### PR TITLE
Trivia custom trivia lists - Delete - Part 2

### PR DESCRIPTION
**Pull request by Stonedestroyer**
### Type

- [ ] Bugfix
- [X] Enhancement
- [X] New feature

### Description of the changes
Depends on #3420
Adds delete so you can delete custom trivia lists, and also adds a way to see which one is a custom trivia list.

### CODE REVIEW

**Comment by Stonedestroyer** [comment]
This PR is not ready but not sure how to mark it as draft when not draft from beginning.

**Comment by Kowlin** [comment]
For the next time, feel free to just add this to the other trivia PR, as these are generally the same functionality.

**Comment by Stonedestroyer** [comment]
@Kowlin If you want me I can close this and merge into Part 1.

**Comment by Kowlin** [comment]
It would be easier for us if you did add it into the other PR. 👍

**Comment by Stonedestroyer** [comment]
Done, can you mark Part 1 as WIP.

**Pull request closed without merging**
