### PR TITLE
[Docs] Dev Cog Guide

### PR DESCRIPTION
**Pull request by bobloy**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
User guide for the Dev cog.
Unsure if this is wanted; I'm interested in hearing feedback.

A step towards the #1734 goal

### CODE REVIEW

**Comment by Drapersniper** [comment]
This brings up a interesting question which I personally have a unpopular opinion of, but should the dev cog guide really be under cog guides main page? Because it's a cog meant for dev use and not for standard use ...

**Comment by bobloy** [comment]
> This brings up a interesting question which I personally have a unpopular opinion of, but should the dev cog guide really be under cog guides main page? Because it's a cog meant for dev use and not for standard use ...

Your comments seem related to #2802 , linking for reference

**Comment by Drapersniper** [comment]
> > This brings up a interesting question which I personally have a unpopular opinion of, but should the dev cog guide really be under cog guides main page? Because it's a cog meant for dev use and not for standard use ...
> 
> Your comments seem related to #2802 , linking for reference

Yup sorry should have made it clear what I was trying to say is should this be in a public doc or internal doc ... because overly advertising the dev cog is recipe for disaster

**Comment by palmtree5** [comment]
> > > This brings up a interesting question which I personally have a unpopular opinion of, but should the dev cog guide really be under cog guides main page? Because it's a cog meant for dev use and not for standard use ...
> > 
> > 
> > Your comments seem related to #2802 , linking for reference
> 
> Yup sorry should have made it clear what I was trying to say is should this be in a public doc or internal doc ... because overly advertising the dev cog is recipe for disaster

Personally, I think this should be documented, but it should be somewhere under ``Red Development Framework Reference`` imo

**Review by Jackenmen — COMMENTED** [review]
(this can be ignored until there's a consensus on whether this guide should even be added)

This PR should update the `.github/labeler.yml` file similarly to how it's done for existing cog guides:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/.github/labeler.yml#L1-L5

```yaml
"Category: Dev Cog":
  # Source
  - redbot/core/dev_commands.py
  # Docs
  - docs/cog_guides/dev.rst
```

**Comment by Flame442** [comment]
Superseded by #5869.

**Pull request closed without merging**
