### PR TITLE
Add `[p]cc raw`

### PR DESCRIPTION
**Pull request by NeuroAssassin**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes
Allow for getting the raw response of a custom command, similar to `[p]tag raw` for R. Danny.  This makes it easier for copy pasting it (in case the bot goes down or something).

### CODE REVIEW

**Comment by entchen66** [comment]
Isn't that the same as [p]cc show?

**Comment by Jackenmen** [comment]
`[p]cc show` has troubles with showing custom commands with code blocks and this doesn't, because it's escaping Discord Markdown. Question is, if it wouldn't be better, if this was just implemented in `[p]cc show` as well. That command could also use some refreshing with embeds and that might be the perfect opportunity for that.

**Comment by Kowlin** [comment]
@NeuroAssassin could you resolve the conflicts for this PR?

**Comment by NeuroAssassin** [comment]
Closing in favor of new PR

**Pull request closed without merging**
