### PR TITLE
[Streams] Add support for game-specific alerts

### LINKED ISSUE #2356: [Streams] Add game whitelist
# Feature request
- [ ] Cog
- [x] Command
- [ ] API functionality

**Cog:** Streams

**Feature Request:** A command/s would allow to filter streams via the game they are playing.
   
**Example;**

**[p]streamalert [platform] [channel] [game]**

         - Filter Stream alert by game per channel

**[p]streamalert [platform] [community] [game]**

         - Filter Stream alert by game per community

As far as I am aware there is only one other bot out there that does this, I believe it would make a great addition to the Streams cog and Red Bot in general.

### LINKED ISSUE #3654: [Feature] Streams | Additional Option
# Feature request

#### Select the type of feature you are requesting:
- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Command: `streamset`
Option: `game`
Syntax: `streamset game <game>`
Function: To set specific game(s) to only alert when a streamer is playing a game from that list.

Useful for servers that are for a specific game.
This might be a bit off topic, but still connected, but maybe be able to seperate specific game(s) alerts from general alerts. So as above I mentioned a Discord for a specific game where you can have alerts for `<game>` in one channel and then be able to have another channel for regular alerts where anything is played. I hope this wasn't too confusing.

### PR DESCRIPTION
**Pull request by palmtree5**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
This will implement #2356 but will also go somewhat above that and implement a way to alert for all channels playing a specific game (though maybe some other filters would be in order on that too), at least for services supporting such a thing via their API (Definitely Twitch and Smashcast, maybe as far as Mixer goes)
Fixes #2356 and fixes #3654

### CODE REVIEW

**Comment by palmtree5** [comment]
So this has wound up needing me to move us over to the new twitch api (helix). At this point, that conversion should be up and running and should just work with previous alerts as well. This will need testing though

I'll work on channels streaming specific games next, though there still might be some refactoring in the `is_online` function in `TwitchStream` to be done

**Comment by palmtree5** [comment]
Ok, for Twitch specifically this should be ready. I haven't actually started on Smashcast/Hitbox or Mixer support for this yet but will soon. Needless to say, this will require a fair bit of testing before merging

**Comment by KongGal** [comment]
When can we expect to see this function in Red bot?

**Comment by Vexed01** [comment]
This is very likely to come in Red 3.2, as you can see by the PR having the 3.2 milestones attached.

**Comment by Kowlin** [comment]
Postponing until ready.

**Comment by Drapersniper** [comment]
@palmtree5  is this PR ready other than the open conflict? if not do you have local changes which you wish to push? just trying to figure out whether we should close this PR as stable or keep it open as you are working on it.

**Comment by palmtree5** [comment]
> @palmtree5 is this PR ready other than the open conflict? if not do you have local changes which you wish to push? just trying to figure out whether we should close this PR as stable or keep it open as you are working on it.

No, not exactly ready as this doesn't even cover Smashcast. Not to mention Mixer's death (though I don't believe I touched any of the code for the Mixer-related commands anyway with this)

**Comment by Drapersniper** [comment]
Do you have any plans to work on it currently, or should it be closed and converted into an issue so others users can pick it up?

**Comment by palmtree5** [comment]
I think I'm going to flat out start from scratch on this as with regards to Twitch specifically, Helix has evolved somewhat since this PR was originally created

**Pull request closed without merging**
