### PR TITLE
[V3] help formatter improvements

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [X] Enhancement

### Description of the changes

This looks to process checks in the help formatter significantly more efficiently.

This depends on changes in #1885, #1963 

This is NOT ready and has several things which need changing since 1963

### CODE REVIEW

**Comment by mikeshardmind** [comment]
This isn't fully working. I'll fix it when I can, but there's a bug with which things get displayed to a user.

**Comment by Kowlin** [comment]
Pushing this to Beta 18 then.

**Comment by mikeshardmind** [comment]
Any remaining work on this will depend on a fix for #1931 being merged, depending on the route used to fix this, nothing more will need changing. As such, this is on hold.

**Comment by mikeshardmind** [comment]
This likely is no longer needed as of #1885 I'd like to see how the help formatter is performing after #1963 as well just to be certain, but this increases the complexity of the help formatter significantly where it may no longer be needed.

Edit:

Still needed due to the special handling required to process permissions checks being dependent on a view. 1963 has the details on that.

**Comment by mikeshardmind** [comment]
I won't be finishing this. This particular one most likely isn't the right approach to this problem, but there are various things in this which may be useful to someone else solving this later. Can be closed, but I'll leave it open for someone else to decide that.

**Comment by mikeshardmind** [comment]
Solved alternatively with #2149

**Pull request closed without merging**
