### PR TITLE
Empty channel check

### PR DESCRIPTION
**Pull request by palmtree5**
Implements the suggestion in https://github.com/Twentysix26/Red-DiscordBot/issues/393

This pretty much just adds a check for seeing if the bot is the only user in the voice channel and if they are, add the server to the timer countdown

### CODE REVIEW

**Comment by palmtree5** [comment]
Also I haven't the slightest clue how but my update check tried to make it in here. Purged it though so the only changed file is audio.py

**Comment by palmtree5** [comment]
Yeah, so it turns out that upon testing this, it didn't work. Turns out 4 lines isn't enough?

**Comment by palmtree5** [comment]
Turns out 6 is though. Newest changes force the bot to stop playing what it's playing and clear its queue if there's nobody else in the channel

**Comment by Twentysix26** [comment]
Can you rebase please?

**Comment by palmtree5** [comment]
Rebase done

**Comment by calebj** [comment]
Looks like you need to rebase again 😕

**Comment by palmtree5** [comment]
Closing, superseded by https://github.com/Twentysix26/Red-DiscordBot/pull/453

**Pull request closed without merging**
