### PR TITLE
Prevent an IndexError from occuring

### PR DESCRIPTION
**Pull request by Kowlin**
If an page value is negative it doesn't properly loop around to the end.

### CODE REVIEW

**Review by leetfin — DISMISSED** [review]

**Comment by Jackenmen** [comment]
Do you remember in what command this was an issue?

**Comment by Ryan5453** [comment]
queue (audio)

**Review by Flame442 — CHANGES_REQUESTED** [review]
`next_page` L138 should also be modified to catch similar out of bounds cases on the top end.

_Or if you want to swap these two methods to use modular arithmetic instead, that would also be a valid way to fix this bug :)_

**Review by Flame442 — APPROVED** [review]
Thanks!

**Pull request merged**
