### PR TITLE
[Core] Add a text only version to `[p]info`

### LINKED ISSUE #3102: Add embedless info command

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
fixes #3102

### CODE REVIEW

**Comment by Drapersniper** [comment]
With custom info: 
image

Without custom info:
image

**Comment by Kowlin** [comment]
~~Does this take into account of the customizable field a owner can set?~~ I'm a potato.

**Review by Flame442 — DISMISSED** [review]
The non-embed info does not have the "Bringing joy since 02 Jan 2016 (over x days ago!)" field, not sure if we want to include that or not. Besides that, this looks all set.

**Comment by Drapersniper** [comment]
> The non-embed info does not have the "Bringing joy since 02 Jan 2016 (over x days ago!)" field, not sure if we want to include that or not. Besides that, this looks all set.

Told you everything in intentional, embedless commands have no right to say they are bringing joy to anyone.

I'll add it "bringing sadness in an embedless world since x"

**Comment by Jackenmen** [comment]
But where's the joy in Discord constantly breaking embeds ;)

**Review by Flame442 — APPROVED** [review]

**Pull request merged**
