### PR TITLE
[General] Add new available guild features in `[p]serverinfo`

### PR DESCRIPTION
**Pull request by owocado**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

These are (some of the) new available guild features I saw on red main server (credits to Kowlin). 😃 
I also sorted the features dict/list alphabetically to make it easier to maintain for future usecase.

Newly added feature are:
* ENABLED_DISCOVERABLE_BEFORE
* MEMBER_VERIFICATION_GATE_ENABLED
* PREVIEW_ENABLED
* WELCOME_SCREEN_ENABLED

Although I am still debating whether `ENABLED_DISCOVERABLE_BEFORE` could really be considered a feature or not but added it anyways.
Please let me know what do you think!

### CODE REVIEW

**Comment by Kreusada** [comment]
+1 to this.
Too much additional info in `[p]serverinfo 1` could turn the command into a clusterfuck of information. But those few features you mentioned would fit in nicely, enabled_discoverable_before could be up for debate but we'll have to wait and see what others think.

**Comment by Kowlin** [comment]
Ye I'm currently thinking that ``enabled_discovery_before`` can be removed for ``discoverable``, as it doesn't really account for anything. Also thank you for the alphabetizing, which is a pet peeve of mine.

**Comment by ltzmax** [comment]
Well... `enabled_discoverable_before` isn't really needed. `discoverable` is enough honestly. :p

**Review by Jackenmen — APPROVED** [review]
I went ahead and remove the `ENABLED_DISCOVERABLE_BEFORE` feature from the list and this should be good to go now.

Thanks for the PR.

**Pull request merged**
