### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aareon**
Fix sentence structure, gramatical, and spelling errors.

### CODE REVIEW

**Comment by ghost** [comment]
In the first paragraph, it should say "to your liking" instead of "for your liking", no?

**Review by Kowlin — COMMENTED** [review]
Looks fine with me, nothing to comment on.

**Review by skeith — COMMENTED** [review]
`for your liking` sounds unnatural

**Comment by Twentysix26** [comment]
The readme is going to be remade in the near future. It's already ready and it will be pushed when the [portal](https://cogs.red/) is completed.

**Pull request closed without merging**
