### PR TITLE
[Core] Improve regionalformat docstrings

### PR DESCRIPTION
**Pull request by Kreusada**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Grammarrrr

### Description of the changes

Small grammar fixes brought up in #support.

### CODE REVIEW

**Review by Jackenmen — CHANGES_REQUESTED** [review]
This needs to also update the cog guide

**Review by Drapersniper — APPROVED** [review]
Nice catch, Thanks!

**Review by Drapersniper — CHANGES_REQUESTED** [review]
Welp ... jacks comments were loaded locally ... I'll let Kreusada edit the docs before merging.

**Comment by Kreusada** [comment]
Requested changes made via #5055

**Pull request closed without merging**
