### PR TITLE
q/pl integration, volume, resolve link, vote %

### PR DESCRIPTION
**Pull request by irdumbs**
### q/pl integration

adding a song to the queue doesn't remove the playlist.
once the current song finishes, the queue plays
the queue must finish before playlist resumes.
if a playlist is started while a queue is playing, the queue must finish before the playlist will start.
### volume

`!audioset volume` by itself displays the current volume
range changed from 0-1 to 0-100
### resolve link

`!queue willow` --> [SEARCH:]willow has been put into the queue by irdumb#1234
after giving it some time to resolve,
`!queue` --> Videos in queue: 1. Jasmine Thompson - Willow (Lyrics)
### settable vote %

settable % votes needed to exceed to skip. 50 == majority

### CODE REVIEW

**Comment by irdumbs** [comment]
huh, I must have reverted passed kowlin's changes.. git y u confusing

**Comment by irdumbs** [comment]
how the heck do you find and resolve the conflicts?

**Comment by irdumbs** [comment]
@tekulvw your assistance is required 😢 
I accidentally committed this,
reverted it by committing the previous commit,
now 3 PRs are conflicting and I can't for the life of me figure out hot to fix it in a safe way

**Comment by tekulvw** [comment]
I'm voting for a hard reset back a few commits

**Comment by irdumbs** [comment]
I agree. you know how? :P

**Comment by tekulvw** [comment]
Functionality in the rewrite...mostly. Vote percent will be in.

**Pull request closed without merging**
