### PR TITLE
[Streams] [WIP] Rewrite

### PR DESCRIPTION
**Pull request by Twentysix26**
Left to do:

- [x] Mention settings for stream alerts (custom roles too?)
- [ ] Tests

### CODE REVIEW

**Comment by Kowlin** [comment]
Someone in the support channel hinted at the fact that there is no list command for the stream alerts, seems like a good time to add one.

**Comment by tekulvw** [comment]
Can we loop #364 into this? Do we want to implement 364 in V2?

**Comment by palmtree5** [comment]
Tbh references to Hitbox should probably be changed to Smashcast because of the branding change there (though https://hitbox.tv redirects to https://www.smashcast.tv/ at the moment)

**Comment by palmtree5** [comment]
#847 and #849 have been merged into this.

- 847: 
  - Mentions for stream alerts
    - Everyone, here, individual roles
      - For roles, the role must be mentionable (i.e. the "Allow anyone to @mention this role" setting for the role in server settings must be enabled) when attempting to enable alert mentions for the role
- 849:
  - Twitch community support
    - Doesn't have mention support at the moment but that can probably change
    - See https://github.com/Cog-Creators/Red-DiscordBot/pull/849#issuecomment-313531782 for a description of the community support

**Review by tekulvw — APPROVED** [review]

**Pull request merged**
