### PR TITLE
Slowmode now accepts integer only inputs as seconds

### PR DESCRIPTION
**Pull request by DevilXD**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

The `[p]slowmode` command now accepts integer only values as seconds.
Instead of doing `[p]slowmode 10s` one can do `[p]slowmode 10` for the same effect as well.

### CODE REVIEW

**Comment by DevilXD** [comment]
Hmm, so apparently Travis failed on docs only because of the new changelog stuff. Note that this PR doesn't even touch docs, so hopefully it should be good regardless .-.

**Comment by mikeshardmind** [comment]
Needa a changelog entry. I think Github should have prompted that the contribution guidelines were updated.since.your last PR.

**Comment by DevilXD** [comment]
Didn't know this. Should be alright now I guess

**Review by mikeshardmind — APPROVED** [review]
👍

**Pull request merged**
