### PR TITLE
[Audio] Fix 'Nonetype has no attribute "server"' issues

### PR DESCRIPTION
**Pull request by Aioxas**
Fixes 2nd part of issue [#425]

Caused by queuing a song using [p]play when the bot is in the voice channel, but the queuer isn't.

### CODE REVIEW

**Comment by Aioxas** [comment]
Woops, wrong PR closed.

**Comment by tekulvw** [comment]
A check for this should already happen outside of this function because you can't just randomly use `bot.say` outside of a command function (and sometimes even within one).

**Comment by Aioxas** [comment]
Seems like it doesn't. For some strange reason. I checked and rechecked and I was running into that error more than once. Only when I put that try except block, did it stop throwing errors and threw the message instead.

**Comment by tekulvw** [comment]
It does happen, just one scope too far down. Check #440

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/pull/440

**Pull request closed without merging**
