### PR TITLE
[Misc] Typo fixes

### PR DESCRIPTION
**Pull request by Stonedestroyer**
### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fixes some doc strings so shouldn't be breaking anywhere.

### CODE REVIEW

**Comment by Stonedestroyer** [comment]
Will just rebase my edits into #3427. Forgot I had that one.

**Comment by Stonedestroyer** [comment]
Closed the wrong one oops.

**Comment by Drapersniper** [comment]
@Stonedestroyer  is this ready for review?

**Comment by Stonedestroyer** [comment]
> @Stonedestroyer is this ready for review?

Yes

**Review by Drapersniper — CHANGES_REQUESTED** [review]
Everything is looking good, however can we get a bugfix change log for the trivia typo fixes please.

**Comment by Stonedestroyer** [comment]
> Everything is looking good, however can we get a bugfix change log for the trivia typo fixes please.

There is one in the line, https://github.com/Cog-Creators/Red-DiscordBot/pull/3427/commits/626751bf2d04f14ffc00e526d20c25c100d2f816 . Or do you want a seperate file?

**Comment by Drapersniper** [comment]
> > Everything is looking good, however can we get a bugfix change log for the trivia typo fixes please.
> 
> There is one in the line, [626751b](https://github.com/Cog-Creators/Red-DiscordBot/commit/626751bf2d04f14ffc00e526d20c25c100d2f816) . Or do you want a seperate file?

Separate called,  `3424.bugfix.rst`  since these are user facing strings it shouldn't be a misc entry

**Review by Drapersniper — APPROVED** [review]
LGTM

**Pull request merged**
