### PR TITLE
Add `on_red_before_identify` dispatch

### PR DESCRIPTION
**Pull request by fixator10**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes

Adds a dispatch of `on_red_before_identify` event in `before_identify_hook`

Allows detecting `IDENTIFY` without editing core

### CODE REVIEW

**Comment by Jackenmen** [comment]
This should use `red_` prefix to avoid potential conflict.

**Comment by PredaaA** [comment]
I don't think it should be called `on_red_identify`. Because as that hook is named, it's *before* IDENTIFY happen that it is called, and also because d.py already dispatch `on_connect` and `on_shard_connect` events, which is when IDENTIFY happens.

https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.before_identify_hook
https://discordpy.readthedocs.io/en/latest/api.html?highlight=on_connect#discord.on_connect
https://discordpy.readthedocs.io/en/latest/api.html?highlight=on_connect#discord.on_shard_connect

So I guess it should be called `on_red_before_identify` instead.

**Comment by Jackenmen** [comment]
I would love to hear some sample use case(s) for this. While it's not really hurting us to have this dispatch, some justification is always nice to have :)

**Comment by Rapptz** [comment]
This could be potentially useful for tracking how many times a shard has disconnected. I do some basic tracking like this in my bot to see how many identifies and resumes I've had per shard in a 24 hour period.

**Review by Jackenmen — APPROVED** [review]
Let's get this merged then, thanks!

**Pull request merged**
