### PR TITLE
Change note to attention

### PR DESCRIPTION
**Pull request by PythonCoderAS**
### Description of the changes

Changes a note box to an attention box. This is done because the contents of the box should be emphasized. 

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Comment by flaree** [comment]
imo development version should not be emphasised to users. It could contain anything from  breaking changes to in development featues.

Not to mention that using development is technically grounds for no support, so more people potentially just blindly copy pasting something because its more emphasised is not great.

**Comment by PythonCoderAS** [comment]
> imo development version should not be emphasised to users. It could contain anything from breaking changes to in development featues.
> 
> Not to mention that using development is technically grounds for no support, so more people potentially just blindly copy pasting something because its more emphasised is not great.

Sorry, I meant that the **danger** should be emphasized more.

**Comment by Flame442** [comment]
image
This is how it currently appears. `Attention` is used to outline the risks of the development version and `Note` is used for the steps to actually install it (with its own little warning as well to be safe). I feel like the danger is stated in multiple places and it is emphasized as appropriate

**Comment by PythonCoderAS** [comment]
I think the "No support" line should at least be moved to the earlier box.

**Comment by Jackenmen** [comment]
Thanks for your contribution but currently we are not interested in this change.

**Pull request closed without merging**
