### PR TITLE
Added [p] whitelist show (and clear) & [p] blacklist show (and clear)

### PR DESCRIPTION
**Pull request by ddday**
Had requests to make handling easier( #202 ) so as the title suggests i've added [p] whitelist show and clear + [p] blacklist show and clear.

### CODE REVIEW

**Comment by ddday** [comment]
I have no idea why the other files were committed, but "	Added [p] whitelist show (and clear) & [p] blacklist show (and clear)" is the correct one.

**Comment by tekulvw** [comment]
Something is weird with your PR, wrong files being changed

**Comment by ddday** [comment]
Yeah...

**Comment by tekulvw** [comment]
Might I suggest `git rebase -i`? Take a look at the git documentation. Gonna close until this is fixed.

**Pull request closed without merging**
