### PR TITLE
Fill out license info

### PR DESCRIPTION
**Pull request by pgaetani**
Based on a conversation had with Danny in the lounge, might also be a good idea to review if this really is the license required.

### CODE REVIEW

**Comment by pgaetani** [comment]
Also not sure if the author's real name is required, gonna look that up.

Update:

> There may be slight downsides to using a pseudonym - for more information on this you can see this PDF from copyright.gov which says in part "An author of a copyrighted work can use a pseudonym or pen name" and "If a copyright is held under a fictitious name, business dealings involving the copyrighted property may raise questions about its ownership". The copyright for pseudonymous works may also be linked to a standard timeframe rather than the author's life + 70 years.

Source: https://opensource.stackexchange.com/questions/4023/must-authors-name-be-included-in-gnu-gpl-v3

**Comment by Kowlin** [comment]
Hah! ye, Github should really notify about that.

**Comment by pgaetani** [comment]
Would also like a clarification on what license third party cog repos should have. I'm currently using MIT for most of my projects, but am not actually sure if I need to inherit Red's GPL or if I can keep my own license.

**Comment by Redjumpman** [comment]
I can ask an expert on this later today and have her type up  a tl;dr on what you need. I think the main questions I would have for you are:

1. What are your concerns about licenses
2. What do you want to prevent?
3. What is your current understanding of how things work?

Source: My wife is a patent attorney and has been a part of many large cases involving patents, copyright, and anti-trust with a ton of large companies. If you are super worried about what people are doing with your source I might be able to get her to do an AmA on saturday.

**Comment by pgaetani** [comment]
Mostly want to clarify not just for my sake but for the sake of the bot's code.

1. Is Red in particular using the proper license? 
Say, if any part of this has some of Danny's code, should it not have inherited his MIT license? (please ignore this if I'm talking nonsense, as it's out of concern from a comment Danny made in the server)
Also, are third party cog repos considered a subset of Red, therefore requiring us to inherit Red's GPL license?
2. Not looking to prevent anything myself, just want to make sure we're all (or at least, I'm) following proper procedure. 
3. Little to none, I know what some license permissions, conditions and limitations are, but have not delved deep enough to fully understand what's going on.

Sorry if my request reeks of ignorance, but I am genuinely curious/concerned.

**Comment by Twentysix26** [comment]
f1fcdf80da870b20f31df73bd251744b176dbb5b

**Pull request closed without merging**
