### PR TITLE
!audioset status

### PR DESCRIPTION
**Pull request by irdumbs**
#301

### CODE REVIEW

**Comment by tekulvw** [comment]
You know you can just push another commit to this branch so you don't have to keep making new PRs...

**Comment by irdumbs** [comment]
the old branch I no longer had write access to

**Comment by franc-ist** [comment]
Works

**Comment by Zackery** [comment]
It doesn't seem like the bot is leaving the room after its done playing songs with this script.

**Comment by tekulvw** [comment]
That is far more likely a result of discord's recent issues that they've _supposedly_ fixed

**Pull request merged**
