### PR TITLE
[Core V3] Pagify Priority

### PR DESCRIPTION
**Pull request by Zephyrkul**
Allows setting pagify to prioritize earlier delims over later ones with the `priority` kwarg.

Requested by irdumb in a Discord conversation.

### CODE REVIEW

**Comment by tekulvw** [comment]
rebase please

**Comment by Zephyrkul** [comment]
Okay, I attempted a rebase, and at first glance it looks like I did it right.

**Comment by tekulvw** [comment]
You did but we added a fix from RJM for a current issue in pagify, can you rebase again with your additions?

**Comment by palmtree5** [comment]
still needs rebase

**Comment by Zephyrkul** [comment]
For whatever reason I can't rebase (git can't seem to find merge-base), so I'll be opening another branch when I see a period of less commits at once (and when I remember) since this one seems to be getting delayed on the merge for other, higher-priority commits.

**Pull request closed without merging**
