### PR TITLE
[CI] Stop messing with our contributor data with automated PRs

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### CODE REVIEW

**Comment by mikeshardmind** [comment]
oh ffs, almost right the first time. Have to grab that conditionally elsewhere

**Comment by mikeshardmind** [comment]
RE: discussion in discord.

While this works, we're just going to leave it as-is.

It's just something which irks me a little bit about this, and not something which actually matters in the grand scheme of things.

**Comment by mikeshardmind** [comment]
Reopening after *more* discussion.

**Comment by Kowlin** [comment]
We're doing it anyhow :eyes:

**Review by Kowlin — APPROVED** [review]
LGTM, Waiting for Jack.

**Pull request merged**
