### PR TITLE
Backups for realsies

### PR DESCRIPTION
**Pull request by Kowlin**

### CODE REVIEW

**Comment by tekulvw** [comment]
@Twentysix26 I vote merge

**Comment by Twentysix26** [comment]
This is not an oversight. This function was made to try and tackle the json corruption issues. I didn't know the reason at the time and the only likely cause I found were crashes during saving. So I figured that if the bot  crashed it would never reach the copy part.  

This is all useless. The corruption issues were due to the fact we were saving with dumps instead of dump and I was planning to remove this backup feature since that has been fixed

**Comment by Kowlin** [comment]
Planned and never got around to it huh :P

**Comment by Twentysix26** [comment]
I'll do it after Will's PR. No rush

**Pull request closed without merging**
