### PR TITLE
Added Patch Notes to downloader, continuation of work from TheGrumpiestVulcan

### PR DESCRIPTION
**Pull request by Redjumpman**
This PR combines the previous work done by Calebj(PR #363) in an earlier PR, and all credit goes to him for the new downloader aspects. My contribution adds patch notes which pulls from the github api, and displays:

short hash
commiter
commit message

I've added a form of error handling to attempt to print out any issues in gathering the patch notes for the cog. The code is OK, but could have some improvements in different places. Going on vacation for 17 days, but hopefully most of the ground work is laid out for someone to easily do an improvement. If not I'll work on it upon return and rebase.

### CODE REVIEW

**Comment by Redjumpman** [comment]
@neonobjclash made some significant improvements and optimizations to my patch notes work on downlaoder. It is already being tested by a few individuals, but anyone who is trying it out please report your findings.

**Comment by calebj** [comment]
I've been thinking, why can't we parse the output of `git log [file]`?

**Comment by Kowlin** [comment]
I've said the same to @Redjumpman. And he was not aware that this was a feature :P

**Comment by Redjumpman** [comment]
Sadly, no I didnt know about git log until kowlin showed me. T.T but, nothing stopping yall from writing it. I just felt comfortable doing it this way. There is a definite  need for a patch notes system to be added to downloader and no one was working on it. Has anyone started on a git log version? I am overseas travelling for a while so I won't be able to contribute. @twentysix thoughts on what you would want for this to be approved?

**Comment by calebj** [comment]
I actually made another PR to your fork that does exactly that two days ago.

**Comment by Redjumpman** [comment]
Ah cool. At this point none of the work is actually mine, and since I am unavailable to contribute I am going to close this and let you submit for approval. Good work :D

**Pull request closed without merging**
