### PR TITLE
Allow creating an instance non-interactively

### LINKED ISSUE #2396: Allow redbot-setup to be run in headless mode
See https://cogboard.red/t/allow-headless-setup-command/250

Necessary for Docker deployment of v3, otherwise an [Expect script](https://forums.docker.com/t/dockerfile-how-to-answer-install-question-from-application/5240) needs to be written to answer the GUI questions for redbot-setup.

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes

resolves 2396 and makes future work with containers more bearable.

example use
```
redbot somename --make-instance
```

further modification supported by use of edit, this just creates with defaults (allowing it to be used in conjunction with non-interactive editing of existing instances via edit for headless setup)

### CODE REVIEW

**Comment by LGACode** [comment]
YES. I have to use Expect right now to answer the interactive setup for Docker because Docker does not play nice with interactive command prompts. I've had to update the expect script every time for the last 3 Red updates because the wording in the sentence about what characters are allowed in the instance name was slightly changed every time, and Expect is pretty harsh about how it detects the questions and answers...

A headless way of running redbot-setup would solve all these issues for Docker and we would no longer have to rely on things like Expect. Maybe even paving a way towards full Docker support?

**Comment by Drapersniper** [comment]
Just because this is a PR, doesn't mean Docker is supported.

Eventually when Docker support is a priority we will work on it, until then 🤷 as we have higher priority stuff going on at the moment.

**Comment by mikeshardmind** [comment]
Just a heads up, while Docker may not be supported by this PR, this PR should give people tools to go do their own thing more easily until we do support it. I have no intention of this being part of a larger PR set, just acknowledged in the description that it happens to help with other goals too.

**Comment by Kowlin** [comment]
Well this beats my solution of just manually placing an config file with the bot 😄

**Comment by Jackenmen** [comment]
> further modification supported by use of edit

While this isn't in scope of this PR, something worth noting is that PostgreSQL driver currently does not support headless configuration of storage details.

**Comment by mikeshardmind** [comment]
No, but Postgres does support env vars for providing these details (should likely support setting this non-interactively later on, but it's a problem that doesn't require something like an expect script to work around at least)

**Pull request closed without merging**
