### PR TITLE
[Audio] Add "[p]cache stats" command

### PR DESCRIPTION
**Pull request by americanhanko**
**This PR:**
- Adds a `!cache maximum` command to give the user the current maximum cache value
- Removes a duplicate `outtmpl` key from `youtube_dl_options` dictionary
- Fixes some PEP8 whitespace and newline issues

### CODE REVIEW

**Review by tekulvw — APPROVED** [review]

**Comment by Twentysix26** [comment]
Three different commands that show three different stats about the same thing seem a bit silly. Mind turning all these into a single command (`[p]cache stats` would be fine) that shows min, max and current size together?

**Review by Twentysix26 — CHANGES_REQUESTED** [review]
A single `[p]cache stats` command for min, max and current size would be better

**Review by Kowlin — COMMENTED** [review]
I'm a little confused, will this also remove older files that are over the max cache size? Or was that already build into the system?

**Comment by americanhanko** [comment]
@Twentysix26 Apologies for the delayed response. Having `[p]cache stats` makes far more sense. Working on it now.

@Kowlin This change wouldn't modify any files. It would only report the current values for `cache_minimum`, `cache_maximum` and `cache_size` to the user.

**Comment by Kowlin** [comment]
Ah ye okay, I see. Source digging does wonders from time to time.

**Review by Kowlin — APPROVED** [review]

**Review by tekulvw — APPROVED** [review]

**Comment by americanhanko** [comment]
Sorry for so many pushes...

Here's what the output looks like as of right now:
1. screenshot 2017-07-25 12 23 47

Some other ideas:
2. screenshot 2017-07-25 12 27 29
3. screenshot 2017-07-25 12 27 36

**Comment by Twentysix26** [comment]
I think the number 3 would look best 👌

**Comment by bobloy** [comment]
Graphical percent of total?

E.G.

Current: 69.97 MB
Min: 60.0 MB  █▒▒▒▒▒▒▒▒▒ Max: 1000.0 MB

**Comment by Kowlin** [comment]
Seems a bit overkill for something as little as data.

**Review by Twentysix26 — APPROVED** [review]

**Pull request merged**
