### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by Proximyst**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Instead of cloning empty submodules, it should now automatically pull all of the modules as it is from remote. This allows for repositories to be their own cogs and rather use submodules in an "indexing" repository, as we do with https://github.com/r-Norge/tannhjul

### CODE REVIEW

**Comment by Tobotimus** [comment]
Hi, thanks for your PR.

Unfortunately I'm gonna freeze this as V2 is at a very low priority (technically it's bugfix-only). It will probably be closed if it doesn't get any attention over the next few months.

**Comment by mikeshardmind** [comment]
I'll just toss on a note, that if you want this behavior in V3's downloader, you may want to add a note on #1968

**Comment by Proximyst** [comment]
@Tobotimus The PR is mostly to help out people using such, as us over at r/Norge wish to use it for the bot we call Askeladden (A Norwegian folk tale icon), and we wish to have the repositories in an easy way to handle with proper permissions. Seeing as the server is relatively small at little over 3k users, there is without a doubt others who most likely also would like to see this be added for their own organisational usecases and simply for the fact that it's simple to handle.

@mikeshardmind I will be sure to do so in a moment, thank you!

**Comment by mikeshardmind** [comment]
Right now, V3's downloader updates submodules. As this is a behavior change, and not a critical fix or a non-code change, We're not going to include this for V2's EOL support, but if there's anything else with this you need for V3, feel free to let us know.

**Pull request closed without merging**
