### PR TITLE
[Audio] Hotfix an edge case where an attribute error can be raised

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### CODE REVIEW

**Comment by mikeshardmind** [comment]
For context on this wrt a hotfix changelog, what would a typical user see when this errored?

**Comment by Drapersniper** [comment]
Honestly not quite sure ....I only reproduced while playing Spotify playlists and debug logs aren’t giving me any extra context just after some trial and error this one worked for me and stop reproducing

**Comment by mikeshardmind** [comment]
I see how this would fix that, was just hoping to get something a little clearer for the changelog if possible.

**Review by mikeshardmind — DISMISSED** [review]

**Comment by Drapersniper** [comment]
Hmm turns out this can open in prod 👍

**Review by mikeshardmind — APPROVED** [review]
Prior info about this *only* being possible under user error circumstances was wrong.

This does mean this only handles one half of the issue though

**Pull request merged**
