### PR TITLE
Typo fix on `[p]invite` command

### PR DESCRIPTION
**Pull request by PythonTryHard**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Correcting one typo by removing one apostrophe

### CODE REVIEW

**Comment by Drapersniper** [comment]
Please don't edit the .po files, the actual string in the code needs to be fixed here

Line 437 in redbot/core/core_commands.py (if the po files are up to date)


Edit: https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/core/core_commands.py#L1149 is the correct line to be editing here

**Comment by PythonTryHard** [comment]
Should I do `git commit --amend` followed by a `git push --force` on my fork? The typo fix was done from browser

**Comment by Drapersniper** [comment]
Up to you how you wish to do it, you could revert the commit and apply to the correct place,
Open a new PR.

Force push, anyway you want to go about it is fine, the commit history doesnt matter as it is squashed when merged to the dev branch anyways.

**Comment by PythonTryHard** [comment]
Forced-push on my fork, it should now be on the correct place

**Review by Drapersniper — APPROVED** [review]
LGTM

**Pull request merged**
