### PR TITLE
[General] Fix usage in choose help

### PR DESCRIPTION
**Pull request by TrustyJAID**
Also improve doc-strings to explain usage.

### CODE REVIEW

**Review by Jackenmen — COMMENTED** [review]
I think the usage syntax should continue to represent that the command requires *at least* 2 choices to pick from.
One of the alternatives (suggested by Danny) would be:
`<first> <second> [others...]`

**Comment by TrustyJAID** [comment]
While I don't disagree I believe this is the better option for a few reasons. First of all the requirement of 2 is already described in the help string and the only place the usage appears is in the help command. Second, in terms of educating users on what the usage actually means this is provides a good stepping stone that more than one option is available and there is only one type of argument. Or in other words this teaches that things like `<arg...>` means more than one option is possible while the help string aids this command by stating that at least 2 are required and it errors on fewer than 2 anyways.

**Review by Drapersniper — DISMISSED** [review]
LGTM, I made a typo fix and fixed the line break in addition to updating the General docs with your new docstrings. Thanks for contributing!

**Review by Drapersniper — DISMISSED** [review]
Jack Approves my own changes.

**Review by Drapersniper — APPROVED** [review]
THIS IS IT!

**Comment by Jackenmen** [comment]
If this ever comes back again, I'm personally going to make this @Flame442's problem 😃

**Pull request merged**
