### PR TITLE
[V3 Audio] Add Lavalink Jar build to settings

### PR DESCRIPTION
**Pull request by TheWyn**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

Added Lavalink Jar build to Lavalink settings since build number now stored in config.

### CODE REVIEW

**Comment by tekulvw** [comment]
I'm hesitant to merge this now because of the impending audio overhaul. We may just opt to integrate these changes into that PR.

**Comment by Kowlin** [comment]
I agree with that Will. I think its better to wait for the overall PR.

**Comment by Kowlin** [comment]
PR has Merge conflict after merging #1440, please resolve this.

**Comment by tekulvw** [comment]
New lib doesn't have a `__version__` yet, will need to add that first.

**Comment by TheWyn** [comment]
Done @Kowlin

**Review by palmtree5 — APPROVED** [review]

**Pull request merged**
