### PR TITLE
[Docs] Update console image in Getting Started guide for Rich logging 

### PR DESCRIPTION
**Pull request by Vexed01**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
The current image in the Getting Started guide is from 3.0.0 and is very poor, so this PR replaces it with a new, rich image.

All ready for review now (23 Dec) after being frozen whilst rich logging was implemented (#4577).

### CODE REVIEW

**Comment by Drapersniper** [comment]
So I was gonna approve then noticed an issue here....
Why is postgres not mentioned on extensions with a cross...

I would say we should fix that then update this image (Unless there is a reason not to?)

**Comment by Vexed01** [comment]
This isn't in the list of things that go there, so putting something in the image that users won't see is the reason it's not there.
```py
        options = (
            ("Voice", True),
            ("Docs", reqs_installed["docs"]),
            ("Tests", reqs_installed["test"]),
        )
```
~~Should this be a separate PR or?~~

**Comment by Drapersniper** [comment]
Oh yes I know, i wasn't referencing the fact thats missing in the image, but the fact thats missing.

Kowlin is actually currently working on this, for context: https://ptb.discordapp.com/channels/133049272517001216/133251234164375552/717806973294215219

So I would say hold of on this PR for now and when the updated look is ready this PR can be unfrozen.

**Comment by Vexed01** [comment]
Now reopened/undrafted, because #4577 has been merged!
Ready for review.

**Review by Kowlin — APPROVED** [review]

**Comment by Kowlin** [comment]
Looks great, thanks!

**Pull request merged**
