### PR TITLE
Provide error handling/user feedback when audio cog fails to load song/playlist

### PR DESCRIPTION
**Pull request by mvanalphen**
Currently, when YouTube-DL runs into an issue when downloading a song or playlist, it fails silently and does not provide any feedback to the end user. An example of such an issue is geo blocking: if the video is unavailable in the host's country, the video will fail to load silently.

This pull request remedies this by enabling YouTube-DL to throw exceptions and handling these exceptions in the audio cog. Now, when a video or playlist can not be downloaded for whatever reason it will provide the user with feedback. Additionally, if the video exceeds the maximum length it will now also inform the user.

When there's an item in the queue that can not be played, the user will be informed about this when the queue list is requested.

[Here's a screenshot example.](http://i.imgur.com/6TD9U2S.png)

To do this, this pull request does the following:
- It refactors the queue array so it uses enumeration values instead of magic strings. For instance, `self.queue[server.id]["QUEUE"]` now uses `self.queue[server.id][QueueKey.QUEUE]`.
- It adds a new class `QueuedSong` which is used to populate the song queue. This class consists of the URL of the queued song (which is currently the only thing stored in said array) and the channel the command was issued from.
- The `ignoreerrors` configuration option of YouTube-DL has been set to `false`: instead, the `Downloader` class now catches the `youtube_dl.utils.DownloadError` exception and includes the error message in the `error` property. Once the Downloader thread finishes, the downloader is checked for this error value, and if it is set a `YouTubeDlError` is thrown.
- The `YouTubeDlError` exception is caught in the `_play` method of the `Audio` class and its error message is passed on to the user. Error handling has also been added to other methods that use the `Downloader` class.

I'm not exactly a battle-hardened Python coder so please do let me know if I'm doing something wrong! I've tested this myself and couldn't find any issues, but more testing is of course always welcomed.

Closes https://github.com/Twentysix26/Red-DiscordBot/issues/877

### CODE REVIEW

**Comment by mvanalphen** [comment]
I've finished reviewing/testing this and can't find any issues. I think this is good to go, but more testing is of course always appreciated.

Should I squash these commits, or do you guys not mind/prefer more separate commits?

**Comment by tekulvw** [comment]
Can you contact me on the support server when you get a moment?

**Comment by TheWyn** [comment]
😍 , will be testing as well.

**Comment by mvanalphen** [comment]
@Wyn10 Thanks!

Keep in mind that due to the V2 feature lock the future of this PR is unclear and it may not be merged. Of course you can always just copy over the code to your audio.py file if you still want to use the error handling.

**Comment by TheWyn** [comment]
@Markolie Seems more like a bug fix then a feature to me 😛 , yeah I copied it over to the existing audio.cog.  Haven't managed break the changes playing video's all afternoon with various issues (Geo/Max Length/Not Available).  It's caught them all.

**Comment by mvanalphen** [comment]
Cool! Thanks again for testing it :). Happy to hear it's working well!

**Comment by tekulvw** [comment]
I'm not going to be able to personally test this, but I think it'd help try to move this along if you could get a few more users to try to break this and report back here.

**Comment by mvanalphen** [comment]
I'll see what I can do in terms of testing - unfortunately enough I'm not very familiar with the community but I'll ask around in Discord to see if anyone's willing to help. 

Things are looking pretty good though - my own bot has been playing music heavily and hasn't run into any issues, and from the looks of it all is well on @Wyn10's end as well.

**Comment by TheWyn** [comment]
Correct 👍 .

**Comment by aikaterna** [comment]
I went through and tested the changes, the only thing I could suggest is perhaps add < >  around the urls on lines 868, 877, and 2196 so that they don't show a preview of the video in chat. When a term is searched and it gives an exception, this might lead to odd formatting like `I'm unable to play URL '<[SEARCH:]searchterm>' because it exceeds the maximum audio length.`.

I added this URL as a playlist and attempted to start it: https://www.youtube.com/playlist?list=PLskV5gsZcuewZ-R_xFw5X7PWrzSggpMiy

In current audio, if you queue this playlist, the console gets spammed with:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Red-DiscordBot\cogs\audio.py", line 2057, in queue_manager
    song = await self._play(sid, url)
  File "C:\Red-DiscordBot\cogs\audio.py", line 807, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Red-DiscordBot\cogs\audio.py", line 603, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Red-DiscordBot\cogs\audio.py", line 253, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```

With this version of audio, the bot gave this exception and died:
```
Exception in thread Thread-127:
Traceback (most recent call last):
  File "lib\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "lib\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "lib\youtube_dl\extractor\youtube.py", line 1516, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: KKCTu9jjz_w: YouTube said: "Serenade for Two -Single ..."
This video is no longer available due to a copyright claim by ã‚¨ã‚¤ãƒ™ãƒƒã‚¯ã‚¹ãƒ»ã‚°ãƒ«ãƒ¼ãƒ—ãƒ»ãƒ›ãƒ¼ãƒ«ãƒ‡ã‚£ãƒ³ã‚°ã‚¹æ ªå¼ä¼šç¤¾.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\threading.py",
line 914, in _bootstrap_inner
    self.run()
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 256, in run
    self.get_info()
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 285, in get_info
    process=False)
  File "lib\youtube_dl\YoutubeDL.py", line 785, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "lib\youtube_dl\YoutubeDL.py", line 602, in report_error
    self.trouble(error_message, tb)
  File "lib\youtube_dl\YoutubeDL.py", line 555, in trouble
    self.to_stderr(message)
  File "lib\youtube_dl\YoutubeDL.py", line 508, in to_stderr
    self._write_string(output, self._err_file)
  File "lib\youtube_dl\YoutubeDL.py", line 487, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "lib\youtube_dl\utils.py", line 1389, in write_string
    if _windows_write_string(s, out):
  File "lib\youtube_dl\utils.py", line 1373, in _windows_write_string
    raise OSError('Failed to write string')
OSError: Failed to write string
```

**Comment by mvanalphen** [comment]
Thanks for taking the time to test it @aikaterna. It's much appreciated!

I'll definitely implement your URL suggestion and also catch the OSError exception (not sure why that is raised, will investigate). 

Thanks again!

**Comment by mvanalphen** [comment]
Looks like YouTubeDL/the bot runs into a problem when writing errors to your system @aikaterna (presumably because of UAC or a similar security measure). When that error happens, the bot will now add a warning to Red's debug file and not break hopefully. Additionally, I've removed the URL preview when the bot posts an error.

Would mind testing these changes one more time for me @aikaterna? I can't reproduce the OSError exception myself.

**Comment by Twentysix26** [comment]
Tested it a bit and it seems to work. I can confirm the `[SEARCH:]` thing still being present in the error, that should be removed on output

**Comment by mvanalphen** [comment]
Thanks for testing it @Twentysix26. URL's should now be cleaned before the bot outputs them in an error warning: `[SEARCH:]` is removed and non-URL's won't be surrounded by `<>`. If the error does contain an URL, Discord won't preview the URL as before.

**Comment by aikaterna** [comment]
Using that same test playlist, this was repeated in the console with no error output in chat:

```
[11/08/2017 19:45] WARNING audio_markolie run 264: An operating system error occurred while downloading URL 'https://www.youtube.com/watch?v=LJttZ_Zfiw0':
'Failed to write string'
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Red-DiscordBot\cogs\audio_markolie.py:2113> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 2152, in queue_manager
    song = await self._play(sid, url, channel)
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 864, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 651, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Red-DiscordBot\cogs\audio_markolie.py", line 275, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```
The bot didn't crash, and responded to input still.

**Comment by mvanalphen** [comment]
The latest commit should resolve the issue @aikaterna. The task exception retrieval error should be gone now (unfortunately enough I still can't reproduce the OSError myself though). 

The failed to write string warning should continue to show up: it's not relevant to the user playing music as it only prevents Python/YouTubeDL from writing errors so the bot does not output it, but it is relevant to the owner of the bot.

Thanks again!

**Comment by TheWyn** [comment]
@aikaterna Has the latest commit fixed the issue for you?

**Comment by aikaterna** [comment]
I get the same OSError that I reported the first time and the bot dies.

**Comment by mvanalphen** [comment]
I'll look into it again, but not being able to reproduce the error is proving somewhat problematic.

**Comment by mvanalphen** [comment]
I can't seem to figure this OSError issue out (I'm not sure if it's something I can fix on my end anyway). When an error occurs, YouTubeDL first outputs this error to the console (https://github.com/rg3/youtube-dl/blob/70851a95c307880f016fcb6f37427a8eeae73cad/youtube_dl/YoutubeDL.py#L558) and then raises the DownloadError. 

Normally, writing to the console doesn't cause any issues. However, in aikaterna's case, it fails here because it can't write to the console:
https://github.com/rg3/youtube-dl/blob/5b232f46dcbdc805507c02edd4fd598f31d544d5/youtube_dl/utils.py#L1372

Because the OSError is thrown before the DownloaderError, the bot won't be able to properly output the downloading error. Setting the verbose option to false does not fix this. Presumably because of a bug in YouTubeDL, it only checks if verbose is set, not if it's set to true or false.

Any help with this would be appreciated.

@aikaterna: To double check: are you running the bot command prompt/.bat as an administrator?

**Comment by tekulvw** [comment]
Couldn't you catch the `OSError` in line 285, the `get_info` method, check to see if there is an error that it was raised from, and re-throw/handle the original error?

It seems to me like this is a really specific Windows issue related to writing to stderr (does windows even have stderr?) and it may take a really hacky solution like that to handle this.

Edit: The previous exception in the exception chain can be gotten from the `__cause__` attribute on the current exception. If there is no previous exception, it should be `None`.

**Comment by mvanalphen** [comment]
YouTubeDL does seems to use some sort of a massive hack to write to the console in Windows whereas for other operating systems it uses built-in Python functions. Which is probably why this issue is happening.

The issue is that YouTubeDL is returning the OSError before anything else, so I'm not sure how I'm able to retrieve the original error: the original error isn't thrown until after it tries to write to the console. 

The `report_error()` and `trouble()` methods that handle all of this are called from another exception handler (https://github.com/rg3/youtube-dl/blob/70851a95c307880f016fcb6f37427a8eeae73cad/youtube_dl/YoutubeDL.py#L798).

**Comment by tekulvw** [comment]
Python 3 provides ways to access it, see my edit from the previous comment.

**Comment by mvanalphen** [comment]
@aikaterna I've pushed another fix that hopefully fixes the issue you're having. Would you be willing to test it another time to see if this resolves it? Sorry for the hassle!

**Comment by mvanalphen** [comment]
After the most recent update it's are still not working properly: https://github.com/Markolie/Red-DiscordBot/blob/29e3b5dc07a9336b5c33cd2a85aa10f1dd6d8db3/cogs/audio.py#L265 is not passing. The warning does show up.

Either `e.__cause__` is `None` or not an instance of the two listed exceptions. I'm almost certain it's the former option. In that case I'm really not sure how I can still go about fixing this. Another options is to try to fix this issue on @aikaterna's end: there must be a reason this error is showing up (due to some permission error perhaps?) and I can't reproduce it on Windows.

**Comment by mvanalphen** [comment]
I've done some more digging, and one thing that caught my eye in @aikaterna's error message seems to be improper encoding of the error message: 
`This video is no longer available due to a copyright claim by ã‚¨ã‚¤ãƒ™ãƒƒã‚¯ã‚¹ãƒ»ã‚°ãƒ«ãƒ¼ãƒ—ãƒ»ãƒ›ãƒ¼ãƒ«ãƒ‡ã‚£ãƒ³ã‚°ã‚¹æ ªå¼�ä¼šç¤¾.`
I'm going to see if I can enforce UTF-8 encoding. Perhaps that's been the issue all along?

**Comment by aikaterna** [comment]
Latest commit worked, outputted the appropriate error to Discord chat.

**Comment by mvanalphen** [comment]
🎉 I think this is pretty much ready in that case. Thanks again for testing it!

**Comment by Kowlin** [comment]
Will take a look at this tomorrow or so.

**Comment by mvanalphen** [comment]
Bump!

**Comment by TheWyn** [comment]
Looking good? @Kowlin

**Comment by Twentysix26** [comment]
When a song is playing and a new invalid url gets queued it will provide no output in chat.
```
Traceback (most recent call last):
  File "C:\*\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\*\cogs\audio.py", line 2191, in queue_manager
    clean_url = self._clean_url(url)
UnboundLocalError: local variable 'url' referenced before assignment
```

**Comment by mvanalphen** [comment]
Good catch. Fixed in the last commit.

**Comment by Twentysix26** [comment]
Seems good to go

**Review by Twentysix26 — APPROVED** [review]

**Review by Kowlin — APPROVED** [review]
Sorry, I know. I promised I would review this earlier. got caught up in some stuff, Anyhow!

I wasn't able to find any issues my self on this PR.

**Review by tekulvw — APPROVED** [review]

**Pull request merged**
