### PR TITLE
[Mod] Correctly log and store the previous (nick)name

### PR DESCRIPTION
**Pull request by Kowlin**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

So it appears we had this bug in Red for the past 3 years, where we didn't store the correct past (nick)name. Lets fix that.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
While it was added to V3 3 years ago, it's historically accurate with the 4 year old V2 behavior. Hurray for consistency? <https://github.com/Cog-Creators/Red-DiscordBot/commit/8b52bd56af7904afef7ad49b3392d7dc1cc7bcd3>

**Review by mikeshardmind — CHANGES_REQUESTED** [review]
To avoid not having as full a record as is possible if someone leaves, name changes, then rejoins, this should probably store both the before and after (with nick still checking against None) rather than just one or the other.

**Review by Jackenmen — COMMENTED** [review]
@Kowlin Works as intended, do you want to add logging of "after" (nick)names here as well?

**Comment by Kowlin** [comment]
Not at the moment, no.

**Review by Jackenmen — APPROVED** [review]

**Pull request merged**
