### PR TITLE
Fix for #438

### PR DESCRIPTION
**Pull request by tekulvw**

### CODE REVIEW

**Comment by Chovin** [comment]
this doesn't account for \\* and such.

**Comment by Chovin** [comment]
shortening by more outside is a quick and dirty fix but what happens when you use pagify on a large document?
now page_length < 0

**Comment by tekulvw** [comment]
I agree with defaulting delims but I see no reason for the catchall positional arg

**Comment by Twentysix26** [comment]
To avoid monstrosities like
`pagify(text, ["\n"], False, 8, 2000)`
What is that bool? What are those 2 last ints? You know it because you made this function yourself but at  first glance it's unclear to say the least.  It forces cleaner code.  
I'd also appreciate if you don't undo changes that I made without first discussing it, thank you very much.

**Comment by Twentysix26** [comment]
Merging. We'll fix what @Chovin reported in a second time

**Pull request merged**
