### PR TITLE
[Trivia] AudioTrivia

### PR DESCRIPTION
**Pull request by bobloy**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes

Add the ability to run audio-based trivia games.

### CODE REVIEW

**Comment by bobloy** [comment]
This PR needs permissions from @pabloleban to merge the anime list (License change)

**Comment by Jackenmen** [comment]
In that case, you should amend the commits so that his trivia list is (co-)authored by him.

**Comment by Jackenmen** [comment]
...after getting his permission to include it in this project of course.

**Review by pabloleban — APPROVED** [review]

**Comment by bobloy** [comment]
Closed based on conversations in the discord server. Waiting for some core audio improvements before resubmitting.

**Pull request closed without merging**
