### PR TITLE
[Core V3] Add setup instructions for external data and cog paths

### PR DESCRIPTION
**Pull request by tekulvw**
One more step towards pip installability.

### New Features
- Refactored initial setup
- Add components to initial setup to ask for data path and cog install path for Downloader
- Setup creates a `config.json` file that's now required to start the bot as it contains the data path

### What does this mean?
*We're no longer depended on current working directory.*

### How do I use this?
1. Update your requirements: `pip install -U -r requirements.txt`
2. `python /path/to/main.py`
3. The bot will then generate a file named `config.json` to the current working directory.
4. From now on run the bot using `python /path/to/main.py /path/to/config.json`

### Dependencies
- ~~#853~~
- #879

### CODE REVIEW

**Comment by mikeshardmind** [comment]
It works, but it shouldn't be asking me for a cog data path on each launch, that should be detected as having already been set.

**Comment by tekulvw** [comment]
It doesn't ask you for a data path every launch if you provide the config
file it generates when you run the bot. E.g. `python main.py config.json`

**Comment by tekulvw** [comment]
Added extra instructions to this PR.

**Comment by mikeshardmind** [comment]
Right, but if that config file exists in Red's directory, it should be considered the default config file unless a different one is specified.

**Comment by tekulvw** [comment]
The point of this PR is to get stuff out of the bot folder. I'm not going to add support for that, just use the command line argument.

**Comment by tekulvw** [comment]
Right idea, wrong implementation. New stuff will be coming soon in different PRs.

**Pull request closed without merging**
