### PR TITLE
[Mod] Warning system

### PR DESCRIPTION
**Pull request by calebj**
See #488

### CODE REVIEW

**Comment by NekoTony** [comment]
Welp, i was gonna try to make this but i never really knew how to make a PR but ty for doing it for me. <3

**Comment by Nerdietony** [comment]
So, by "needs testing" does that mean someone test it or twentysix red? It works fine for me...

**Comment by Nerdietony** [comment]
i'm gonna bump this

**Comment by NekoTony** [comment]
Works fine for me...

**Comment by NekoTony** [comment]
meep

**Comment by tekulvw** [comment]
Closing due to staleness, v2 feature freeze...just dev it for v3 caleb

**Pull request closed without merging**
