### PR TITLE
MongoDB docs

### PR DESCRIPTION
**Pull request by laggron42**
So here is what @tekulvw asked me to do, a tutorial for MongoDB installation. It includes Mac, Windows and Ubuntu. Make sure to check if it's ok (line 3. please). 
And I tried to show all the commits I made (was working on the wrong branch) but I didn't achieved it.

### CODE REVIEW

**Comment by laggron42** [comment]
I'm adding Arch, Debian and Raspbian tutorials too

**Review by tekulvw — CHANGES_REQUESTED** [review]
This needs to go in the `docs/` folder in the bot repo

**Comment by laggron42** [comment]
what happened?

**Comment by laggron42** [comment]
Don't understand what's the actual problem

**Review by Kowlin — CHANGES_REQUESTED** [review]
Nope. This is better if we just close this outright, Somehow you managed to merge ``v2`` into ``v3``

**Comment by Twentysix26** [comment]
You somehow shoved v2 into v3 in the last commit. You should be able to reverse to the last good commit and force push. The changes will be reflected into this PR.

**Comment by laggron42** [comment]
I think it's better to open a new PR

**Pull request closed without merging**
