### PR TITLE
Drop the launcher

### PR DESCRIPTION
**Pull request by palmtree5**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Removal

### Description of the changes

Removes the launcher as merging #2726 adds autostart documentation for Mac and Windows.

### CODE REVIEW

**Review by mikeshardmind — DISMISSED** [review]
This is ready, pending the auto-restart docs finalization.

**Comment by Jackenmen** [comment]
This PR doesn't remove mention of launcher from docs.

**Comment by Jackenmen** [comment]
Ignore my previous comment, mentions of launcher were removed from docs in some other PR already.

**Comment by mikeshardmind** [comment]
This is being deferred (for now). The plan is still removal, but in the short term, we will be stripping down the launcher to *only* handle the auto restart concerns.

**Comment by Drapersniper** [comment]
I would like to see this done for 3.4.0 if possible, I'm aware that is blocked by the docs PR. but it would be nice to prioratize.

**Comment by Kowlin** [comment]
Superseded by #5999.

**Pull request closed without merging**
