### PR TITLE
Cleanup reactions

### PR DESCRIPTION
**Pull request by phenom4n4n**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
Adds a `[p]cleanup reactions <number>` command which searches the messages provided and clears reactions from them if there are any.

### CODE REVIEW

**Review by TurnrDev — COMMENTED** [review]
Surely `str.format()` is better than `%-formatting`? Certainly a lot more readable.

**Comment by Zephyrkul** [comment]
Python's logging module uses %-formatting.

**Comment by phenom4n4n** [comment]
^ this logging is based off how the rest of the cog logs.

**Comment by TurnrDev** [comment]
> Python's logging module uses %-formatting.

> ^ this logging is based off how the rest of the cog logs.

Oh, ignore me then :+1:

**Comment by Vexed01** [comment]
`%-formatting` is what `cleanup_spam` uses. The rest of the cleanup cog sets a `reason` var with `str.format()`, then does `log.info(reason)`.

**Comment by Drapersniper** [comment]
Okay so, this is gonna be extremely API intensive... to the point you could start hitting the global ratelimits if you pass large numbers.

One solution is to enforce it to clear reaction only on the last 100 messages, this of course would severally restrict usability of this command.

**Comment by phenom4n4n** [comment]
Another solution may be to limit the number of messages searched in channel history to 300, and limit the number of messages that are actually cleared to 100. If it reaches than 100 messages, the loop will break. Then put a 5s channel cooldown on the command. 
These numbers are examples, I'm not sure which numbers are best for use in production.

**Comment by phenom4n4n** [comment]
New commit reflects the idea proposed here:
> Another solution may be to limit the number of messages searched in channel history to 300, and limit the number of messages that are actually cleared to 100. If it reaches than 100 messages, the loop will break. Then put a 5s channel cooldown on the command.

**Pull request closed without merging**
