### PR TITLE
do better with loop cleanup

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Description of the changes

It should reduce console noise during cleanup.

Should also fix the issues some people had on windows with a keyboard interrupt hanging rather than quiting.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
This isn't review ready. Some of this needs changing, and it's going to be used to cleanup the logic in main more.

**Comment by mikeshardmind** [comment]
This should be ready to go now.

**Comment by mikeshardmind** [comment]
Handling cleanup properly on windows requires something which was fixed in python3.8 ([bpo-23057](https://bugs.python.org/issue23057))

Since we have to update the deps here for this, we'll be doing it for all platforms to ensure feature availability is uniform across platforms

**Comment by mikeshardmind** [comment]
Current PR state disables our pylint check due to https://github.com/PyCQA/pylint/issues/3247

More internal discussion around this happening.

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
