### PR TITLE
Fix leaderboard error in DMs for global banks

### PR DESCRIPTION
**Pull request by phenom4n4n**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fixes `leaderboard` erroring in dms

### CODE REVIEW

**Review by Jackenmen — APPROVED** [review]
Looks good to me.

**Comment by Jackenmen** [comment]
Thanks for PRing!

**Comment by TurnrDev** [comment]
Ah, that was my fault. Sorry guys.

**Comment by Jackenmen** [comment]
No worries, bugs are a normal thing in development :)

**Pull request merged**
