### PR TITLE
irdumb's twitch set

### PR DESCRIPTION
**Pull request by ddday**
Author: irdumb
Adds !set stream, because why not ¯ _( ツ )_ /¯.
#242

### CODE REVIEW

**Comment by irdumbs** [comment]
oh, you know what?
people won't be able to use this unless they use the audio hotfix or multivoice pr
since we're telling them to use the old discord.py

**Comment by Kowlin** [comment]
Don't care :D near release anyhow.

**Comment by ddday** [comment]
_twiddles thumbs_

**Comment by ddday** [comment]
well we're no longer telling them to use the old discord.py sooo

**Comment by irdumbs** [comment]
boop bop a rebop a roobarb pie

**Comment by irdumbs** [comment]
see #300?

**Pull request closed without merging**
