### PR TITLE
Bump dependencies (this switches to HTML 5 writer in Sphinx)

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Dependency Update

### Description of the changes
This PR bumps all our dependencies to the latest versions.
Notably:
- Sphinx 2.4.4 -> 3.1.1
  - sphinx_rtd_theme 0.4.3 -> 0.5.0 - Sphinx 2.x and 3.x is now fully supported
    - this includes full support for HTML 5 writer which this PR switches our docs to use now
  - there are few goodies in Sphinx 3.x we could take use of, but this PR focuses on dependency update itself

### CODE REVIEW

**Comment by Jackenmen** [comment]
Yeah... I think I broke something with this judging by the postgres tests...

**Comment by Jackenmen** [comment]
We need to wait for `pytest-asyncio 0.13.0` release or back down on the `pytest-asyncio` bump. This is not a time-critical dependency update so I'm gonna wait, especially that it most likely will be released very soon™

**Comment by Jackenmen** [comment]
This is now ready for review.
Testing is mostly needed for Mac (more detailed information in PR description) and changes in how docs are rendered (some changes, like bigger font size in class/method documentation are expected, but anything that seems wrong is worth mentioning).

**Comment by aikaterna** [comment]
I'll help with getting the Mac stuff tested on a couple devices.

**Comment by aikaterna** [comment]
On a Mac that's never had Red installed:
I confirmed that it installed appdirs==1.4.4, but it placed a config.json in `~/Library/Application Support/Red-DiscordBot/config.json` when we were expecting `~/Library/Preferences/Red-DiscordBot/config.json` instead.

**Comment by Jackenmen** [comment]
After some additional debugging (thanks aika), I figured that I'm just dumb and I looked at wrong diff when checking the changes in appdirs 1.4.4 and it turns out that the change that would break us doesn't exist in that version (probably due to the reason that I needed to do this compatibility fix in the first place).

Thanks for the testing @aikaterna and helping me figure out that I'm just dumb 👍

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
