### PR TITLE
[Trivia] Updated and 1 new trivia

### PR DESCRIPTION
**Pull request by MiniJennJenn**
Updates: anime, entertainment typos, final fantasy, general
New: usstateabbreviations

### Type

- [x] Bugfix
- [x] Enhancement
- [ ] New feature

### CODE REVIEW

**Review by Twentysix26 — DISMISSED** [review]
The problem that was fixed in the previous PR is again in this one (pokemon list)

**Comment by MiniJennJenn** [comment]
Ah shit. I think I was supposed to attach ff not Pokemon to this PR. Thanks for catching it. I'll fix it when I get home.

**Comment by MiniJennJenn** [comment]
All fixed~

**Review by Tobotimus — APPROVED** [review]

**Review by tekulvw — APPROVED** [review]

**Review by Kowlin — APPROVED** [review]
Better late then never right?

**Pull request merged**
