### PR TITLE
[Docs] Autostart and restart on Windows

### PR DESCRIPTION
**Pull request by Limmek**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Added how to create a batch file that allows the bot to be restarted and it also checks if a windows scheduled task exist to start the bot on windows startup, if not it will create it.

### CODE REVIEW

**Comment by Drapersniper** [comment]
I'm personally not in favour of auto updates, updates should be something a owner takes action to ensure they have up to date requirements.

Yes it's more convenient, but convenience is not always better than explicitly

**Comment by Drapersniper** [comment]
Also not to mention, you shouldn't run red as an admin. Ever.

**Comment by Limmek** [comment]
I will change the update to be false  from the beginning and if the user want to have auto update he can just enable it.

That is true you should never do it but the bot will only run as admin if you right click and run it as admin.

**Comment by Drapersniper** [comment]
I mean it shouldn't be an option to start with it available in the docs I mean.

By having it there it means it's supported, supporting auto updates is problematic


Same applies to telling them to run as admin.

**Comment by Limmek** [comment]
Ohh i see,  i will make some changes!

**Comment by Limmek** [comment]
I removed auto update and task creation from the script and instead added how to sett up the task by command.

**Comment by Jackenmen** [comment]
Considering there is already one PR adding auto-restart (#2726) and that there's been no prior discussion on the approach taken here, I would like to mention that this PR might not get accepted if our team decides that we can't support this approach if for example there are some flaws in it.

Also for the next time, please file an issue or start a conversation on [Red server](https://discord.gg/red) for any new additions that have not been proposed already or, if you have alternative proposals to already requested additions, please propose them in already existing issue. It may save you from losing time on an addition that we may not be able to accept. Communication is key :)

**Comment by Kowlin** [comment]
Superseded by #5996.

**Pull request closed without merging**
