### PR TITLE
Bump discord.py to version 2.1.0

### PR DESCRIPTION
**Pull request by Kowlin**
### Description of the changes

For as far as I'm aware no additional changes are needed for this bump. However, would be a good idea to double check.

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Review by Jackenmen — CHANGES_REQUESTED** [review]
Should do a swap from `delete_message_days` to `delete_message_seconds` when `Guild.ban()`/`Member.ban()` is used (passed argument needs to be multiplied by `86400`) as the former is deprecated. Based on code search, this argument is only used in `redbot/cogs/mod/kickban.py` file.

---

We could also consider allowing people to specify other intervals in commands such as `[p]ban`, `[p]massban`, and `[p]tempban` though in the `[p]tempban` case it may make the parameter syntax more ambiguous due to temp ban duration and delete seconds allowing the same syntax (timedelta converter). Since it's not a very clear cut, I recommend that you make an issue for that where we can discuss it further.

**Comment by Kowlin** [comment]
Okay that was the thing that I absolutely glanced over and blanked out while reading the change log, whoops 😅

**Comment by Jackenmen** [comment]
To be fair, the changelog doesn't mention the deprecation anywhere :)

**Review by Jackenmen — APPROVED** [review]
Seems fine now, thanks for making the issue for tracking the new possibility for ban commands.

**Pull request merged**
