### PR TITLE
Use embed for user/server info

### PR DESCRIPTION
**Pull request by YeahImRose**
User color is the same as the user's role
Server color is completely random
How it looks

### CODE REVIEW

**Comment by Kowlin** [comment]
Looks good to me, I have one concern though. Only bots can make the used of Rich Embedding, is there a fallback for non bot accounts?

**Comment by YeahImRose** [comment]
There's no fall back but I can add it in easily

**Comment by YeahImRose** [comment]
Issue
~~Please do not merge this until I have sorted an issue with dates.~~ Thanks @Eslyium for pointing this out c:

EDIT: Fixed now

**Comment by Eslyium** [comment]
Works fine. 👍

**Comment by skeith** [comment]
Roles on userinfo should be sorted descending

**Comment by YeahImRose** [comment]
I was debating whether or not to add some form of sorting to roles, wasn't sure if it should be alphabetical or by hierarchy

**Comment by skeith** [comment]
Probably better by hierarchy just like profile card

**Comment by YeahImRose** [comment]
Good point

**Comment by Twentysix26** [comment]
Er. Selfbots can send rich embeds, no need for fallbacks.

**Pull request merged**
