### PR TITLE
Make use of dpy commands.Range on set status commands

### PR DESCRIPTION
**Pull request by PredaaA**
### Description of the changes

This PR make uses `commands.Range` for maximum length of `[p]set status` commands.

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Review by Jackenmen — CHANGES_REQUESTED** [review]
You should remove the length checks from the method bodies.

**Comment by Jackenmen** [comment]
Please update to latest V3/dev and apply the changes to `[p]set status custom` as well, thanks!

**Comment by PredaaA** [comment]
> Please update to latest V3/dev and apply the changes to `[p]set status custom` as well, thanks!

Done

**Review by Jackenmen — APPROVED** [review]
Thanks!

**Pull request merged**
