### PR TITLE
[Docs] randomize_color now has its own docstring

### LINKED ISSUE #3468: [Docs] Typo in Embed Helpers
# Other bugs

https://red-discordbot.readthedocs.io/en/stable/framework_utils.html#module-redbot.core.utils.embed

`redbot.core.utils.embed.randomize_color` says there is an alias called ``randomize_color`` though it should say ``randomize_colour``.

### PR DESCRIPTION
**Pull request by Dav-Git**
### Type

- [X] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
This closes #3468

### CODE REVIEW

**Comment by Dav-Git** [comment]
Well... some new checks showed up

**Comment by Jackenmen** [comment]
You need to update PR for them to trigger, something like merging/rebasing on top of V3/develop and then pushing would work.
Or you could make an empty commit...
```
git commit --allow-empty -m "Trigger CI"
```

A minor inconvenience for old PRs that gives us a lot better (faster) checks.

**Comment by Jackenmen** [comment]
I feel like it might be better to just remove `randomize_color` from docs and only leave `randomize_colour` (and consequently the docstring with alias shows only the correct function since the other won't be shown separately in docs).
To be clear, that's just my opinion.

**Comment by Dav-Git** [comment]
Something I actually didn't think about which makes a lot of sense however. I agree. Will update the pr to this tomorrow

**Comment by Dav-Git** [comment]
Actually, how would I go about removing it from the docs? I've tried changing 
```
.. automodule:: redbot.core.utils.embed
    :members:
```
 to
```
.. automodule:: redbot.core.utils.embed.randomize_colour
    :members:
```
In framework_utils.rst

**Comment by Jackenmen** [comment]
@Dav-Git IMO, the best way to change would be changing from:
```rst
.. automodule:: redbot.core.utils.embed
    :members:
```
to
```rst
.. automodule:: redbot.core.utils.embed
    :members:
    :exclude-members: randomize_color
```
This way, if someone adds a new util to `redbot.core.utils.embed`, they won't have to modify the rst file to have it added to documentation.

**Review by Jackenmen — APPROVED** [review]
LGTM

**Pull request merged**
