### PR TITLE
Audio Fixes

### LINKED ISSUE #4489: Audio bug
Fix the bug

### LINKED ISSUE #4491: Help of `[p]audioset globalapi toggle` is wrong
# Command bugs

#### Command name

`[p]help audioset globalapi toggle`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

I expected default to be OFF according to help.

#### What actually happened?

Default is ON according to help.
image

#### How can we reproduce this issue?

`[p]help audioset globalapi toggle`

### LINKED ISSUE #4495: Audio doesn't work with i18n
# Other bugs

#### What were you trying to do?

Use Audio while having a non-English locale set.

#### What were you expecting to happen?

Strings to be translated (if the translation is available of course, but it is in this case).

#### What actually happened?

Strings are not translated.

#### How can we reproduce this issue?

1. Set the bot to some locale with big coverage, e.g. French, German, Polish, Russian
2. Try using few commands in Audio.
3. See that strings aren't getting translated.

---

The reason for this is the way `Translator` object is created in Audio cog vs how the po files are actually structured. Audio creates a single `Translator` object at `redbot.core.audio.core.cog_utils` that refers to `po` files in `redbot/core/audio/locales` folder. Meanwhile, the actual translation can exist in any of:
```
redbot/cogs/audio/locales
redbot/cogs/audio/apis/locales
redbot/cogs/audio/core/locales
redbot/cogs/audio/core/commands/locales
redbot/cogs/audio/core/events/locales
redbot/cogs/audio/core/tasks/locales
redbot/cogs/audio/core/utilities/locales
```
depending on where the string actually resides. The solution can for example be creating a `Translator` object in each file that needs translations (as do other cogs) rather than rely on a single one, since in such case its path is inaccurate.

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

resolves #4491
Typing indicators on playlist commands.
Fix a bs edge case that i can't reproduce (in theory) as now I ensure the player lock is always released upon an exception/error
Fix yet another bs edge case, where setting a new token doesnt update audio properly for the global api.
resolves #4495

Theoretically this resolves #4489 as I cannot reproduce it even with the exact steps the one user who hit this said they done.

### CODE REVIEW

**Comment by Jackenmen** [comment]
The solution used for #4495 is correct, I did quick testing of it and it worked as intended. I haven't looked if each file with the usage of `_()` uses its own Translator object now, but considering there are no ImportErrors, I can suspect it's all good.

**Comment by Drapersniper** [comment]
Commit sucks ... 
image

**Review by aikaterna — COMMENTED** [review]
This is a provisional approval for everything in this PR. There may be some additional error handling added after this comment, which is why this isn't a true approval.

**Comment by Drapersniper** [comment]
Updated Errors as discussed with Aika.
image

**Review by aikaterna — APPROVED** [review]

**Pull request merged**
