### PR TITLE
Allow to hide moderator from warnings sent to the users + warn channel fix

### PR DESCRIPTION
**Pull request by Dav-Git**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
On some discords, backlash on the moderator who warned a user is a big concern. Therefore I implemented a setting that would turn off the sending of the username of the moderator if sending DMs is enabled.

### CODE REVIEW

**Comment by Kowlin** [comment]
I'd personally be of favor on the moderator's side and making ``show_mod`` be False by default, and I'd like some of the thoughts on this.

**Comment by Dav-Git** [comment]
My thought on that was transparency and have people be able to turn it off once it becomes an issue

**Comment by Dav-Git** [comment]
I went with the kowlin option so it's now default false

**Comment by Jackenmen** [comment]
> I'd personally be of favor on the moderator's side and making `show_mod` be False by default, and I'd like some of the thoughts on this.

I agree with this, even if it's changing current default. Usually it's not important who warned the warned user and it can end up in unwanted backlash so this seems as more reasonable default.

This change might be worth mentioning at the start of changelog section so that people who do want moderators to be shown, can change this after updating.

@Dav-Git this PR is now conflicting, could you handle the conflict resolution?

**Comment by Dav-Git** [comment]
Yep, will do later today/tomorrow.

**Comment by Dav-Git** [comment]
Hold off on merging this, I found an error I will need to test first

**Comment by Jackenmen** [comment]
There's another mention of a moderator at L417

**Comment by Dav-Git** [comment]
I also included a "fix" to the warnchannel... either I broke it or it was broken previosly. i'm not sure at this point.

**Comment by Dav-Git** [comment]
Ah, forgot to include in last comment, but from my testing this works(TM)

**Review by Jackenmen — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
