### PR TITLE
"Imgur" command changes

### PR DESCRIPTION
**Pull request by Jeddunk**
* Allow greater time window (than "day") if there isn't enough content (at least 3 images)
* Output every image with its title in a seperate message
* GIFV support

### CODE REVIEW

**Comment by Jeddunk** [comment]
Also, with these changes it might be easier to expand upon the command if needed (e.g. output more or less content depending on user input, metadata, nsfw filtering,...)

**Comment by palmtree5** [comment]
Looks pretty good to me

**Comment by Kowlin** [comment]
Seems to be broken when I tried it out, can anyone confirm that its broken or working?

**Comment by palmtree5** [comment]
Gimme a bit and I'll test it

**Comment by palmtree5** [comment]
Or instead of testing, I could be grossed out by the old tech in the imgur command and wind up rewriting the imgur command to use subcommands (see #500) :p

**Comment by Twentysix26** [comment]
Closing in favor of https://github.com/Twentysix26/Red-DiscordBot/pull/500

**Pull request closed without merging**
