### PR TITLE
Fixes #1931 (Permissions not able to override subcommands)

### LINKED ISSUE #1931: [V3] Permissions nested group issues.
Well, I hate finding I didn't properly account for this, but at least it was designed to fail securely.

The allow override for a command in a group does not implicitly grant an allowance of that group. This is a problem with how the permission model is advertised.

2 (ED: 1) possible routes for fixing:

1. Only commands can have `admin_or_permissions` style checks, not groups. (Ed: this breaks invokable group checks...)
2. Modify check handling done by the bot to account for our permission model.

Things which will not satisfactorily fix this:

1. Setting a subcommand implicitly allows the group.
  This is not okay, as we want the granularity, without needing to define each command individually, and would be insecure if any commands were added to the group after configuration.

2. Abusing reinvoke:
  This leaves the help-formatter in the dust (coincidentally, tracking weirdness on #1899 down is part of how I found this)

3. Moving checks from groups to their subcommands during add_cog:

    This breaks checks on invokable groups.

Additional notes:

Because of the ordering and current priority, the worst impact of this currently is blocking commands to someone you intended to allow them to. This will never incur the opposite.

### PR DESCRIPTION
**Pull request by mikeshardmind**
Fixes #1931 (Permissions not able to override subcommands)
Supercedes: #1961

Additionally, #1899 needs a new implementation and inclusion for the help formatter to correctly hide things.

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

This adds an attribute to context allowing persistent storage of a fully consumed view object. This is needed because discord.py does not consume the view entirely at the point in time checks are run, and out model relies on knowing the command the user wants to run, not just each group, subgroup, and command in question individually.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
After more testing, this avenue for fixing this breaks the helpformatter behavior of hiding unavailable commands, indicating the proposed changes in #1899 will need to be finished and included for this to be a valid fix.

**Comment by mikeshardmind** [comment]
This still works as intended, but after discussion with @Tobotimus this should likely be handled in a redesign of the underlying mechanisms while leaving the user-facing interfaces as similar as possible. Leaving open for such a decision to be made, but will not continue with this myself from here.

**Comment by Tobotimus** [comment]
Indeed, unfortunately I think a redesign is needed. I'm going to leave this open in case that doesn't eventuate, however. This could act as a hotfix, if the help formatter was not affected.

**Comment by mikeshardmind** [comment]
@Tobotimus Have you had a chance to come up with an alternative method, or should I look deeper into the current ways this breaks the help formatter, and how to avoid that?

**Comment by mikeshardmind** [comment]
Solved alternatively with #2149

**Pull request closed without merging**
