### PR TITLE
[V3] Set token command

### PR DESCRIPTION
**Pull request by laggron42**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

The `[p]set token` command from V2 is missing, and we are obligated to manually edit the `settings.json` file. That PR adds this command. This still needs testing (as I'm not home to do it) but, following the code from this file, this should work. I made it the same way as you made your commands in that file.

### CODE REVIEW

**Comment by tekulvw** [comment]
This should be DM only and the `if` check is unnecessary, the token argument isn't optional.

**Comment by laggron42** [comment]
when I say I did it the same way you made your commands...
```Py
    @_set.command(aliases=["prefixes"])
    @checks.is_owner()
    async def prefix(self, ctx, *prefixes):
        """Sets Red's global prefix(es)"""
        if not prefixes:
            await ctx.send_help()
            return
        prefixes = sorted(prefixes, reverse=True)
        await ctx.bot.db.prefix.set(prefixes)
        await ctx.send(_("Prefix set."))
```
Anyway, gonna edit this!

**Comment by tekulvw** [comment]
If a user tries to use this command outside of DM the bot should attempt to delete the message and tell the user that they should change their token (since they just released it publicly) before telling them to re-run the command in DM.

**Review by tekulvw — APPROVED** [review]

**Comment by laggron42** [comment]
Sorry for not updating, I got to go

**Pull request merged**
