### PR TITLE
MongoDB installation tutorial

### PR DESCRIPTION
**Pull request by laggron42**
After I had nuked my PR, I'm just gonna create a new one (all of that for just a doc, but at least I learn)

### CODE REVIEW

**Comment by Twentysix26** [comment]
Needs to be in the `/docs/` folder *cough*

**Comment by palmtree5** [comment]
I threw in the content of the file as it was in #929 as what you had in there before my commit was incomplete

**Review by palmtree5 — DISMISSED** [review]

**Review by laggron42 — COMMENTED** [review]
I don't know how you did this but I can finally stop my recovery programm (got 2 high level temperature alert) Thanks so much

**Comment by Twentysix26** [comment]
It's just me or it's a bit weird to have installation instructions for a third party software? There's nothing in these instructions that is Red specific, it's basically what you can already find in [MongoDB's docs](https://docs.mongodb.com/manual/administration/install-community/)

**Comment by laggron42** [comment]
@Twentysix26 say that to will, it's him who asked me to do that (and also promised me a Contributor role *cough*)

**Comment by tekulvw** [comment]
What I asked was for installation instructions for V3. I also agree this instruction is unnecessary and incomplete.

**Pull request closed without merging**
