### PR TITLE
I promise I'm not doing this on purpose

### LINKED ISSUE #3918: [Audio] `[p]skip` when paused briefly plays
# Command bugs

#### Command name

`[p]skip` (when invoked after the music is `[p]pause`ed)

#### What cog is this command from?

Audio

#### What were you expecting to happen?

After the music has been paused, I was expecting `[p]skip` to start playing the next track immediately.

#### What actually happened?

After the music had been paused, the paused track restarted playing briefly before the next track started.

#### How can we reproduce this issue?

1. `[p]load audio`
2. Play at least two tracks - this could be a playlist or two individual tracks.
3. Run `[p]pause`
4. Run `[p]skip`

To clarify, _the music un-pausing after `[p]skip` is not the issue_, the issue is that the paused track plays for a second or so before the next track starts.

Make sure you have sound on to hear this: https://videobin.org/+19n1/1fwt.ogg (yes I queued the same song twice)

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
||or am I||

This one depends on https://github.com/Cog-Creators/Red-Lavalink/pull/85

LL#85 and this will close #3918

### CODE REVIEW

**Comment by Drapersniper** [comment]
So On this one I done Level 9000 Dark voodoo magic,  auto deafen is delegated to RLL on initial WS OPs, cutting the calls here in half.

I also added some special WS handling, you know all those times discord fucks you up the ass, then  audio stops playing, or player disconnect,  or some weird shit happens? Yeah so thats all gone, I've added handling to audio to recover from a voice ws closing during playback, this often happens on long playback sessions, but can also happen for example when your shard reconnects.

All in all this is the best Audio PR in 2 days, so merge pliz it wont break :tm:.

**Comment by Drapersniper** [comment]
Summary of Changess:

User Facing: 
 - Audio should no longer stay stuck on a VC with nothing playing (Fixed an issue where the VC WS wasnt recconected upon dying)
 - If a user has the Global API enabled, they will now be able to continue searching for tracks even though YouTube API key runs out (Note a warning about the key being exausted will still be shown if the playlist they are enqueuing doesnt exist in the global API)
 - If there is a shutdown, audio cog reload, `[p]audiosetr restart` or anything of the sort during an auto play section, the player will smartly restore the rection properly.

Backend changes:
 - Improved the auto deafen so its not called directly from audio for the most part.
 - RLL bump to 0.8.0
 - Improved logging around WS disconnect issues

This has been actively enabled over the last few days, for a handful of users without any issues, in fact we have seen a major improved in that if a shard reconnects player will no longer completely die now.

**Comment by fixator10** [comment]
emptydisconnect seems to be doesnt clearing autoplay status
img
Context/talk:
https://discord.com/channels/133049272517001216/133251234164375552/776934030582612039
https://discord.com/channels/133049272517001216/133251234164375552/777290034075140127

**Comment by PredaaA** [comment]
- On cog reload/after restarting, some players that were killed some time before (I'm talking about a few days before) are restored.
- Restarting lavalink, when there is some players (~40) the bot is getting global ratelimited for a little bit (like 5secs), I'm guessing it's because the cog is sending the error message to *every* channel linked to the died player.
Then once lavalink is back, some players aren't connecting back, even though they have a queue, and that they can access, it's usually around 10 players that aren't restored.
Considering there is also an error getting spammed for a bit after lavalink being ready which is:
```py
[2021-01-23 14:45:20] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "/cogs/CogManager/cogs/audio/core/events/lavalink.py", line 59, in lavalink_event_handler
    await self._websocket_closed_handler(
  File "/cogs/CogManager/cogs/audio/core/events/lavalink.py", line 381, in _websocket_closed_handler
    await player.resume(player.current, start=player.position)
  File "/venv/lib/python3.8/site-packages/lavalink/player_manager.py", line 326, in resume
    await self.node.play(self.channel.guild.id, track, start=start, replace=replace)
  File "/venv/lib/python3.8/site-packages/lavalink/node.py", line 504, in play
    await self.no_stop_play(guild_id=guild_id, track=track, replace=replace, start=start)
  File "/venv/lib/python3.8/site-packages/lavalink/node.py", line 496, in no_stop_play
    "track": track.track_identifier,
AttributeError: 'NoneType' object has no attribute 'track_identifier'
```

**Comment by PredaaA** [comment]
- Disconnecting manually (right click then "Disconnect") will makes the bot reconnect itself to the channel, and may also disconnect itself after a few seconds, that in loop for a few times. (it's happening wether there's something in queue or not)
I'm guessing it's related to my previous comment things.

**Comment by aikaterna** [comment]
Localtrack names/paths need to be escaped.

**Comment by fixator10** [comment]
Thats happened, probably due to bot leave a guild at around that time.

```py
[2021-02-27 12:31:38] [ERROR] red.cogs.Audio.task.callback: Task-17809 raised an Exception
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/cogs/audio/core/tasks/player.py", line 50, in player_automated_timer
    if sid in stop_times and await self.config.guild(server_obj).emptydc_enabled():
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/core/config.py", line 1060, in guild
    return self._get_base_group(self.GUILD, str(guild.id))
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Drapersniper** [comment]
### Fixed on most recent comments

- https://github.com/Cog-Creators/Red-DiscordBot/pull/4565#issuecomment-787449128
- https://github.com/Cog-Creators/Red-DiscordBot/pull/4565#issuecomment-773989824 (Hopefully let me know if you are still seeing this after you update)
- https://github.com/Cog-Creators/Red-DiscordBot/pull/4565#issuecomment-786851727 (Think i covered all cases let me know if i missed any)
- Fixed the crash in https://github.com/Cog-Creators/Red-DiscordBot/pull/4565#issuecomment-766278288
- https://github.com/Cog-Creators/Red-DiscordBot/pull/4565#issuecomment-727270556


- On cog reload/after restarting, some players that were killed some time before (I'm talking about a few days before) are restored. This should be fixed ... if you still see it please let me know, if possible also saying exactly how the player was disconnected will help loads here)

### Not done yet
- Restarting lavalink, when there is some players (~40) the bot is getting global ratelimited for a little bit (like 5secs), I'm guessing it's because the cog is sending the error message to every channel linked to the died player. Then once lavalink is back, some players aren't connecting back, even though they have a queue, and that they can access, it's usually around 10 players that aren't restored.
  - Havent handled this yet ... we have 2 realistic options
    - 1. Slow down the whole restore process which can make bots with loads of players take quite a while to resume playback.
    - Get rid of the "auto play started" message, but my concern here is new users being caught off guard by this behaviour (Bot joining a VC/start to play songs without any comms, yes even thought it takes a user with perms to enable the behaviour)


### Known issues
- Sometimes after a cog reload the bot will not start playing (when autoplay is enabled) ... if you can provide me with debug logs it will help me debugging this massively
- Sometimes the when you start playing something it will fill stuttery, pausing and resuming for less than a second, this is linked to the resume logic but debug logs would be appreciated. (I believe I have fixed this ... but not confident enough to say I have until more people try to use this)
- I seen the bot leave the VC by itself but the player remained alive thinking it was playing something, cant reproduce if you do with debug logs please give them to me here as I cant debug this without them.

**Comment by fixator10** [comment]
<https://sentry.io/share/issue/f2601b625da14367b4eaf386d66f8f0d/>
```py
[2021-03-01 01:57:29] [INFO] red: Connected to Discord. Getting ready...
[2021-03-01 01:57:40] [INFO] red.cogs.Audio.cog.Utilities.playlists: Curated playlist has been updated.
[2021-03-01 01:57:40] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/cogs/audio/core/events/lavalink.py", line 56, in lavalink_event_handler
    if event_type == lavalink.LavalinkEvents.FORCED_DISCONNECT:
  File "/usr/lib/python3.8/enum.py", line 346, in __getattr__
    raise AttributeError(name) from None
AttributeError: FORCED_DISCONNECT
```

**Comment by Drapersniper** [comment]
> https://sentry.io/share/issue/f2601b625da14367b4eaf386d66f8f0d/
> 
> ```python
> [2021-03-01 01:57:29] [INFO] red: Connected to Discord. Getting ready...
> [2021-03-01 01:57:40] [INFO] red.cogs.Audio.cog.Utilities.playlists: Curated playlist has been updated.
> [2021-03-01 01:57:40] [CRITICAL] red.main: Caught unhandled exception in task:
> Traceback (most recent call last):
>   File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/cogs/audio/core/events/lavalink.py", line 56, in lavalink_event_handler
>     if event_type == lavalink.LavalinkEvents.FORCED_DISCONNECT:
>   File "/usr/lib/python3.8/enum.py", line 346, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: FORCED_DISCONNECT
> ```

You didn't force reinstall to get latest version of the RLL PR

**Comment by Kowlin** [comment]
CC: @Drapersniper

From #Advanced-testing on 1st April ~11PM

> https://canary.discord.com/channels/133049272517001216/171665724262055936/827297824122208267
> image

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
