### PR TITLE
Add aiohttp speedups to Red

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### CODE REVIEW

**Comment by Stonedestroyer** [comment]
Worked on python 3.7 on pi 1b, gonna try python 3.8 and report back.

**Comment by fixator10** [comment]
Works for me on `Python 3.8.5 (64bit) | Ubuntu 18.04`
Also on `3.8.6 (64bit) | Arch Linux`

**Comment by ltzmax** [comment]
Works for me as well, `python 3.8.6 64bit ubuntu 18.04.`

**Comment by Stonedestroyer** [comment]
Also works on Raspberry Pi 1B, Buster, 3.8.5. I think maybe we should test Alpine and musl related OSes.

**Comment by kablekompany** [comment]
Smoof as butta on py38 Ubuntu 18.04x64

**Pull request closed without merging**
