### PR TITLE
Add `quote()` function to chat formatting utilities

### PR DESCRIPTION
**Pull request by Zephyrkul**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes
Note that, unlike other methods in this module, this method does *not* escape formatting by default at current.

### CODE REVIEW

**Comment by Jackenmen** [comment]
Is there much reason to add option that escapes markdown here? In methods like `underline()`, this is needed so that the underlined text is underlined exactly as is. This problem doesn't exist for quoting as far as I know, so I'm interested to know, if there's other reason you decided to include it here.

**Comment by Zephyrkul** [comment]
Solely for the reason that it's present in other methods, which escape *all* formatting by default.

**Comment by Jackenmen** [comment]
I think it can be removed if that's the only reason then. It fits well with the `box()` method that also doesn't offer the option to escape formatting.

**Review by Jackenmen — APPROVED** [review]
LGTM, thanks for PRing.

**Pull request merged**
