### PR TITLE
[V3] Remove audio relative path for rare error

### PR DESCRIPTION
**Pull request by bobloy**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Removed relative path in audio
Helps clarity and a rare audio error

### CODE REVIEW

**Comment by mikeshardmind** [comment]
~~snip~~ Was being dumb

**Comment by tekulvw** [comment]
Neither of the two imports I'm seeing here will *ever* work. First, @bobloy, there is no top level package `audio`. Python package resolution does not work that way. Also @mikeshardmind there is no `redbot.audio` package so I'm not really sure what your comment proves?

**Comment by tekulvw** [comment]
What even is the issue that this PR is attempting to solve?

**Comment by mikeshardmind** [comment]
@tekulvw my mistake, I had intended for that to be `import redbot.cogs.audio.manager` , even so we've had one person with an issue (in #v3-support channel), and I'm not convinced (at all) that this PR would (could, or should work here too) fix their issue.

**Comment by bobloy** [comment]
Having this user try `import redbot.cogs.audio.manager` did succeed FYI

**Comment by bobloy** [comment]
Edited import scheme, see commit

**Comment by bobloy** [comment]
Root error was not identified, gonna close for further debugging

**Pull request closed without merging**
