### PR TITLE
[Audio] Rework event_handler to handle unhandled errors

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
As per title ... no more attribute errors

### CODE REVIEW

**Comment by mikeshardmind** [comment]
Needs conflict resolution

**Comment by Drapersniper** [comment]
conflicts resolved

**Comment by Drapersniper** [comment]
Do not merge this one ... Merge #3205

**Comment by Drapersniper** [comment]
Will setup a CPR for all of this so itsd easier to follow ... less likely to fuck up)

**Pull request closed without merging**
