### PR TITLE
Audio - Replay queued history by day

### PR DESCRIPTION
**Pull request by Fr6jDJF**
- Allows mods to manage/export replays as general playlist.
- General users may start replays.
- Auto cleanup old unused replays

### CODE REVIEW

**Comment by tekulvw** [comment]
I realize this has barely even been looked at but it's an interesting idea. If someone (*cough* @Kowlin *cough*) is available to test this I see no reason not to merge it in. In the meantime, can you rebase?

**Comment by Twentysix26** [comment]
Closing for impending rewrite.

**Comment by Drapersniper** [comment]
@Canule Im looking into this for Red 3.2 audio update, would you mind if I use parts of this PR for its logic?

**Comment by Fr6jDJF** [comment]
That is fine @Drapersniper

**Pull request closed without merging**
