### PR TITLE
Update pokemon.txt

### PR DESCRIPTION
**Pull request by violetnyte**
### Type

- [x ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Removed line 309 (Question: Who is the only Pokémon that is a Poison and Dragon type?`Dragalge) -- no longer accurate as of Gen VII USUM

### CODE REVIEW

**Comment by MiniJennJenn** [comment]
Ok that's fair to remove that question. But you also randomly deleted the word Poison in line 210.

**Comment by violetnyte** [comment]
Oops! Overzealous use of ctrl+f, sorry about that. I hope I fixed it correctly now

**Comment by MiniJennJenn** [comment]
np, This has my stamp of a approval

**Comment by Twentysix26** [comment]
Added in #1268

**Pull request closed without merging**
