### PR TITLE
[Docs] Link to Getting started guide at the end of installation guides

### LINKED ISSUE #3025: [Docs] Installation guides should link to Getting started guide
Add link to Getting started guide at the end of installation guides for Windows and Linux/Mac.
I think it makes sense to add it there so that they will know what they can do with the bot after installation.

// Edited for clarity

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Resolves #3025

### CODE REVIEW

**Comment by Vexed01** [comment]
This is a duplicate of #3027, however, this is implemented better as it will update to stable without input and it uses the tip box. I feel #3027 should be closed in favour of this.
Jus' saying, I obviously have no jurisdiction to close the other PR.
Needs a changelog entry 😉.

**Comment by Jackenmen** [comment]
It's not duplicate of #3027, they address 2 different things :p

**Comment by Vexed01** [comment]
Well they both link to the getting started guide, however now you made me read that they are different as the other one is in bot setup 🤦‍♂
_slowly walks away_

**Review by laggron42 — CHANGES_REQUESTED** [review]
You should actually reference the guide instead of using wrong rST formatting.
```diff
- If it's the first time you're using Red, you should check our `getting-started` guide
+ If it's the first time you're using Red, you should check our :ref:`getting-started` guide
```
See this for more info about references: https://www.sphinx-doc.org/en/1.5/markup/inline.html#cross-referencing-arbitrary-locations

**Comment by Jackenmen** [comment]
@retke we have default role set to `any` which takes care of finding the reference.

**Review by mikeshardmind — APPROVED** [review]

**Pull request merged**
