### PR TITLE
Urban supports specific definitions

### PR DESCRIPTION
**Pull request by Kowlin**
This is the only way to do this as far as I can find out. The reason being that we call for a string, and ye... Strings are evil!

### CODE REVIEW

**Comment by irdumbs** [comment]
`self, ctx, search_terms, result_number : int=1` ?
sorry, didn't occur to me until now :3

**Comment by Kowlin** [comment]
And how do we preserve multible spaces between words?

**Comment by irdumbs** [comment]
ah you would be correct in dat. carry on.
tiny change could be to take it in as a list instead, save you the trouble

**Comment by Twentysix26** [comment]
Refactored in https://github.com/Twentysix26/Red-DiscordBot/commit/881a1d3212f9544aaf47532acf681f30cac817f3

**Pull request closed without merging**
