### PR TITLE
[Trivia]Fix out-of-date NBA answers 

### PR DESCRIPTION
**Pull request by dsvobo**
Also added new questions

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
Updated 2 questions, added alternate answers for 2 questions, and added 18 questions.

### CODE REVIEW

**Comment by MiniJennJenn** [comment]
Thanks, I'll put these in. 
According to what I read, the LA clippers have had a 47 year playoff drought?

**Comment by dsvobo** [comment]
@MiniJennJenn They have a 47 season Conference Final drought, not playoff appearance drought. I guess that would be a good question to add though!

**Comment by MiniJennJenn** [comment]
jk that's active vs inactive. I've added both.

**Comment by dsvobo** [comment]
@MiniJennJenn I added 8 more lines to the NBA trivia. In the future, I will try to update the v3 files if I edit anything else. Thanks for the help!

**Comment by MiniJennJenn** [comment]
Sounds good :) 
Converting the trivia files: https://github.com/Tobotimus/trivia-yaml/blob/master/README.rst 
New trivia repo: https://github.com/Cog-Creators/Red-Trivia/tree/master/redbot/trivia/lists

**Review by Kowlin — APPROVED** [review]
LGTM.

**Comment by MiniJennJenn** [comment]
There have been minor changes I've made in my PR version. I'm not good enough with Github to know the best way to keep up with 2 different PR's, but I have included all of David's edits in my PR #1163 

I reworded one as well.

**Review by palmtree5 — APPROVED** [review]

**Review by tekulvw — APPROVED** [review]

**Comment by dsvobo** [comment]
All done... for now! Thanks for implementing my trivia edits!

**Comment by palmtree5** [comment]
Uh, we never merged anything lol. That was just approvals

**Comment by dsvobo** [comment]
OmegaLUL I am really new to this

**Comment by Kowlin** [comment]
Fixed in #1165

**Comment by dsvobo** [comment]
Not exactly, there are several pieces of code that are unchanged there.

**Comment by MiniJennJenn** [comment]
It has all been reviewed. Some things were not included to maintain quality for trivia lists.

**Pull request closed without merging**
