### PR TITLE
Audio PR part 1.5

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [x] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes
NO LONGER A DRAFT,  but this one has all the goodies from #2950 minus the new Menu implementation.

1.  Play + Bump Combo Command (#2522)
2.  Don't shuffle bumped tracks (Added an extra argument to [p]shuffle that allows the person with permissions to say whether bumped tracks should be shuffled or kept at the top of the queue, off by default)
3.  Expand local track support to all file formats (Added support for AAC, AU, M3U, M4A, OPUS, RA, TS, WAV, WMA, 3GP, FLV M4V, MKV, MP4, MOV, WEBM, WMV)
4. Cache DJ setting value to reduce api calls  (more significant on Mongo)
5. Rework UX to standardize messages (Summary of what message is about is the title, and a more  descriptive explanation is added to embed description/footer)
6. Add cooldowns to playlist save, eq save and summon, also add resets in error scenarios.
7. Add a global variant of the existing whitelist/blacklist thats thats priority over the server level whitelist/blacklist

@aikaterna  love you please don't kill me :eyes: 

No need to assign to anyone just as of yet but in theory everything here work since #2950  is fully functional, but ... since this hasn't been tested it I may have messed up some things, once I've taken it through i spin i'll flag it as ready for review.

### Update
This PR is ready to be reviewed

### CODE REVIEW

**Comment by Ianardo-DiCaprio** [comment]
There is no message saying whether or not the shuffle bump feature is on or off when you use the command and it also doesn't show the current setting in audioset settings.

**Comment by aikaterna** [comment]
This is a partial review, I intend to look at and test more parts of this PR.
Sorry for the line numbers mentioned in this text, my browser is not letting me display the larger diffs to comment on specific parts. If you have questions about any of these, please ask me in Discord.
_______________________________________
Shuffle docstring needs to be title case on Bumped and removed an s, added "this"
"""Toggle shuffle.
Bumped tracks default to True.
Set this to False if you wish to avoid bumped songs being shuffled.
"""
_______________________________________
Use [p]local play
Select a folder that has files in it
The listing footer says "search results" instead of “local folders” or “local files”
_______________________________________
Please display Shuffle-bump settings (true/false) in the response to the user
Also not sure why this was added as a bool to shuffle when it is stored as a setting, and could be a setting. I could be convinced otherwise on this though and it's fine as is with True or False as the arg, just seems awkward to me.
_______________________________________
Queue footer:

Page 1/16 | 154 tracks, 11:08:30 remaining  |  

Auto-Play: ❌ | Shuffle: ✅ | Repeat: ✅

Remove extra pipe on top line after "remaining" if the footer will always be 2 lines. Also please remove the extra line return inbetween the two lines.
_______________________________________
The removal of "\localtracks\" from queueing local tracks with play commands (including bumpplay), which was made in the Lord of Audio PR, should be mentioned in release notes (please correct me if this was mentioned somewhere, I remember us talking about it previously, but I just want the users to be aware)

Example command: [p]bumpplay ENM\501 - Inside The Machine.mp3
Was expecting: [p]bumpplay localtracks\ENM\501 - Inside The Machine.mp3
_______________________________________
Extra space before "Raises" in docstring in playlists.py under deleting a playlist
_______________________________________
Was it Black that forced "0 to disable" to a 2nd line on the docstrings for audioset emptypause, audioset emptydisconnect, and audioset vote? I feel like that should be shown to users by default and not have them have to run help specifically on that command to know that. Also audioset maxlength has this descriptor for "0 to disable" and it was not touched... if you were trying to standardize this change.
_______________________________________
The formatting for the track display for audioset status needs to be changed: see https://i.imgur.com/zwldslS.png
_______________________________________
Why is there an `await ctx.embed_colour()` here? (Line 2034)
_______________________________________
description=_("You must be in the voice channel pause or resume.") (Line 2615)
Should be "You must be in the voice channel to pause or resume."

**Comment by Drapersniper** [comment]
Morning forward will work on a fork of audio

**Comment by aikaterna** [comment]
[p]local play shows “x local folders” on the folder page, and shows “x local folders” on the track listing page as well. Was expecting “x local tracks” on the track listing embed. Local search returns the correct footer now, “x local tracks”

Using shuffle with no subcommand displays the help for shuffle and also toggles the setting, instead of just toggling it.

**Comment by Drapersniper** [comment]
Do not merge this one ... Merge #3205

**Comment by Drapersniper** [comment]
Will setup a CPR for all of this so itsd easier to follow ... less likely to fuck up)

**Pull request closed without merging**
