### PR TITLE
[Downloader] WIP V3 rewrite

### PR DESCRIPTION
**Pull request by tekulvw**
Goals

- [x] Make downloader in an API accessible format in order to hook cogs.red into it.
- [x] Find some way to support repo-wide "libraries"

### CODE REVIEW

**Comment by orels1** [comment]
Like it so far 👍 

Will copy my comment from discord too

so like my process will look like this.

- user calls `redp search redportal`

- user clicks on the download react

- redp cog calls `add_repo` for the repo, `RepoManager` adds it if it's not there and clones it and returns the list of cogs available

(from this point - not implemented yet) 

- redp looks throught the list for the cogs it needs and either drops an error, or calls (for example) `install`

- `Downloader` installs the cog and returns true to redp

- `Downloader` asks if user wants to load the cog

and that's it
looks like a nice process to me

**Comment by tekulvw** [comment]
Do we want to retain the "changelog" that existed in V2, modify it, or drop it entirely?

**Comment by Twentysix26** [comment]
Any plans for #516 ?

**Comment by tekulvw** [comment]
Already implemented

**Comment by Kowlin** [comment]
From my testing this seems to work and can be merged into the alpha. If anyone wants to add on that, feel free.

**Pull request merged**
