### PR TITLE
Text tells you what to put in info.json.

### PR DESCRIPTION
**Pull request by Apoo711**
Pull request adds paragraph about what you should add in info.json, also adds optional next to info.json.

### CODE REVIEW

**Comment by Apoo711** [comment]
Updated so code block actually works.

**Comment by Drapersniper** [comment]
The keys for the info.json and information about it can be found on this section of the docs.
https://docs.discord.red/en/stable/guide_publish_cogs.html#publishing-cogs-for-red-v3

I do not believe this PR is necessary, as the info.json is only needed if you plan to public your cog.

**Comment by Apoo711** [comment]
But then it shouldn't be mentioned in creating cogs, shouldn't it just be mentioned in https://docs.discord.red/en/stable/guide_publish_cogs.html#publishing-cogs-for-red-v3.

**Comment by Drapersniper** [comment]
I disagree with you; perhaps it should link to the info.json section in our publishing docs sure, but it should still be mentioned as creating the info.json although not necessary for non published cogs its a good thing to get in the habbit of doing to for the benefit of users.

**Comment by Apoo711** [comment]
Ahh I understand!

**Pull request closed without merging**
