### PR TITLE
[Mod] APIify modlogs

### PR DESCRIPTION
**Pull request by palmtree5**
This will allow for easier usage of mod logs by third party cogs by allowing them to be able to register new case types. The mod log can be accessed by other cogs by doing something like `self.modlog = self.bot.get_cog("Mod").modlog`. Then from there, they can use `register_casetype` to add a new case type and then use `new_case` for adding new cases. This does not reset cases at all, but settings related to the modlog feature (i.e. modlog channel and case type settings) would need to be redone by the user after updating if this were merged as is

### CODE REVIEW

**Comment by palmtree5** [comment]
As for what needs to be tested:

- [x] Create a case
- [x] Specify a reason
- [x] Edit the case
- [ ] Register a custom case type and try using it

**Review by Twentysix26 — DISMISSED** [review]
Needs a rebase

**Comment by palmtree5** [comment]
rebase done

**Comment by palmtree5** [comment]
ok, this is actually fixed now

**Comment by palmtree5** [comment]
bump since it's been almost 2 weeks

**Comment by palmtree5** [comment]
Rebasing intensifies

**Comment by palmtree5** [comment]
And done

**Comment by tekulvw** [comment]
Do we want to just hold off on this and incorporate it into V3?

**Comment by tekulvw** [comment]
Closing as this will likely be included in V3.

**Pull request closed without merging**
