### PR TITLE
[Announce] No error message

### LINKED ISSUE #4196: [Announce] No Error Message
# Command bugs

- [x] Bug
- [x] Enhancement
- [ ] Feature

#### Command name

[p]announce

#### What cog is this command from?

Admin

#### What were you expecting to happen?

Error message when no channel was setup to receive announcements

#### What actually happened?

The `The announcement has begun.` message sends regardless if no channel was set to receive announcements.

#### How can we reproduce this issue?

1. Clear your announce channel from all servers your bot is in if you had any set.
2. Use the announce command as normal
3. Observe

### PR DESCRIPTION
**Pull request by douglascdev**
### Type

- [X] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
 Bot now sends a error message to the owners after trying to announce on a server where the announcement channel was not set/deleted.
 I also added a specific message to the exception discord.Forbidden and to when the bot does not have permission to send messages on the channel, and fixed two typos I found in a docstring on another module.
 Closes #4196.

### CODE REVIEW

**Comment by Jackenmen** [comment]
I was expecting this to only send an error message if there's not a single server that has an announcement channel set, not for *every* server that doesn't have announcement channel set. This could result in a very long message for public bots.

**Comment by douglascdev** [comment]
Oh right, I'll change it to work like that.

**Comment by Jacob-1999** [comment]
@jack1142 I just tested this again and here is an image of my attempt. The bot you see that I'm using is in 2 servers, neither has an announcement channel setup, and I receive no error in my direct messages nor anywhere else. Not sure if this is what you mean but ¯\\\_(ツ)_/¯

image

**Comment by Jackenmen** [comment]
@infamous-jacob this is a pull request. A pull request is a method of submitting contributions to the project. These changes are not in Red's development version until the PR has a "merged" status (and every PR might also just be closed without merging, if there's a reason to reject the contribution) and they're not in Red's stable version until version with the "merge commit" of this PR is released.
So yes, current version of Red does not have this change, as a matter of fact, it's not even ready yet.

**Comment by Jackenmen** [comment]
@douglas-cpp Hello there, do you still plan to work on this?

**Comment by Jackenmen** [comment]
Closing due to no activity.

**Pull request closed without merging**
