### PR TITLE
Let Downloader use the plural

### PR DESCRIPTION
**Pull request by madebylydia**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

Downloader will now use the plural when needed, like when there's only one repository, only one cog loaded, unloaded, etc...
It may need fix about grammar.

### CODE REVIEW

**Comment by Drapersniper** [comment]
Hey just a quick headsup.
This pural here is not i18n friendly.

which means it cannot be used with the current implementation, just wanted to give you a early warning here.

The way for you to implement this which would be more friendly would be 


```py
				message += _("Successfully uninstalled {plural}: ").format(plural=_("cogs") if len(uninstalled_cogs) > 1 else _("cog")
                ) + humanize_list(uninstalled_cogs)
``` 

as an example

**Comment by Jackenmen** [comment]
> Hey just a quick headsup.
> This pural here is not i18n friendly.

I guess I'm too slow
image

**Comment by madebylydia** [comment]
Alright, I change that and push later.

**Comment by Jackenmen** [comment]
> The way for you to implement this which would be more friendly would be
> 
> ```python
> 				message += _("Successfully uninstalled {plural}: ").format(plural=_("cogs") if len(uninstalled_cogs) > 1 else _("cog")
>                 ) + humanize_list(uninstalled_cogs)
> ```
> 
> as an example

Please don't do this either, it's not much better with i18n as other parts of a sentence can also change between singular and plural, i.e in Polish (more or less, I don't know what would be used for `cog`):
`<Cog> został pomyślnie odinstalowany.` for singular 
`<Cogs> zostały pomyślnie odinstalowane.` for plural

So please use two completely separate sentences here.

**Comment by Drapersniper** [comment]
> > The way for you to implement this which would be more friendly would be
> > ```python
> > 				message += _("Successfully uninstalled {plural}: ").format(plural=_("cogs") if len(uninstalled_cogs) > 1 else _("cog")
> >                 ) + humanize_list(uninstalled_cogs)
> > ```
> > 
> > 
> > as an example
> 
> Please don't do this either, it's not much better with i18n as other parts of a sentence can also change between singular and plural, i.e in Polish (more or less, I don't know what would be used for `cog`):
> `<Cog> został pomyślnie odinstalowany.` for singular
> `<Cogs> zostały pomyślnie odinstalowane.` for plural
> 
> So please use two completely separate sentences here.

Damned Polski... but yeah good point

**Comment by Jackenmen** [comment]
@Predeactor So yeah, what Draper said to do isn't good enough as I said above, sorry for confusion 😛

**Comment by Jackenmen** [comment]
@Predeactor you removed your fork.

**Comment by madebylydia** [comment]
0_0
What a mistake, sorry

**Comment by madebylydia** [comment]
Replaced by #4004.

**Pull request closed without merging**
