### PR TITLE
[Mod] Add two new settings to disable name/nickname tracking

### LINKED ISSUE #4514: [Mod] Toggable nickname/username saving.
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [x] API functionality

#### Describe your requested feature
I know this was brought up before the Data API configurations were talked about (data retention and so). There was a PR that was started on regarding this, though it was closed for reasons I forget.

I wanted to bring this back up in an issue to gather feedback on having a command to toggle the bot saving nicknames and usernames in the Mod cog, currently there is no such thing and it's saving people's nickname changes.

I'd also like to purpose a command that lets possibly server owner or just bot-owner permission to wipe the complete list of names / usernames if they use the command.

One thing I'd like to spark up a conversation on is the possibility of having servers opt-in on nickname saves if the bot-owner allows for it. Giving the ability to toggle it on per server and toggle it on as a whole.

If the bot owner disables it, no matter what it's disabled. Though if it's enabled and a owner wants to record that for their server, they can opt into it.

* Sorry for spelling / grammar, it's nearly 3 am and I'm tired.

### LINKED ISSUE #4798: [bug] the mod cog/core made bot super slow with making large setting files.
**What Red version are you using?**

3.4.5

**What were you trying to do?**

my bot were super slow my bot is in 4k servers and i unloaded the mod cog like [p]unload mod. then my bot is fast again. i checked whats going on with Process Monitor software and i saw the redbot in mod settings is making so many large files.( i think its bc it check the users changing their name and it save it to the settings or idk for real.)

**What did you expect to happen?**

it shouldnt bug the bot or slow down the bot like this. it use so much cpu too.

**What actually happened?**

please look at screenshot that i send
bot keep writing large files in settings = https://cdn.discordapp.com/attachments/760365719660527627/808880223063375882/unknown.png 
and here  : https://cdn.discordapp.com/attachments/760365719660527627/808880819481215016/unknown.png 

**How can we reproduce this error?**

1. load the mod cog/core
2. it keep making large files.

### PR DESCRIPTION
**Pull request by Flame442**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
Adds two new commands, `[p]modset trackallnames` and `[p]modset tracknicknames`. Since `trackallnames` needs to be able to be run in DMs, the group command `[p]modset` was modified to be usable in DMs, as well as `[p]modset showsettings`.

`[p]modset trackallnames` disables name tracking and overrides the nickname tracking setting for all guilds.
`[p]modset tracknicknames` disables nickname tracking in the current guild.

Closes #4514
Closes #4798

### CODE REVIEW

**Comment by Jackenmen** [comment]
Not a review, I just have two things up for consideration.

- Should the tracking be enabled by default? Personally, I think it's alright to keep it on by default, but I think that some people don't agree with this so I want to bring it up.
- I think it would make some sense to have a way to clear all stored usernames and/or nicknames as disabling the functionality currently still keeps all the names and nicknames in the bot's storage.

**Comment by Flame442** [comment]
> I think it would make some sense to have a way to clear all stored usernames and/or nicknames as disabling the functionality currently still keeps all the names and nicknames in the bot's storage.

Personally, I think that should be done explicitly somewhere else (does the cog data deletion have anything else it deletes anyway?) rather than bundling it in here.

**Comment by Jackenmen** [comment]
Hmm, without a way to clear the data this PR does not fully resolve #4798 IMO as there's no way to clear the data other than doing it manually in the data storage while the bot is offline.

Edit: seems like #4514 also mentions a command for wiping username and nickname data so that isn't resolved either.

**Comment by TrustyJAID** [comment]
I really like this change. However, Jack is right about the missing features as they should be included in this. Removing past names is trivial with a config clear on users. Clearing nickname changes is a bit more challenging since you'd have to iterate through the entire guild and member list. In my experience though clearing the username's changed my mod settings from 14mb down to 3mb in size.

**Review by Jackenmen — COMMENTED** [review]
LGTM code-wise and I've tested the changes too. Not approving yet as there's an ongoing conversation on what the defaults should be.

**Review by Jackenmen — CHANGES_REQUESTED** [review]
Actually, I've just remembered that we wanted a hint about the `[p]modset deletenames` (already approved so it's safe to add here) to be included when disabling tracking of all names so that should get addressed.

**Review by Jackenmen — DISMISSED** [review]
LGTM.

**Review by Jackenmen — APPROVED** [review]

**Pull request merged**
