### PR TITLE
[Streams] use embeds for stream info if live

### PR DESCRIPTION
**Pull request by palmtree5**
Adds embed support for Beam, Hitbox, and Twitch (though only Twitch and Beam will have an image with them). Embeds only happen if the channel specified by the user is live on the service

### CODE REVIEW

**Comment by palmtree5** [comment]
Should note that I tested `[p]beam`, `[p]hitbox`, and `[p]twitch` before I pushed this to my fork. Haven't tested it with the notifier but that should be fine

**Comment by palmtree5** [comment]
Put in checks on the twitch commands for where the game and/or title aren't set

**Comment by palmtree5** [comment]
Fixed the issue I was having where alerts weren't happening. Note to self: don't try to .format a dict into a string...

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/b69b5b30056c5b4fb213b20ee0970f22de5c0503

**Pull request closed without merging**
