### PR TITLE
Remove PM2 guide

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Removal

### Description of the changes
There's apparently no way to specify exit codes
for which the process should not be restarted.

This just shows how poor of a process manager PM2 is
so we really should not continue to recommend it in the documentation...

Ref:
https://stackoverflow.com/questions/43614017/how-to-only-restart-node-process-with-pm2-if-exit-code-0

---

Change my mind :P

### CODE REVIEW

**Comment by Apoo711** [comment]
This'll remove auto restart for mac users, as pm2 works but we don't have systemd.

**Comment by aikaterna** [comment]
Mac users use a plist file.

**Comment by Drapersniper** [comment]
Consider this my approval here, dont wanna do an official one so the big green button doesnt show my and im physically forced to press it just yet...

**Comment by Kowlin** [comment]
Can't find the damn approve button on mobile...

**Pull request merged**
