### PR TITLE
[Audio] Disallow all users from modifying Playlist 42069.

### PR DESCRIPTION
**Pull request by Drapersniper**
As the title states, users should not manually edit this playlist, specially delete it, even though it comes back on next cog reload/bot restart it may leave the bot in a unsupported state as the presence of this playlist is mandatory, if autoplay is expected to work.

### CODE REVIEW

**Review by Jackenmen — CHANGES_REQUESTED** [review]
It seems unnecessary to pass `bypass=False` everywhere considering it's the default.

**Comment by Drapersniper** [comment]
> It seems unnecessary to pass `bypass=False` everywhere considering it's the default.

You've missed https://github.com/Cog-Creators/Red-DiscordBot/pull/5018/files#diff-bd87e54068100b18833ef1210198b0be47138aa7f667fca5876412c625399e88R1694


and Im dumb...

**Review by Jackenmen — CHANGES_REQUESTED** [review]
I see that you changed `playlist.id` to `getattr(playlist, "id", 0)`. From what I can see `Playlist` object will always have the `id` attr, which suggests that the `playlist` variable might not be a `Playlist` object. If that can indeed happen, then the type hints should be updated appropriately.


Also this change with `getattr()` doesn't really seem that related to this PR's real purpose which is fixing the stuff with playlist 42069...

**Comment by Drapersniper** [comment]
It can be a SimpleNamesace when mocked.

**Review by Jackenmen — APPROVED** [review]
The error message is IMO not ideal but it's the simplest way to fix this so I think it's good enough until proven otherwise.
image

**Comment by Drapersniper** [comment]
I've filed #5052 to track it.

**Pull request merged**
