### PR TITLE
fixed hug command lol

### PR DESCRIPTION
**Pull request by NotSoSuper**

### CODE REVIEW

**Comment by Twentysix26** [comment]
Granted, it is indeed bugged because when I made it I lazily copy pasted another command (probably !info) and then forgot to edit the parameters but your fix is not correct.
!hug is meant to be used with other users, yours only work with the author. Thanks for making me notice

**Comment by NotSoSuper** [comment]
Ah I see, I could change it for that however it seems you've got it.
Thanks.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/3c338eeab5574c13de399e900f1172470333ae0f
I think I may have went a bit overboard

**Comment by ghost** [comment]
10 intensity levels of hugs? Oh my...

**Pull request closed without merging**
