### PR TITLE
[V3 Core] Command group help

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [ ] Bugfix
- [X] Enhancement
- [X] New feature

### Description of the changes

This puts all the boilerplate for command help in the group decorator. This targets b16. 

This adds `autohelp` as a kwarg for the group decorator. On b16 this defaults to False to give 3rd party cogs time to adjust. For b17 this will be switched to defaulting to `True` as it is the more used case. (exactly one exception in current core code)

This flag is incompatible with `invoke_without_command` 

This is not a breaking change until the additions targeting b17

### CODE REVIEW

**Comment by mikeshardmind** [comment]
(discussion from #1785 )

**Comment by tekulvw** [comment]
When the default becomes `True`, will this conflict with any existing help checks?

**Comment by mikeshardmind** [comment]
Nope, still only gets called if it normally would, this just gives cog creators time to have a chance to decide if they want to opt out.

**Comment by mikeshardmind** [comment]
I think I may have misunderstood your question. Using this will not conflict with someone sending help from a group command, but it may end up sending it twice if they are using `auohelp=True` on b16 (or after, and not using `autohelp=False`) and have not removed help calls from that group.

What this does is when autohelp is specified to a group decorator:
if there is no invoked subcommand, or the invoked subcommand is that group, and `invoke_without_command` is not used, send help.

This is a relatively common pattern in cogs, and even ones that do other things like display settings on no command can still work using this.

**Review by tekulvw — APPROVED** [review]

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
