### PR TITLE
[Image] rewrite imgur command to use subcommands

### PR DESCRIPTION
**Pull request by palmtree5**
Overrides #432. The changes from that PR were worked into a rewrite of the imgur command in images.py such that it uses subcommands. Also some general PEP8 formatting stuff all over in the image cog. Tested in #advanced-testing in discord and it appears to work fine (i.e. it doesn't crash and burn)

### CODE REVIEW

**Comment by Twentysix26** [comment]
Did some adjustments but could use more work.  
Also, very few people noticed but this cog has blocking issues. Since we're rewriting we might as well do something about this.

**Comment by tekulvw** [comment]
Specifically, the imgurclient lib uses requests which means you'll need to use `loop.run_in_executor` for each call to the lib

**Comment by palmtree5** [comment]
new commit from @fwinest-JediThug on this branch that moves the giphy api key into a variable

**Comment by Twentysix26** [comment]
Closing for impending rewrite.

**Pull request closed without merging**
