### PR TITLE
[Owner] Link branch in [p]version, logic fix, better batch start

### PR DESCRIPTION
**Pull request by Jan200101**
made it only remove the .git extension if it exists

made it display a custom message if its not a git repository

added direct link to the branch

### CODE REVIEW

**Comment by Jan200101** [comment]
I got nothing to add for now.
If there is any suggestion leave it here

**Comment by Jan200101** [comment]
I also dont know if the git language fix works if git is still on default language so someone needs testing aswell as the batch files, but they worked for me so far.

I hand decided if the Batch also should have a special coloring (Though of red text on black background) but its White text on Black background for now and added the red text as a comment behind it

**Comment by Jan200101** [comment]
forgot to add that start_red files are now in .gitignore

**Comment by Jan200101** [comment]
The only thing missing now is feedback

**Comment by Twentysix26** [comment]
[I think you might benefit by reading these tips](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/). Closing this, I'll implement the bug fixing parts myself.

**Pull request closed without merging**
