### PR TITLE
Use the commands module instead of checks for permission decorators

### PR DESCRIPTION
**Pull request by Kreusada**
Use commands instead of checks for permission decos.

### CODE REVIEW

**Review by Drapersniper — COMMENTED** [review]
Won't merge in case Jack want to give some input but reviewed the code changes and they all look good and ready for merging pending Jacks input.

**Comment by Drapersniper** [comment]
JAAAAAAAAAAACK yes its noise, but at the very least merge it as first PR in 3.5.0 (or as last in 3.4.10 :Awesome:)

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Comment by Flame442** [comment]
Hi there @Hbutlercapone, while we appreciated people taking a look at PRs to see if they are working for them, you have reviewed this PR 4 times in a row. Would you mind keeping it to 1 review at a time, unless you have something new to add? Thanks!

**Review by Fabian-Evolved — DISMISSED** [review]

**Comment by Kreusada** [comment]
See #5463.

**Pull request closed without merging**
