### PR TITLE
Update cogboard links

### PR DESCRIPTION
**Pull request by Apoo711**

### CODE REVIEW

**Review by Jackenmen — CHANGES_REQUESTED** [review]
Hi there, could you update the links in `docs/guide_cog_creators.rst` and `docs/cog_guides/cog_manager_ui.rst` as well?

**Comment by Jackenmen** [comment]
As for the link in the `README.md` (not the docs ones), it would be preferred if it was replaced with a link to `https://index.discord.red`

**Comment by Apoo711** [comment]
Ok I'll make all those changes now!

**Review by Jackenmen — APPROVED** [review]
Thanks, looks good now!

**Pull request merged**
