### PR TITLE
[V3] Same link can be added multiple times on a playlist

### PR DESCRIPTION
**Pull request by rguan72**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
If a user tries to append a song url to a playlist that already has the song, the song is not appended and red tells the user that the song is already in the playlist. This only checks if the exact url has already been added, so songs with the same title but different urls can be added. Black also found a style issue, but I was having some trouble submitting getting around it so I wanted to submit a pull request first.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
Hey! Appreciate the pull for this. We have a makefile that will handle style for you (`make reformat`) from the project directory with red's stlye extra installed (`pip install red-discordbot[style] -U --process-dependency-links`)

**Comment by rguan72** [comment]
Hey, is making a test for a bug like this necessary? If so, where should I write the test? I couldn't find a file for audio cog tests in the tests folder. Thanks!

**Comment by aikaterna** [comment]
No tests needed, it should be looked at by a QA member or someone else willing to test it and leave a review. I intend to look at this later myself, but if someone would like to test and comment it would be appreciated.

**Review by aikaterna — DISMISSED** [review]
Thanks for this addition and closing the issue referencing this. Not really sure why we have README edits attached to it, but that looks fine too. In the future I (or anyone else) might revisit this to iterate through playlist links with multiple tracks added via append to discard duplicate existing tracks as well.

**Review by Tobotimus — APPROVED** [review]
Thanks, and congrats on your first PR :tada:

I reverted the README changes to avoid conflicts with another PR, I assume they were just accidental from your IDE stripping trailing whitespace.

**Pull request merged**
