### PR TITLE
😃 I 😃 know 😃 you 😃 all 😃 want 😃 this 😃 !

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
😃 This 😃 PR 😃 makes 😃 all 😃 send 😃 methods 😃 wrap 😃 text 😃 in 😃 "😃" 😃 !

### CODE REVIEW

**Review by Kowlin — DISMISSED** [review]

**Review by PredaaA — CHANGES_REQUESTED** [review]
Since it isn't 1st April and so that it isn't a joke, I would like some personalization of the emoji. As my friends said after some testing, I quote: "It is scarying, that emoji is cringe, I see it in my dreams, which transform them to nightmares."

**Comment by Drapersniper** [comment]
> Since it isn't 1st April and so that it isn't a joke, I would like some personalization of the emoji. As my friends said after some testing, I quote: "It is scarying, that emoji is cringe, I see it in my dreams, which transform them to nightmares."

@Flame442 has a flaming dick emoji we could use

**Review by NeuroAssassin — CHANGES_REQUESTED** [review]
I would also like the flaming dick to be an option

**Comment by ltzmax** [comment]
😃 we 😃 are 😃 gonna 😃 see 😃 alot 😃 of 😃 smileys 😃

**Comment by DariusStClair** [comment]
I am expressing sadness through this comment.

**Comment by fixator10** [comment]
:smiley:

**Review by Bakersbakebread — APPROVED** [review]

**Review by fixator10 — APPROVED** [review]

**Review by Drapersniper — APPROVED** [review]
LGTM (although flaming dicks would make it better, there nothing that dicks don't improve)

**Comment by Kowlin** [comment]
Probs a good time that we end this joke 😃.

**Comment by Jackenmen** [comment]
😃

**Pull request closed without merging**
