### PR TITLE
V3/start screen

### PR DESCRIPTION
**Pull request by Redjumpman**
Created a new screen for Red's start-up. Includes the following information:

- Bot Name
- Prefixes
- Red's Version
- Language
- Servers
- Users
- Cogs
- Commands
- If Sentry is reporting Errors
- If MongoDB is being used.
- Number of shards

image

This PR also adds a required bordered function I made to create the boxes. I stuck it in chat_utils incase someone else wanted to use it.

### CODE REVIEW

**Comment by DannyB5544** [comment]
Idea: Have the ticks/crosses light up green or red (of course, green for tick/red for cross)
Should be doable to single characters via escape characters

**Comment by bobloy** [comment]
In this situation, what is Users? The # of users on all servers combined?

**Comment by DannyB5544** [comment]
That's exactly what it is

**Comment by Redjumpman** [comment]
@bobloy Yes that's the total users.
@DannyB5544 It will be hard to do that because of how I wrote my border function. I'll have to look into it.

**Comment by DannyB5544** [comment]
I think it could be done in string. I'll experiment too

**Comment by tekulvw** [comment]
As per @palmtree5's suggestion, can we add d.py version information?

**Comment by Redjumpman** [comment]
Yeah that's a good one. Are there any others you would like for me to add?
I could also add some checks for the optional packages voice and for docs/tests

**Comment by tekulvw** [comment]
That information would be good to add as well. I don't personally have anything else on my mind to add adn I think that after dpy/package information is in this PR we should go ahead and merge.

**Comment by Redjumpman** [comment]
Added Discord.py Version
Added Docs/Test package checking
Added Voice package checking

New screen looks like this: 
image

**Review by palmtree5 — APPROVED** [review]

**Pull request merged**
