### PR TITLE
Fix "Playing..." tag

### PR DESCRIPTION
**Pull request by zsr2531**
This worked for me! Something happened with the wrapper that requires changing the way of updating the "Playing..." tag.

### CODE REVIEW

**Comment by Twentysix26** [comment]
Could you go into details on what this is supposed to fix?

**Comment by zsr2531** [comment]
I saw a message in #announcements in the Discord server about "Playing..." tags not working. And I thought to myself, "Hmmm...That stopped working for me as well for some reason." (on another bot), and I did some research and found out if I change the `change_presence` function like so, it fixes the* issue.

**Comment by Twentysix26** [comment]
The message after that asks to update discord.py to fix the issue. No code change is needed.

**Comment by zsr2531** [comment]
I was using the latest discord.py version when I had the issue with another bot, I thought the issue was the same here. Seems like it wasn't.

**Pull request closed without merging**
