### PR TITLE
Output to Music channel what song is playing.

### PR DESCRIPTION
**Pull request by DevScyu**
Output to Music channel what song is playing.

### CODE REVIEW

**Comment by tekulvw** [comment]
This only works for servers that have a channel named music and should really be a function separate from the queuing controls

**Comment by DevScyu** [comment]
I didn't want to change the code that much, I am going to add a toggle feature and a way to chose the room name PER server hopefully.

**Comment by franc-ist** [comment]
Yeah, but in many servers, people play songs wherever they want. Maybe you should set it to the channel where the command was used?

**Comment by zeosmar** [comment]
Would be a nice make a mention to the user who made the request.

**Comment by Twentysix26** [comment]
Too limited. Closing in favor of https://github.com/Twentysix26/Red-DiscordBot/pull/379

**Pull request closed without merging**
