### PR TITLE
Add methods for getting app command IDs/mentions from cache

### LINKED ISSUE #5976: Add functionality to mention app commands
### Type of feature request

API functionality

### Description of the feature you're suggesting

Currently mentioning an app command is pain with plain discord.py. You would need to fetch all commands from api and search for the right command. This can be improved by implementing a cache. 

A tag from discord.py: 
> To have your bot mention its own commands without hardcoding them, you'll need to use either tree.sync or tree.fetch_commands to get the commands from discord then .mention the command(s) you want.
It's recommended to subclass CommandTree to override these methods and cache the results to avoid unnecessary api calls.

The best way would be adding such cache in the tree. This cache is either supplied on sync or when triggering manually an update with a method.

Furthermore a method to get a mention would be nice. E.g. `Bot.get_app_command_mention(name: str, guild_id: Optional[int]) -> Optional[str]` 
Usage: 
- `bot.get_app_command_mention('ban')`
- `bot.get_app_command_mention('cog update')`
- `bot.get_app_command_mention('load', guild_id=133049272517001216)`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Flame442**
### Description of the changes
Adds `bot.get_app_command_id` and `bot.get_app_command_mention` which pull from the ID cache built when `RedTree.sync`ing.

Potential future work:
- Hook into `CommandTree.fetch_commands` to update the cache manually using the fetched command data
- Migrate the current data structure to allow storing guild specific app command IDs on guild `sync`, and allow these new methods to be used to pull from that cache as well

Fixes #5976

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Comment by Jackenmen** [comment]
> Potential future work:
> * Migrate the current data structure to allow caching on guild `sync`, and allow these new methods to be used to pull from that cache as well

Having such a cache now would mean we don't need to make these methods asynchronous and such a change to method signature is not really something we can do once the API is released. Is there any reason we wouldn't want those methods to be synchronous?

**Comment by Flame442** [comment]
I don't mean a memory cache, I mean storing in config _guild specific_ command ids. Currently, only global app command ids are stored, since that is all the `[p]slash` system cares about.
(Edited original to be more clear)

**Comment by Jackenmen** [comment]
Oh yeah, I missed that this remark is about guild stuff. Either way, I am still wondering about the in-memory cache thing to get a synchronous API, it does seem a bit unfortunate that it requires awaiting right now.

**Review by Daniel07468 — COMMENTED** [review]
Redbot

**Review by Jackenmen — APPROVED** [review]
LGTM. Sorry that I'm only coming to this *now*, two releases later than I said I would...

**Pull request merged**
