### PR TITLE
Make `humanize_list()` use babel.

### LINKED ISSUE #2906: No special case for 2-tuple humanize_list
# Other bugs

#### What were you trying to do?

use humanize_list with a 2-item list

#### What were you expecting to happen?

returns "*x* and *y*"

#### What actually happened?

returns "*x*, and *y*"
note the comma here

#### How can we reproduce this issue?

use humanize_list on a 2-tuple

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

`humanize_list` will now use `babel.list.format_list` for it's logic. This closes #2906

### CODE REVIEW

**Review by mikeshardmind — COMMENTED** [review]
This can't be merged till we officially handle #2850

**Review by mikeshardmind — CHANGES_REQUESTED** [review]
This needs to include changes for places where humanize list is used to pass the current locale

**Review by Jackenmen — CHANGES_REQUESTED** [review]
Docstring should contain some info about the `style` arg - what determines if locale supports specified style? Since it's not handled by Red, saying this is based on Babel's `format_list` should probably be enough unless you think it's worth saying more.

There is one other issue I see with this though - this will change the current behavior for the empty sequences and someone relying on this raising `IndexError` is gonna be surprised. I'm not sure if we want to pursue this breaking change in 3.4.0, but if we don't then you could add an `if not items` and raise `IndexError` there.

**Comment by Drapersniper** [comment]
Whoever wants to pick this one up feel free to

**Review by Jackenmen — DISMISSED** [review]
This PR is approved, it is waiting for merge until we're ready for 3.4 release (hence the Blocked label).

**Review by Jackenmen — APPROVED** [review]
This PR is approved (approving again after conflict resolution), it is waiting for merge until we're ready for 3.4 release (hence the Blocked label).

**Pull request merged**
