### PR TITLE
Special case new RLL message (RLL 0.5.1 bump inside)

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### CODE REVIEW

**Review by Jackenmen — DISMISSED** [review]
Works great with https://github.com/Cog-Creators/Red-Lavalink/pull/78
I wonder if it wouldn't be good to set an embed description to something like "Something went wrong when fetching track" or whatever as all (or most) other errors in Audio have a concise friendly error and I wouldn't really say this is a concise or friendly error:
image
Example of what it could look like with additional one-liner:
image

I don't think this the most important thing so I'm approving this PR anyway, but I think the addition I mentioned is worth considering.

**Comment by Drapersniper** [comment]
it wouldnt follow the format set by audio for all of its error messages.

this is something to consider for the rewrite though...  other things can be in the description field

**Comment by Jackenmen** [comment]
I guess what I mean is that the error in footer is quite verbose and "Nothing found." text while simple, doesn't really explain *that* much about it and isn't exactly correct either. This isn't a most typical error so I just went with something generic but I guess even the error "Service Unavailable" sent after "Message: " could work *somewhat* better than "Nothing found."
I'm not convinced about either of these so approving status quo is better than leaving the error like this 😄:
image

**Comment by Drapersniper** [comment]
To expand on it the other exceptions, are exceptions provided by the jar, this is the one of new that arent, so the handling of it is iffy at best... (all other exceptions provided by the jar are handled in the footer, so further special casing this imo would:
1. Overly complicate the code
2. Add something that will be removed shortly.
3. Break from current pattern

Although like you mentioned ... adding it does make it clearer to the user so i'll leave aika to make the final call on this.

**Comment by aikaterna** [comment]
After a discussion in Discord I agree about adding the clarification that Jack asked for, but my opinion is that it should be done in a subsequent PR as it's not something simple to tack onto this one in a quick manner. I agree with this PR and will be approving it but we should refer back to this later on the audio todo list.

**Review by aikaterna — DISMISSED** [review]

**Review by Jackenmen — APPROVED** [review]
Bumped RLL version to 0.5.1, reapproving.

Will need to rerun checks when RLL 0.5.1 is released.

**Pull request merged**
