### PR TITLE
Add variation selector-16 as appropriate to emojis across Red

### LINKED ISSUE #4106: Look through emojis used in Red to see if some don't need variation selector
#4105 handles emojis in chat formatting, but all other places in Red still need to be checked. 

Info copied from Sinbad's PR:
  - Ensures consistent rendering across devices
  - See:  https://unicode.org/Public/emoji/12.1/emoji-variation-sequences.txt

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fixes #4106

### CODE REVIEW

**Comment by Drapersniper** [comment]
Why did you delete `redbot/cogs/mod/casetypes.py` ?

**Comment by Jackenmen** [comment]
@Drapersniper it isn't used anywhere (aside from the unused import that has been removed as well) and it contains incorrect emojis as well. I can separate it, but I don't want to lose time on updating emojis in it.

**Comment by Drapersniper** [comment]
Ah didnt notice it wasn't used anywhere. nah no need to separate it imo.

**Review by Drapersniper — APPROVED** [review]
LGTM

**Pull request merged**
