### PR TITLE
Turn economy to server specific

### PR DESCRIPTION
**Pull request by tekulvw**
Needs testers!

Fix for #187 server specific bank

### CODE REVIEW

**Comment by irdumbs** [comment]
problems I have with this:
- requires all users to re-register
- moves multi-server users' balances to one server, removing their balance from all other servers
- the 1st server they re-register to will be the one with their balance. does not warn the user of this at all
- should be done without users noticing. Too much user involvement because of the above issues

**Comment by tekulvw** [comment]
@irdumbs latest commit 663c2d2 gives the original account value to a user once they use an economy command on a new server

**Comment by irdumbs** [comment]
ty <3

**Comment by ddday** [comment]
tested it, users did have to re-register and commands had to be used twice to go through

**Comment by tekulvw** [comment]
Closing because of impending doom.

(economy rewrite)

**Comment by Kowlin** [comment]
https://youtu.be/aXU8w336oGs

**Pull request closed without merging**
