### PR TITLE
Update pronouns used for the bot in documentation

### PR DESCRIPTION
**Pull request by Apoo711**
I change "she joins" to "they join" to make it non gender specific.

### CODE REVIEW

**Comment by Apoo711** [comment]
NOTE: Not a very big change, this just bugged me because I don't think all bots would be female.

**Comment by Jackenmen** [comment]
why not "it"?

**Comment by Apoo711** [comment]
Oh I just thought to refer to them as people, but I'll change it now.
Done!

**Comment by Drapersniper** [comment]
Red is named after the main character of "Transistor", a video game by Super Giant Games.

Our docs refer to the bot as Red, and thus "She".

**Comment by Apoo711** [comment]
> Red is named after the main character of "Transistor", a video game by Super Giant Games.
> 
> Our docs refer to the bot as Red, and thus "She".

I did realise that, I thought the docs referred to the general bot that the person is running it on.
If you find this commit incorrect I close it.

**Comment by Jackenmen** [comment]
After gathering more information, it turns out most of the docs refer to the bot by "it" and there are only 3 occurrences of "she" which all can be replaced with "it" as they refer to the bot as an app rather than the character.

If you could update this PR to also update the two other occurrences that appear in the `docs/getting_started.rst`, it would be great.

**Comment by Apoo711** [comment]
Ahh ok sure!
Thank you Jack!

**Comment by Apoo711** [comment]
I added the pronoun change in getting_started.rst, pull request #5062

**Comment by Jackenmen** [comment]
I was hoping you would include in *this* PR rather than make a new one. Do you know how to update this PR with more changes or do you want some help?

**Comment by Apoo711** [comment]
Oh could i have some help
i know how to do it with changes in the same file, but in different ones.

**Review by Jackenmen — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
