### PR TITLE
Audio Refactor: Part 1  - APIs

### PR DESCRIPTION
**Pull request by Drapersniper**
As the title says this one handles the internal APIs used by Audio ... still WIP.

### CODE REVIEW

**Comment by Drapersniper** [comment]
This is now ready for review

**Comment by Drapersniper** [comment]
@fixator10  not quite, this branch doesnt always need to be up to date with the v3/develop branch.

**Comment by Drapersniper** [comment]
Blocked by #3459

**Comment by fixator10** [comment]
> @fixator10 not quite, this branch doesnt always need to be up to date with the v3/develop branch.

*this was an comment to version bump commit, thanks github for putting it in pull request*

**Review by aikaterna — APPROVED** [review]
Talked to Draper about the intents of this PR and am approving this so he can move forward with the feature branch.

**Pull request merged**
