### PR TITLE
[Filter] Filter API

### PR DESCRIPTION
**Pull request by palmtree5**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
This moves the logic for checking the filter as well as adding and removing things from the filter to `redbot.core`. A number of settings have also been introduced here as well as a `is_sentence` parameter on the add/remove commands that is optional. Documentation for this is still to come though

### CODE REVIEW

**Comment by palmtree5** [comment]
Ok, docs for the API are in now. If anyone has requests on things to add to this thing in general though, go for it. Currently, it covers adding and removing items from the filter, checking messages against the filter, and checking a member's name/nick against the filter

**Comment by entchen66** [comment]
Some more ideas for the rewrite:

* Add a view of all serverwide filtered words and include all channel explicit filter words
* make filter channel add available outside the channel you wanna add a word

**Comment by Drapersniper** [comment]
@palmtree5  do you have any plans to update this PR?

**Comment by Drapersniper** [comment]
Closing due to innactivity.

Please file issues for any of the feature implemented here that are not currently part of filter.

**Pull request closed without merging**
