### PR TITLE
[ModLog] Keep last known username in case's data

### LINKED ISSUE #3443: No username in modlog entries
# Command bugs

#### Command name

hackban, reason

#### What cog is this command from?

Mod, ModLog

#### What were you expecting to happen?

ModLog entry should show a nickname and/or username.

#### What actually happened?

For users that aren't in the server, the ModLog entry shows no information indicating what user the entry is for.

#### How can we reproduce this issue?

Moderate or update a ModLog entry for any user not in the server or not in the bot's cache.

modlog

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Fixes #3443 
This add a `Case.last_known_username` attribute in ModLog so that ModLog doesn't edit the recorded username in case's message with "[Unknown or Deleted User]" after editing the case. ModLog will continue on with not using `bot.fetch_user()`, but if ModLog has recorded last known username then it will be used instead of "[Unknown or Deleted User]"

Better attribute name is welcome :P

### CODE REVIEW

**Comment by Drapersniper** [comment]
Wouldn’t it be better using the user ID instead of storing usernames? Due to discord potentially sending data deletion requests, the bot owner would have 7 days to delete PII and User generates data which usernames fall under, iirc bank leaderboard already does this

**Comment by Jackenmen** [comment]
> Wouldn’t it be better using the user ID instead of storing usernames?

We already store user IDs, this PR is precisely for storing last known username - read the issue linked in PR's description.

**Comment by Drapersniper** [comment]
YEah I know, but my point still apply since usernames are User generated data, which fall under what has to be deleted within 7 days if discord sends the notification to delete a users data

**Comment by Jackenmen** [comment]
As said in the linked issue, it has already been discussed internally in Discord and this had been agreed on (you were taking part in that discussion)

And as far as PII goes, what we actually do is store a part of discord message that was sent by the bot to the modlog channel which is required by the bot to function properly.

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
