### PR TITLE
add custom red url

### PR DESCRIPTION
**Pull request by JordanB-1337**
Switching the invite link for red from a bunch of gibberish to the new discord.gg/red

### CODE REVIEW

**Comment by Twentysix26** [comment]
#591

**Comment by JordanB-1337** [comment]
it said there was no conflict....

**Comment by Twentysix26** [comment]
There's no problem with your PR. I closed it for the same reason I stated in the other one

**Comment by JordanB-1337** [comment]
Oh, I thought you were closing it cause there was already another one. Sorry, I messsed up by only reading one of them.

**Pull request closed without merging**
