### PR TITLE
[Audio] WIP Rewrite

### PR DESCRIPTION
**Pull request by tekulvw**
Hey guys, I figured it was about time we did this so please leave any suggestions/comments down below for Audio 2.0. If you'd like to contribute please fork my repo and contribute to this PR.

### CODE REVIEW

**Comment by Kowlin** [comment]
Just going to drop this here: https://github.com/Cog-Creators/Audio/projects/1

**Comment by Twentysix26** [comment]
[General Audio rewrite](https://trello.com/c/7G31eLks/1-general-audio-rewrite)

**Comment by Canule** [comment]
```class Song:
    def __init__(self, **kwargs):
        self.__dict__ = kwargs
        self.local = kwargs.pop('local', False)
        self.url = kwargs.pop('url', None)
        if self.local and self.url is not None:
            # Make sure ffprobe gets an absolute path.
            work_dir = os.getcwd()
            lt_path = os.path.normpath("data/audio/localtracks")
            track_path = os.path.normpath(self.url)
            f = os.path.join(work_dir, lt_path, track_path)

            # Get audio file info (ffprobe)
            local_tags = AudioFileInfo(f)
            if not local_tags.probe:
                raise InvalidSong()
            if local_tags.title is not None:
                self.title = local_tags.title
            else:
                self.title = kwargs.pop('title', None)
            self.creator = local_tags.artist
            self.album = local_tags.album
            self.webpage_url = None            
            self.id = kwargs.pop('id', url)
            self.duration = float(local_tags.duration)
        else:
            self.title = kwargs.pop('title', None)
            self.album = kwargs.pop('album', None)
            self.id = kwargs.pop('id', None)
            self.webpage_url = kwargs.pop('webpage_url', "")
            self.duration = kwargs.pop('duration', 0)

class AudioFileInfo:
    def __init__(self, path_file, probe_cmd=None):
        self.file = path_file
        if probe_cmd is None:
            self.cmd_payload = ["ffprobe", "-v", "fatal", "-print_format", "json", "-show_format", self.file]
        else:
            self.cmd_payload = probe_cmd
        self.probe = self.ffprobe_audiofile()
        self.format = self.probe.get("format", None)
        
        self.filename = self.format.get("filename", None)
        self.duration = self.format.get("duration", 0)
        self.size = self.format.get("size", None)
        self.tags = self.format.get("tags", None)
        
        self.title = self.tags.get("title", None)
        self.artist = self.tags.get("artist", None)
        self.album = self.tags.get("album", None)

    def ffprobe_audiofile(self):
        sp_err = "-"
        try:
            p = subprocess.Popen(self.cmd_payload, stdout = subprocess.PIPE, stderr = subprocess.STDOUT)
            out, sp_err =  p.communicate()
            ostr = out.decode("utf-8") # str of json
            output = json.loads(ostr) # Make it json
            return output
        except Exception as e:
            log.debug("get_audio_info(): path:{}\n{}\n{}".format(self.file, e, sp_err))
            return False
    @commands.command(pass_context=True, no_pm=True)
    async def song(self, ctx):
        """Info about the current song."""
        server = ctx.message.server
        if not self.is_playing(server):
            await self.bot.say("I'm not playing on this server.")
            return

        song = self._get_queue_nowplaying(server)
        if song:
            if not hasattr(song, "creator"):
                song.creator = None
            if not hasattr(song, "view_count"):
                song.view_count = None
            if not hasattr(song, "uploader"):
                song.uploader = None
            if hasattr(song, "duration"):
                duration = float(song.duration)
                if duration > 0.0:
                    m, s = divmod(duration, 60)
                    dur = "{:.0f}:{:.0f}".format(m, s)
                else:
                    dur = None
            else:
                dur = None
            if not hasattr(song, "album"):
                song.album = None

            msg = ("~~\n~~**Title:** {}\n**Author:** {}\n**Uploader:** {}\n"
                   "**Views:** {}\n**Duration:** {}\n**Album:** {}\n \n<{}> \n".format(
                       song.title, song.creator, song.uploader,
                       song.view_count, dur, song.album, song.webpage_url))
            await self.bot.say(msg.replace("**Author:** None\n", "")
                                  .replace("**Views:** None\n", "")
                                  .replace("**Uploader:** None\n", "")
                                  .replace("**Duration:** None\n", "")
                                  .replace("**Album:** None\n", "")
                                  .replace("\n<None>", ""))
        else:
            await self.bot.say("Darude - Sandstorm.")
```

**Comment by mibby** [comment]
Suggestion for the rework to take into consideration.

* A way to stream youtube videos so it doesn't have to pre-download / cache long videos. (i.e. 3 hour compilations) Currently adding a long video to the playlist takes forever to pre-download with Red-DiscordBot. However, it does not with this bot. https://github.com/Just-Some-Bots/MusicBot

**Comment by Jan200101** [comment]
Streaming Music is a little more difficult when trying to keep a certain quality up.
Not everyone has high speed internet so not everyone can stream it from youtube into discord.

Instead a command to toggle between would be great

**Comment by Twentysix26** [comment]
It will support both ways.

**Comment by Jan200101** [comment]
# Suggestion
simple equalizer

**Comment by Jan200101** [comment]
a progress bar.
The math behind it is simple it would just require getting the song lenght (which is already done in the song command) and how far the song has advanced until the command is executed.
This can be calculated using the lengh of frames the song is long and how many frames the song was playing.

The example for the math behind it would be
`(currentlenght / songlenght) * progressbarwidth`


Now why am I continuing to ramble about this when this is so simple ?
I have no fucking idea

**Comment by tekulvw** [comment]
No longer working on this, Flapjack has taken over audio development for V3.

**Pull request closed without merging**
