### PR TITLE
Audio patch

### PR DESCRIPTION
**Pull request by tekulvw**
- Queue list

### CODE REVIEW

**Comment by tekulvw** [comment]
Hold off on this, I'm gonna fix it up a bit tonight

**Comment by 19lmyers** [comment]
Is this going to be merged??

**Comment by irdumbs** [comment]
we might make a 
`!songlist`
command instead that lists all the songs including ones in the currently playing playlist

should we have `!queue` and `!playlist` also list their respective songs?

**Comment by jonyroda97** [comment]
do the <code>!songlist</code> and the others too

the <code>!queue</code> it's important so that we can see what was queued

Are you adding the names of who have queued the songs to that list? It would be good so that we can punish who puts "bad" music. 

Is there a way to block people to queue songs?

**Comment by tekulvw** [comment]
I don't like any sort of do-all `songlist` command because we'll be bombarding Youtube for no good reason. `!queue` as it is in this PR will show you the currently playing song as well as up to the next 10

**Comment by irdumbs** [comment]
no need to bombard youtube if we store the info on the 1st pass

**Comment by tekulvw** [comment]
The first pass is when we'd bombard youtube. Plus, where would you store the info? For how long? You start entering into the territory of ridiculous memory growth pretty fast.

In other words, trying to get all of the information for every queued song is unnecessary and I am not going to implement it. My only question is do we show the next 5 or 10 songs?

**Comment by jonyroda97** [comment]
5 by default with possibility to ask for an amount of queued songs? (last, only possible to admins?)

**Comment by tekulvw** [comment]
I'm fairly confident I'm just gonna do 5, the use case for more than that is so small I'm just gonna ignore it

**Comment by jonyroda97** [comment]
ok 👌

**Pull request merged**
