### PR TITLE
[Utils] Spoiler Function for Chat Formatting

### PR DESCRIPTION
**Pull request by Kreusada**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes

Re-opened this PR because I deleted the PR branch.

Additional formatting functions including spoilers, snake_spaces and alternating case (ExAmPlE)

I think that spoiler is definitely worthy of being added, but I'm 50/50 on the other two.

### CODE REVIEW

**Comment by Jackenmen** [comment]
My thoughts on this are that `snake()` and `alternatingcase()` functions are too specific and it's quite easy to make yourself and therefore I don't think they should be included in our utils.

`spoiler()` on the other hand seems like a reasonable addition and fits well with the rest of the markdown functions we already have in `.utils.chat_formatting` so I think this PR could get in Red if `snake()` and `alternatingcase()` would be excluded from it.

**Comment by Kreusada** [comment]
Sure. I did think from the start that those other two functions were a bit querky, but its always worth getting an opinion. I'll take those out.

**Review by Jackenmen — CHANGES_REQUESTED** [review]
This PR seems fine, but you're failing the style check. Please run black on your code as explained in [our contributing guidelines](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md#41-setting-up-your-development-environment). If you need any help, feel free to ask on our Discord server.

**Comment by Kreusada** [comment]
Good to go 👍

**Review by Jackenmen — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
