### PR TITLE
Embed pagination fixing (pt2)

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Fixes buggy first embed of paginated help CC: @jack1142

### CODE REVIEW

**Comment by Jackenmen** [comment]
This PR doesn't fully address the problem, output of `[p]permissions` still gives empty page:
image

**Comment by mikeshardmind** [comment]
Note with the above, this particular case isn't actually broken, but it might appear so to users. We may want to reconsider the embed generation strategy more later on.

**Comment by Jackenmen** [comment]
In my opinion, we should split "Commands" fields so that some part of it is shown in first page and some is shown in next page with "Commands (continued)", same as we already do when commands in next pages don't fit in one embed.
chrome_2020-01-04_12-38-39

**Comment by mikeshardmind** [comment]
That's actually not how we're splitting fields currently, though I understand why it can appear that way. This needs a larger overhaul than it will get prior to 3.2 with a more generalized embed paginator than what's currently in use.

**Comment by mikeshardmind** [comment]
Long term we should resize fields, short term, we're not ever having an embed with no fields. This can't go over discord limits, but might exceed some page size settings.

**Review by Kowlin — APPROVED** [review]
Working as intended.

**Pull request merged**
