### PR TITLE
Actual *user* counter

### PR DESCRIPTION
**Pull request by tekulvw**
Members are unique to a server, not to each other. Let's get rid of the duplicates, shall we?

### CODE REVIEW

**Comment by irdumbs** [comment]
can you explain?

**Comment by tekulvw** [comment]
Basically each server has a set of members that belong to that server. Any one given discord user can be a member on multiple servers, and we end up counting them multiple times if we just check the size of `bot.get_all_members()`. However, using set() will make sure each user is only counted once.

**Comment by irdumbs** [comment]
why would get_all_members return a list of all members including duplicates if there's no way to distinguish which server they came from with that call?

**Comment by tekulvw** [comment]
There is a way, because a discord.Member has a `server` attribute. Using `set()` will only keep the members with unique user id's

**Comment by irdumbs** [comment]
i see. ty

**Pull request merged**
