### PR TITLE
[Help] Continuing work and bug-fixes

### LINKED ISSUE #2681: [Core] Exception thrown on help when blocked
# Command bugs

#### Command name

[p]help

#### What cog is this command from?

help.py

#### What were you expecting to happen?

For the bot to say in the invoking channel "I couldn't send the help message to you in DM. Either you blocked me or you disabled DMs in this server."

#### What actually happened?

```
019-05-15 16:23:44] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/commands/help.py", line 513, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/bot.py", line 132, in send_help_for
    return await self._help_formatter.send_help(ctx, help_for)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/commands/help.py", line 95, in send_help
    await self.format_bot_help(ctx)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/commands/help.py", line 394, in format_bot_help
    await self.send_pages(ctx, pages, embed=False)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/commands/help.py", line 500, in send_pages
    await destination.send(page)
  File "/usr/local/lib/python3.7/site-packages/discord/abc.py", line 776, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.7/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user
```

#### How can we reproduce this issue?

Block the bot.
Use the help command.

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [X] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

Includes some of the improvements related to #2667 

  - Fixes a small issue in a previously not-exposed logic path
  - Fixes an issue with denied commands help invocation
  - Adds some global usage settings
  - Fixes #2681 (the command erroring on blocking the bot)

### CODE REVIEW

**Comment by DevilXD** [comment]
Can there be a setting that will mimic what this v2 cog did?: https://cogs.red/cogs/ZeLarpMaster/ZeCogs/help_autodelete/

It let you set a time in seconds after which the help messages, along with the help command message that triggered the help response itself, would be deleted. This really helps to keep the chat clear of any unnecessary messages.

**Comment by mikeshardmind** [comment]
> 
> 
> Can there be a setting that will mimic what this v2 cog did?: https://cogs.red/cogs/ZeLarpMaster/ZeCogs/help_autodelete/
> 
> It let you set a time in seconds after which the help messages, along with the help command message that triggered the help response itself, would be deleted. This really helps to keep the chat clear of any unnecessary messages.

Not in this particular PR, but I'll add it to the checklist issue.

**Review by Kowlin — DISMISSED** [review]

**Comment by NeuroAssassin** [comment]
Thought I’d leave a comment about this here: So earlier, I was using help on my bot and it for some reason was returning the disabled message when I was using it.  However, it worked fine for calling help on the ping command.  Also, I was getting help on a category, not a command, so I knew that the command I was calling wasn’t disabled.  I was able to solve this by disabling then re-enabling help, but thought it was pretty weird.  I thought it was my editing red, until later when I was helping someone in the support channel.  They also had been receiving this, but with every command.  Help wasn’t disabled; they tried restarting the bot and doing what worked for me earlier; nothing.  They also told us that it was only in one guild it was doing that, the others were fine.  They said they had not edited red at all.  I’m not sure what could be causing this, so I’m dropping it here for you to know.

**Review by Kowlin — APPROVED** [review]

**Comment by wereii** [comment]
What @NeuroAssassin described here is what happens ~if your server has disabled DM.~ Interesting enough this happens only for me as the bot owner because I receive every possible help and according to [this line](https://github.com/Cog-Creators/Red-DiscordBot/blob/ee293876d90cfa6ba180fe3dbceaa784a8859861/redbot/core/commands/help.py#L582) it the tries to send DM once the output is too big. 

~Enabling DMs server wide works, but we don't want that here.~ If this fails, bot sends the error DM message set in #2681 but it should also offer the possibility to just drop the message in the current channel. 
>"...you blocked me or you disabled DMs in this server. You can :OK: this message to receive the help in this channel."

Btw ~if at least one server with you and the bot has DMs enabled~ If you have DMs enabled on at least one server you share with the bot this won't happen. 

EDIT: words
EDIT2: After some digging. Disabling DMs from a server (Right click on server, Privacy settings) is user specific. Basically there is some smelly logic from discord that you can't "favorite" or "friend" bots so they could send you DMs without actually sharing any open DM server. Also If I had a lot of cogs with lot of public commands every user calling [p]help with DMs disabled everywhere will experience this issue.

**Pull request merged**
