### PR TITLE
New Casino Games

### PR DESCRIPTION
**Pull request by franc-ist**
# **_WARNING**_

`apparently people are coming here and using this PR instead of their original economy.
editing / replacing / removing random files is not recommended.
You'll be giving us a hard time in the support channel if you do this.
We will most likely not help you with your problems if you edit / replace / remove random files in Red`

New casino games (courtesy of Spriter137), as well as some formatting cleanups.
# What's included:
- New leaderboard
- Coin flip gamblling
- Dice roll gambling
- Bank heist
- All-in
# What has been left out
- Blackjack - was deemed too spammy in it's current state. Would have been rate-limited on large servers.

### CODE REVIEW

**Comment by Skordy** [comment]
Nice Fishy. :D

**Comment by franc-ist** [comment]
@Skordy wasn't mine lol. i just made it look nicer

**Comment by ddday** [comment]
Has the bank wipeout bug been fixed?

**Comment by Skordy** [comment]
@FishyFing I know, that's why I was saying nice. :P

**Comment by tekulvw** [comment]
Why did you modify register? And why didn't you include that in the description?

**Comment by franc-ist** [comment]
@tekulvw register isnt modified. the bot just gets an account, for heist to work, which slowly increases over time

**Comment by franc-ist** [comment]
ignore this

**Comment by irdumbs** [comment]
apparently people are coming here and using this PR instead of their original economy.
editing / replacing / removing random files is not recommended.
You'll be giving us a hard time in the support channel if you do this.
We will most likely not help you with your problems if you edit / replace / remove random files in Red

**Pull request closed without merging**
