### PR TITLE
[Config V3] Rewrite (already?)

### PR DESCRIPTION
**Pull request by tekulvw**
Front facing features shouldn't change a whole lot but the backend of config is getting totally revamped. I'll list new features here as they come to fruition.

### New Features
- Nested defaults!
  * `conf.register_global(foo__bar=True)` and to get that data `conf.foo.bar()`
- `.set()` now does not require the field name
  * `config.set("enabled", True)` is now `config.enabled.set(True)`
  * As a result, if you're trying to do dynamic attribute setting you will need to use a new method: `config.set_attr("some_field", True)`
  * Also, to maintain consistency, `conf.get('foo', False)` is now `conf.get_attr('foo', False)`
- Member features! You now access all the guilds in member data as well as all members in a given guild.
  * All guilds: `conf.member(member_obj).all_guilds()` returns a dict of servers -> members -> data
  * All members same guild: `conf.member(member_obj).all()` returns a dict of members -> data

### To Do
- [x] Implement #812 
- [x] Write some more tests to cover new functionality

### Currently Fixes
- #868 
- #810
- #812

### CODE REVIEW

**Comment by tekulvw** [comment]
Okay so for those of you who have used config before, does anyone deem the `.get()` function necessary?

**Comment by palmtree5** [comment]
`.get()` is necessary if you don't force registration (which the first case that comes to mind of not forcing registration is the modlog part of my rewrite of mod because of `[p]modset cases` and having an interface available for adding casetypes which means that its key where its enabled status is located would not necessarily be registered automatically and would instead be added after the fact)

**Comment by mikeshardmind** [comment]
I've used config and migrated about half my repo over to v3. 
Using the alpha (this is pretty stable for an alpha) to manage temp channels, formboxes, and a few other things.  `self.conf.guild(ctx.guild).somekeyhere` already retrieves the key (as long as it exists) , and you provide a way to register defaults already, so I don't see the use case for `.get()`

Edit:
@palmtree5 is right, I've actually just forgotten how I worked around that detail by abstracting everything a level up, storing temporary channnel settings as owned by the server, not the channels themselves, alongside forcing registration for a few things.

**Comment by tekulvw** [comment]
To use your example, `self.conf.guild(ctx.guild).somekeyhere()` works both with and without registering `somekeyhere`. The current functionality forces `somekeyhere` to have a default of `None` if you don't register it and you can pass a different default (such as `self.conf.guild(ctx.guild).somekeyhere(True)`) into the getter function if you wish.

**Comment by mikeshardmind** [comment]
If that's already current functionality (was it before? ....) then getting rid of it doesn't seem awful

**Comment by tekulvw** [comment]
It's always been that way, I was asked to specifically include the `.get()` function as an alternative.

**Comment by mikeshardmind** [comment]
Then .get() is redundant

**Comment by QingyuChai** [comment]
But what if what I'm looking for in the config is a parameter of the command?
Example:
```python
async def test(self, ctx, foo):
    # I can't do self.conf.guild(ctx.guild).foo()
    # In this case I would need get()
    self.conf.guild(ctx.guild).get(foo)

```

**Comment by Twentysix26** [comment]
I'd argue that
`self.conf.guild(ctx.guild).somekeyhere(True)`
is significantly less clear and immediate than
`self.conf.guild(ctx.guild).get("somekeyhere", True)`
to anyone who has not source dived into (or developed) Config.  
Not to mention that it would force the use of `getattr` if the key is dynamic.

**Comment by tekulvw** [comment]
@QingyuChai You bring up a very good point, dynamic attribute access is impossible without `.get()` or using `getattr()` and the use case for that is so large I'm going to add it back in.

@Twentysix26 My argument is that while not using `.get()` may be unclear at someone's first glance, after reading and learning how config works (with enough documentation), using `.get()` becomes more of a hassle because than directly accessing the attribute. However, the point is now moot.

**Review by Kowlin — APPROVED** [review]
Code looks good from my end.

**Comment by tekulvw** [comment]
@QingyuChai @Twentysix26 In order to support dynamic attributes and to make things explicitly clear I had to add a new method to set the value of dynamic attributes. You'll have to use `config.set_attr("dynamic_attr", value)` instead of `config.set()` because now `.set()` only takes 1 argument.

**Comment by tekulvw** [comment]
~~Active development is complete, ready for review/testing.~~

~~Making a few changes.~~

Ready again for review.

**Review by palmtree5 — APPROVED** [review]
Looks good to me too

**Review by Twentysix26 — APPROVED** [review]

**Pull request merged**
