### PR TITLE
Replace verbose matching w/ simple \w RegEx

### PR DESCRIPTION
**Pull request by JodanJodan**

### CODE REVIEW

**Comment by tekulvw** [comment]
Except your regex is too permissive. It allows people to put `/` and `.` in playlist names which is a security problem.

**Comment by Twentysix26** [comment]
Unneeded.

**Comment by JodanJodan** [comment]
@tekulvw `\w` is identical to `[a-zA-Z0-9_]`, so I'm not sure why you believe `/` and `.` are included. This is basic RegEx.

image

**Comment by tekulvw** [comment]
Okay, my bad, I was thinking `\w` was the non-whitespace character code.

Please explain to me how regex is "simpler."

This PR is still going to stay closed because it provides no real benefit and V2 audio is pretty much locked in prep for V3.

**Pull request closed without merging**
