### PR TITLE
Fix for modset reinvite

### PR DESCRIPTION
**Pull request by Kowlin**
Code fix by @aikaterna, added as an co-author

### Type

- [x] Bugfix
### Description of the changes

This PR fixes an issue with ``modset reinvite`` not functioning. Traceback for old error below.

```
Exception in command 'modset reinvite'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/mod/mod.py", line 320, in reinvite
    f"{ctx.prefix}unban"
KeyError: 'command'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/commands/commands.py", line 409, in invoke
    await super().invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 1024, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 614, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'command'
```

### CODE REVIEW

**Comment by mikeshardmind** [comment]
if this issue exists on rc2, this should be rebased onto (and PR made to) `V3/release/3.0.0` to allow it to be fixed prior to 3.0.0 stable.

**Comment by Kowlin** [comment]
Darn, you're right. Will move the branch over and hope it doesn't break stuff.

**Comment by mikeshardmind** [comment]
Definitely needs to be rebased.

**Comment by Kowlin** [comment]
Absolutely... *sigh*

**Comment by Kowlin** [comment]
Ye I cannot be bothered, just gonna make a new PR from the correct branch.

**Pull request closed without merging**
