### PR TITLE
[OKAY MAYBE MERGE] Multivoice (rewrite)

### PR DESCRIPTION
**Pull request by tekulvw**
Leaving this here so we can log discussion about multivoice audio design
## Todo:

**Priority:**
- [x] Downloading tracks
- [x] Play
- [x] Stop
- [x] Queue
- [x] Playlist functionality
- [x] Keep track of players by tacking them onto voice clients as `player` attributes
  - thanks Danny for not using `__slots__`!
- [x] Local files...

**Definite:**
- [ ] queue-playlist integration
  - [x] songs put in the queue will be played next after the current song finishes. once the queue is empty, playlist resumes.
  - [ ] when a queue is playing, adding a playlist puts it at the end of the current songs being played.  
- [x] playing on a repeating "current" playlist
- [ ] adding/removing songs to current
- [ ] adding/removing playlists to current
- [ ] playlist management
  - saving current songlist as playlist
  - adding/removing songs/playlists to x playlist
- [ ] queue management
  - removing x song from queue
  - moving songs around in the queue
- [ ] add sfx by link
- [x] disable loop without !stop
- [ ] When adding a song, don't just say "a song has been put in the queue" and don't just stick "a song" in the queue. Put in the search string, and then update it once the song name/url is found.
- [ ] Display current song duration/time till added song
  - 1:40 [███████...............] 3:21 <- updating every time !song is used
- [x] Fix the reload bug in #155 
- [x] Fix the bug in #153 
- [x] Really redo how audio handles multiple servers
- [ ] asyncio bug in #132
- [x] Make sure that mobile/desktop links work as in #80 
- [ ] Separate youtube search command #79 
- [ ] Make bot auto-disconnect after x seconds
- [ ] Make the bot display the file name of local tracks, instead of the path
  - In queue, and actually show in currently playing
- [ ] Settable skip percentage
  - settable % votes needed to exceed to skip. 50 == majority
- [ ] Make the bot display the file name of local tracks, instead of the path
  - In queue, and actually show in currently playing
- [x] Volume changes
  - `!audioset volume` by itself displays the current volume
  - range changed from 0-1 to 0-100

**Not so definite:**
- [x] Remove/rethink !play. Just have !queue functionality. give mods/admins/owner some way to override instead. maybe just through moving songs in queue
- [ ] Radio solutions
  - icecast/shoutcast/last.fm https://github.com/Twentysix26/Red-DiscordBot/issues/179
  - pandora/spotify
- [x] Discord.py dependent fixes
  - Join multiple voice channels (when discord.py supports)
  - remove song from status - stick into channel details?
- [ ] Features specified by #52 
- [ ] Features specified by #135 
- [ ] Features specified by #180 
- [x] Queue/Playlist integration.
  - adding a song to the queue doesn't remove the playlist.
  - once the current song finishes, the queue plays
  - the queue must finish before playlist resumes.
  - if a playlist is started while a queue is playing, the queue must finish before the playlist will start.
- [ ] Link resolving
  - `!queue willow` --> [SEARCH:]willow has been put into the queue by irdumb#1229
  - after giving it some time to resolve,
    - `!queue` --> Videos in queue: 1. Jasmine Thompson - Willow (Lyrics)

### CODE REVIEW

**Comment by franc-ist** [comment]
```
[8:01 AM] Danny said:
The change is not too complicated.
client.voice -> client.voice_clients
but you can query it via different ways

like Server.voice_client or Client.voice_client_in(server)
```

**Comment by tekulvw** [comment]
On the issue of leaving the voice channel after audio has stopped, I'm voting to wait around for ~3 minutes before auto leaving

**Comment by tekulvw** [comment]
[1:05 AM] Will: Action manager recieves actions to be put into a priority queue and executes the highest priority item each time it loops. It passes the player and the queue to the Action item it runs for the item to do whatever it wants.
[1:05 AM] Will: Queue manager simply monitors the currently playing thing and starts the next one if there are things in the song queue
[1:05 AM] Will: Action manager runs evey 0.5 sec
[1:05 AM] Will: Queue manager only does things at song change
[1:06 AM] Will: using !pause would put a Pause action into the Action manager at high high priority
[1:06 AM] Will: then when it get's passed the player it simply calls pause

**Comment by irdumbs** [comment]
I think it might be more intuitive if we refer to the currently playing list of songs as the **songlist**,
lists of songs we stick in there as **playlists**,
and the list of one-time-playing songs as the **queue**
:3

**Comment by franc-ist** [comment]
Problems shown in #234

**Comment by Senpoii** [comment]
Any updates on possible m3u/pls support? It's been over a year

**Comment by tekulvw** [comment]
Man you're looking in the wrong place to comment, see #623. To directly answer your question, m3u/playlist support will not be in v2 but will be in v3 when it comes out.

**Pull request merged**
