### PR TITLE
Add setting for credits given on registering account

### PR DESCRIPTION
**Pull request by palmtree5**
Adds in a new command along with the necessary code to allow someone with the appropriate permissions to set the balance to be given on account creation via [p]bank register

### CODE REVIEW

**Review by Kowlin — COMMENTED** [review]
Code looks and runs fine for me, however you could add the setting to `economyset`'s output

**Comment by palmtree5** [comment]
The setting appears to be in `economyset`'s output for me

image

**Comment by Kowlin** [comment]
Ahaha, I'm blind ;)

**Review by SapphicCode — APPROVED** [review]

**Review by YeahImRose — CHANGES_REQUESTED** [review]
Line 3: from cogs.utils.dataIO import dataIO
Line 198: self.settings = dataIO.load_json("data/economy/settings.json")
Line 464/472/480/488/496/504: dataIO.save_json("data/economy/settings.json", self.settings)
Line 534/539: if not dataIO.is_valid_json(f):
Line 536/541: dataIO.save_json(f, {})

**Review by tekulvw — CHANGES_REQUESTED** [review]
Needs to be redone for post economy rewrite changes

**Comment by palmtree5** [comment]
Superseded by #472

**Pull request closed without merging**
