### PR TITLE
[V3 pip WIP] Package bot and begin writing setup scripts

### PR DESCRIPTION
**Pull request by tekulvw**
More info to come soon.

To install the bot using pip, for now you must use the following:

`pip install --process-dependency-links -U git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop`

### CODE REVIEW

**Comment by tekulvw** [comment]
As of now the latest version on pypi is representative of the "Remove double sentry opt in" commit.

**Comment by tekulvw** [comment]
Now that we have tests passing again...from here on out we will NOT be uploading dev versions to pypi, it simply isn't designed for that.

~~You will need to git clone/pull/whatever the latest copy of this repo and then `pip install --process-dependency-links -e .` to install the bot.~~

I lied, you'll need to `pip install --process-dependency-links -U git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop` to update/install the bot AFTER this is merged.

To install RIGHT THIS MOMENT: `pip install --process-dependency-links -U git+https://github.com/tekulvw/Red-DiscordBot@V3/better_refactor_setup`

Also I'll be fixing core cog loading in the next few days.

**Comment by palmtree5** [comment]
For reference, the `--process-dependency-links` flag is needed because pip doesn't automatically install from external sources unless that flag is present

**Review by palmtree5 — DISMISSED** [review]
Looks good to me. Cogs are loading too

**Review by palmtree5 — APPROVED** [review]

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
