### PR TITLE
Merge V3/feature/audio into V3/develop (a.k.a. audio refactor)

### LINKED ISSUE #3353: [Audio] Summon command graceful errorhandling
# Command bugs

#### Command name

summon

#### What cog is this command from?

Audio

#### What were you expecting to happen?

The bot to inform the user what happened.

#### What actually happened?

Traceback error.

```py
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7680, in summon
    can_skip = await self._can_instaskip(ctx, ctx.author)
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7527, in _can_instaskip
    if await self._channel_check(ctx):
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7909, in _channel_check
    player = lavalink.get_player(ctx.guild.id)
  File "/data/venv/lib/python3.8/site-packages/lavalink/lavalink.py", line 110, in get_player
    node_ = node.get_node(guild_id)
  File "/data/venv/lib/python3.8/site-packages/lavalink/node.py", line 365, in get_node
    raise IndexError("No nodes found.")
IndexError: No nodes found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: No nodes found.
```

#### How can we reproduce this issue?

1. Have lavalink down (easiest with external lavalink)
2. Use summon

### LINKED ISSUE #3389: [Audio] Audio doesn't gracefully errors on failed startup
```
[2020-01-16 23:02:43] [ERROR] red: AttributeError
Traceback (most recent call last):
  File "c:\windows\system32\redenv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\windows\system32\redenv\lib\site-packages\redbot\cogs\audio\audio.py", line 2738, in play
    elif not await is_allowed(ctx.guild, f"{query}", query_obj=query):
  File "c:\windows\system32\redenv\lib\site-packages\redbot\cogs\audio\utils.py", line 90, in is_allowed
    global_whitelist = set(await _config.url_keyword_whitelist())
AttributeError: 'NoneType' object has no attribute 'url_keyword_whitelist'
```

### LINKED ISSUE #3467: [Audio] Local tracks with special characters in path wont return a value in all cases
# Command bugs

#### Command name

[p]local folder
[p]local play

#### What cog is this command from?
audio

#### What were you expecting to happen?

trying to play a folder with spaces in path such as:
https://puu.sh/F4B4A/9070d830aa.png
and selecting 2

should result in playing all songs inside that folder

#### What actually happened?
Nothing found message.
http://puu.sh/F4B5s/45eb04af34.png

#### How can we reproduce this issue?

make (symlink) folder. add another folder inside it with a space in name. "redbot test" and try to play it.

### LINKED ISSUE #3471: [Audio] API tutorials should be made to work in DMs
# Command bugs

#### Command name

`[p]audioset` api commands, there may be others in core but I forget what all else use api keys if any

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Dump the tutorial on setting API keys

#### What actually happened?

> That command is not available in DMs.

Since API keys should be set in DMs, this is a bit problematic since users either have to constantly switch between DMs and a guild channel or they end up just using the commands in a guild, which can be a security concern.

#### How can we reproduce this issue?

Use any of the audioset api commands in DMs

### LINKED ISSUE #3485: [Audio] Disconnect while others are listening
# Command bugs

#### Command name

[p]disconnect

#### What cog is this command from?

Audio

#### What were you expecting to happen?

For the bot to disconnect.

#### What actually happened?

The bot said "There are other people listening to music." as if DJ mode or voteskip was activated.

#### How can we reproduce this issue?

Join a channel
Have a friend join the channel (not a privledged user on the bot)
Play a song.
Have the friend try to use [p]disconnect

### LINKED ISSUE #3506: [Audio] inadequate playlist update with local cache enabled
# Other bugs

#### What were you trying to do?

Update local playlist from remote (youtube)

#### What were you expecting to happen?

Update playlist with adding new songs, removal of nonexistent in remote playlist

#### What actually happened?

Random songs was removed, when they are still available on remote playlist.

#### How can we reproduce this issue?

1. use Audio with disabled local cache
2. `playlist save` remote playlist ([i.e.](https://www.youtube.com/playlist?list=PLP08gCf9c_7OITwu6VfPSMkwUsg0RGMDq))
3. enable local cache
4. `playlist update` saved playlist
5. random songs get removed

### LINKED ISSUE #3552: [Audio] Config schema 2 migration incorrectly recorded as upgraded to _SCHEMA_VERSION = 3
When the config schema 2 upgrade happens, at the end, it is recorded as upgraded to _SCHEMA_VERSION (currently 3). This is premature, as the schema 3 upgrade has not happened yet. It should be recorded as upgraded only to schema 2 here.

https://github.com/Cog-Creators/Red-DiscordBot/blob/86549248699d1bcd5294b57805d49b1fb3d1a660/redbot/cogs/audio/audio.py#L268

### LINKED ISSUE #3712: [Audio] [p]genre fails if you disconnect while menu is open
# Command bugs

#### Command name

[p]genre

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Maybe close the menu if use disconnect command, or just don't error.

#### What actually happened?

```py
Traceback (most recent call last):
  File "/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/redbot/cogs/audio/audio.py", line 3214, in genre
    return await self._get_spotify_tracks(ctx, query)
  File "/redbot/cogs/audio/audio.py", line 3368, in _get_spotify_tracks
    player = lavalink.get_player(ctx.guild.id)
  File "/lavalink/lavalink.py", line 111, in get_player
    return node_.player_manager.get_player(guild_id)
  File "/lavalink/player_manager.py", line 412, in get_player
    raise KeyError("No such player for that guild.")
KeyError: 'No such player for that guild.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'No such player for that guild.'
```

#### How can we reproduce this issue?

1. Use `[p]genre`
2. Use `[p]disconnect`
3. Click on one of the reactions of the genre command.

### LINKED ISSUE #3715: Error in command 'play'. Check your console or logs for details.
# Command bugs

#### Command name

!play <url>

#### What cog is this command from?

AUDIO

#### What were you expecting to happen?

I expected a song to play in the voice channel

#### What actually happened?

The bot connects to it but nothing plays.

#### How can we reproduce this issue?

- !play <url>
- nothing plays

#### LOGS

Exception in command 'play'
Traceback (most recent call last):
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(args, **kwargs)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 2826, in play
    await self._enqueue_tracks(ctx, query)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 3516, in _enqueue_tracks
    result, called_api = await self.music_cache.lavalink_query(ctx, player, query)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/apis.py", line 769, in lavalink_query
    results = await player.load_tracks(query)
  File "/home/tom/redenv/lib/python3.8/site-packages/lavalink/rest_api.py", line 319, in load_tracks
    data = await self._get(url)
  File "/home/tom/redenv/lib/python3.8/site-packages/lavalink/rest_api.py", line 286, in _get
    async with self._session.get(url, headers=self._headers) as resp:
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in aenter
    self._resp = await self._coro
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in exit
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(ctx.args, **ctx.kwargs)
[1:59 PM] xTomR: File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError:

### LINKED ISSUE #3728: [Audio] - Playlist command error
# Command bugs

#### Command name

playlist list

#### What cog is this command from?

Audio

#### What were you expecting to happen?

For the command to show me playlist list 1.

#### What actually happened?

```py
Traceback (most recent call last):
  File "/home/bot/botenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bot/botenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 4937, in _playlist_list
    playlists = await get_all_playlist(scope, self.bot, guild, author, specified_user)
  File "/home/bot/botenv/lib/python3.8/site-packages/redbot/cogs/audio/playlists.py", line 475, in get_all_playlist
    scope_standard, scope_id = _prepare_config_scope(scope, author, guild)
  File "/home/bot/botenv/lib/python3.8/site-packages/redbot/cogs/audio/playlists.py", line 86, in _prepare_config_scope
    scope = standardize_scope(scope)
  File "/home/bot/botenv/lib/python3.8/site-packages/redbot/cogs/audio/playlists.py", line 62, in standardize_scope
    scope = scope.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bot/botenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bot/botenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/bot/botenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/bot/botenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/bot/botenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'upper'
```

not sure

### PR DESCRIPTION
**Pull request by Drapersniper**
This is the PR to be merged into V3/develop once The refactor is completed.
This one will contains all changes that went into V3/feature/audio.

For Easier Review (In order they were should be reviewed/merged):

Audio Refactor: Part 1 - APIs #3363
Audio Refactor: Part 2 - Cog Class #3424
V3/feature/audio/3 #3500 - (Some small fixed + Playlist scope fix and playlist logic improvement)
V3/feature/audio/fixes/3485 #3502 - Fixes #3485 and has some enhancements to the usage of `can_skip`
V3/feature/audio/fixes/3353 #3503 - Fixes #3353
V3 feature audio 4 #3518 - Minor fixes that have no issues for + global daily playlist
V3 feature audio lyrics #3519 - Ads a feature that allow prioratising videos with lyrics when matching tracks.
V3 feature audio - clean up #3528 - A LOT of fixes

Already reviewed:
#3251 - Allow `[p]playlist upload` to have the file upload with the command 
#3201 - Allow Removing tracks from queue by URL

For Myself: 
#3505 - changes need to be in here at some point (Only Missing Persistent Queue and Global cache API)

### CODE REVIEW

**Review by mikeshardmind — CHANGES_REQUESTED** [review]
I'm preventing any accidents with this review...

**Comment by Drapersniper** [comment]
# Needs review
Audio Refactor: Part 1 - APIs #3363
Audio Refactor: Part 2 - Cog Class #3424
V3/feature/audio/3 #3500 - (Some small fixed + Playlist scope fix and playlist logic improvement)
V3/feature/audio/fixes/3485 #3502 - Fixes #3485 and has some enhancements to the usage of can_skip
V3/feature/audio/fixes/3353 #3503 - Fixes #3353
V3 feature audio 4 #3518 - Minor fixes that have no issues for + global daily playlist
V3 feature audio lyrics #3519 - Ads a feature that allow prioratising videos with lyrics when matching tracks.
V3 feature audio - clean up #3528 - A LOT of fixes

# Already reviewed:
#3251 - Allow [p]playlist upload to have the file upload with the command
#3201 - Allow Removing tracks from queue by URL

## What needs done here.

Please complete the functional test in #3528, this will make your life a lot easier.

once you complete the review on that PR merge it into the Feature branch, it will automatically update this PR and this PR will be ready to be merged into V3/develop after the conflicts are resolved.

For sanity sake i suggest the audio freeze continues until this PR is merged as conflicts here will become more and more difficult to resolve.

**Review by Jackenmen — CHANGES_REQUESTED** [review]
Review for accident prevention :P

**Review by Jackenmen — APPROVED** [review]
One small step for a... Ah, let's just merge it already.

**Comment by Drapersniper** [comment]
For future reference: if audio burns .. Blame @jack1142  he approved and merged

**Pull request merged**
