### PR TITLE
[Core] Added [p]contact and [p]dm

### PR DESCRIPTION
**Pull request by Twentysix26**
I added [p]contact, which is unchanged from v2, ~~and a syntax to DM users through Red.~~  
~~The syntax is `dm:<id> <text>`, it's owner-only, only works in DM with Red and you receive the full string to copy paste when you get `[p]contact`ed
I'm actually not sure if I should add a normal command for it instead~~
Let me know what you think 👌 
EDIT: Syntax turned to [p]dm

### CODE REVIEW

**Comment by tekulvw** [comment]
To move my thoughts from discord onto here: I think that having a normal command (dm/pm/whisper whatever you want to call it) that simply takes two args, a user ID and a message, is a way simpler solution to this problem. Especially because contact already gives you the user id.

**Comment by Twentysix26** [comment]
Yeah I'm of the same opinion now, this is just the result of various things I tried and I eventually got too deep into it x)
I'll turn it into a command later

**Comment by Twentysix26** [comment]
Should be good to go

**Review by Kowlin — APPROVED** [review]
Looks good from my view.

**Review by tekulvw — APPROVED** [review]

**Pull request merged**
