### PR TITLE
[Audio] Move playlist from the Config Driver to their own SQL table

### PR DESCRIPTION
**Pull request by Drapersniper**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Okay so this should in theory significantly improve audio performance across the border for folks that use the playlist function

@PredaaA using Mart on dev which has #2921 (which significantly reduces JSON size went from 50+MB prior to #2921 to 18.6MB prior to this PR)

With this PR his audio config went from 18.6MB to 287.12 KB... (and say we want to also migrate the EQUALIZER scope to an SQL table ... his config was reduced to 42.97 KB) which should significantly reduce write times and overall make audio commands feel speedier.

### CODE REVIEW

**Comment by Drapersniper** [comment]
Note: This was supposed to be a draft ... as still pending some testing ... I'll update it when its ready for a review

**Comment by Drapersniper** [comment]
This will keep failing until #3192 is merged due to the apsw dep

**Comment by mikeshardmind** [comment]
Note for future improvement.

Changes here are a drastic improvement in performance, and once ready for use, they should be merged without waiting on adapting everything for the below.

However, long term a schema like the below should be used

```sql
CREATE TABLE IF NOT EXISTS playlists(
  playlist_id INTEGER PRIMARY KEY,
  playlist_name TEXT NOT NULL,
  scope_type TEXT NOT NULL,  -- INTEGER preferable*
  scope_id INTEGER NOT NULL, -- author or guild id
  owner_id INTEGER NOT NULL, -- Used to determine creator for UI
);

CREATE TABLE IF NOT EXISTS tracks(
  track_id INTEGER PRIMARY KEY,
  track_data JSON
);

CREATE TABLE IF NOT EXISTS track_relations(
  track_id INTEGER REFERENCES(tracks.track_id) ON DELETE CASCADE,
  playlist_id REFERENCES(playlists.playlist_id) ON DELETE CASCADE,
  track_number INTEGER, -- for playlist ordering
  PRIMARY KEY(track_id, playlist_id)
);
```

With queries changing to something such as:

```sql
-- fetch playlist tracks
SELECT tracks.track_data, track_relations.track_number
FROM tracks 
  INNER JOIN track_relations
  ON tracks.track_id=tracks_relations.track_id
WHERE track_relations.playlist_id = ?;
```

Search query gets a little more complicated, but won't be used as often and will still be faster:

```sql
-- search playlists by name
SELECT
  playlists.playlist_name,
  playlists.owner_id,
  playlists.playlist_id,
  COUNT(track_relations.track_id)
FROM playlists 
  LEFT INNER JOIN track_relations ON playlists.playlist_id=track_relations.playlist_id
GROUP BY playlists.playlist_id
-- query doesn't have to be provided
WHERE
  playlists.scope_id = :scope_id 
  AND playlists.scope_type = :scope_type
  AND playlists.playlist_name LIKE "%" || COALESCE(:query, "") || "%";
```

**Comment by Drapersniper** [comment]
Do not merge this one ... Merge #3205

**Comment by Drapersniper** [comment]
Will setup a CPR for all of this so itsd easier to follow ... less likely to fuck up)

**Pull request closed without merging**
