### PR TITLE
[V3 Mod] Userinfo past nicks/names

### PR DESCRIPTION
**Pull request by mikeshardmind**
Prevents trying to do a string replace on a NoneType

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### CODE REVIEW

**Comment by Twentysix26** [comment]
I was curious to see how a None would even end up in there, so I checked how the past names / nicknames tracking works. It seems that the past names assignation is wrong (it's adding the nickname instead of the name) and with this PR you're attempting to fix the symptom rather than the root issue
https://github.com/Cog-Creators/Red-DiscordBot/blob/0298b538031f1c922bf00fd29d8c12ee43faf1d2/redbot/cogs/mod/mod.py#L1606-L1613

**Comment by palmtree5** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/blob/1e60d1c2652ea432cfc645c93bcc35fa08afb441/redbot/cogs/mod/mod.py#L1362-1380
Really weird, it was fine at this commit which means there must've been a regression somewhere

**Comment by mikeshardmind** [comment]
I agree fixing the cause is a good thing too, but the fact is we have people with `None` entries in there with this erroring for them. I'll update fixing that as well.

**Comment by palmtree5** [comment]
Regression appears to have occurred in https://github.com/Cog-Creators/Red-DiscordBot/commit/15ea5440a3d51397b83697fcfcbc69fb4c3dc95d#diff-4bbe83517d8a95d2e6e0e46fe9f7b809

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
