### PR TITLE
Forcefully shutdown RPC to prevent hangs

### LINKED ISSUE #6391: RPC server shutdown hangs the bot shutdown process
### What Red version are you using?

3.5.9

### What were you trying to do?

Shutdown the bot

### What did you expect to happen?

For the bot to shut down

### What actually happened?

The shutdown process will hang during `await self._runner.cleanup()` if there is an active RPC connection

### How can we reproduce this error?

1. Have RPC enabled
2. Have AAA3A's Dashboard cog running (I suspect the same will happen with any other service talking via RPC)
3. Restart or Shutdown the bot
4. Bot will hang during the process and continue to hang until the Dashboard's web service is restarted

### Anything else?

So a possible workaround is to set the `shutdown_timeout` on [Line 96](https://github.com/Cog-Creators/Red-DiscordBot/blob/4242a7adf22b5b128fec26deb7eb3959ce2bba82/redbot/core/_rpc.py#L96) to be something other than 0 so the connections get forcibly closed if they don't gracefully close. Or, we can push the issue back to @AAA3A-AAA3A to see if something on his web service side is causing the connection to remain always open. Looks to be possibly related to #4134

### PR DESCRIPTION
**Pull request by Kowlin**
### Description of the changes

Fixed #6391.

### Have the changes in this PR been tested?

No, but it should just work. If not, its aiohttp's fault.

### CODE REVIEW

**Review by yamikaitou — COMMENTED** [review]
Tested and it works as expected (shutdown process continues after the 120 second timeout)

```
Jul 19 00:02:56 redbot python[737041]: [2024-07-19 00:02:56] [INFO] red.Audio.WS.LLNode: Shutdown Lavalink WS.
Jul 19 00:02:56 redbot python[737041]: [2024-07-19 00:02:56] [INFO] red.AAA3A-cogs.Dashboard: Unloading cog...
Jul 19 00:04:57 redbot python[737041]: [2024-07-19 00:04:57] [INFO] red.main: Shutting down with exit code: 26 (RESTART)
Jul 19 00:04:57 redbot python[737041]: [2024-07-19 00:04:57] [INFO] red.main: Please wait, cleaning up a bit more
Jul 19 00:05:00 redbot systemd[1]: itazura.service: Main process exited, code=exited, status=26/n/a
```

**Comment by AAA3A-AAA3A** [comment]
It works for me too! I was going to raise the subject again in #advanced-coding, fearing a problem in the way my Dashboard uses to create the websocket, but I've found this PR. ;P Thanks @Kowlin! 😃

**Comment by BenCos17** [comment]
seems to work for me also

**Review by Jackenmen — APPROVED** [review]
We should probably look into graceful shutdown at some point, see https://github.com/Cog-Creators/Red-DiscordBot/pull/4134#pullrequestreview-458439461

For now, let's just go with this, thanks!

**Pull request merged**
