### PR TITLE
[Downloader] Remove Repo Folders on Repo Removal

### PR DESCRIPTION
**Pull request by Aioxas**
Issues addressed:
* Build-up of stale repo folders when deleting them.

### CODE REVIEW

**Comment by Aioxas** [comment]
Rebased version of #415

**Comment by aikaterna** [comment]
Been using this as a separate command on my bot for about 2+ months now. Has been working great.

**Comment by aikaterna** [comment]
Testing this version this evening, removing a repo gives this error:
```
[09/12/2016 23:47] ERROR red on_command_error 249: Exception in command 'cog repo remove'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'data/downloader/aikaterna\\.git
\\objects\\0e\\85fde709c64136fc12cffad7d9764c0783b191'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\downloader.py", line 117, in _repo_del
    shutil.rmtree(cog, onerror=self.del_rw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
TypeError: del_rw() takes 3 positional arguments but 4 were given
```

**Comment by Kowlin** [comment]
Seems its a permission error, ``PermissionError: [WinError 5] Access is denied: 'data/downloader/aikaterna\\.git\\objects\\0e\\85fde709c64136fc12cffad7d9764c0783b191'``. I'll look into this on how to solve this.

**Comment by Aioxas** [comment]
I was testing it out, seems I messed up somewhere. I need to check this out.

**Comment by Aioxas** [comment]
With this it should be good to go. Tested it beforehand.

**Comment by Aioxas** [comment]
A few machines may show a different error than others. This should deal with it.

**Comment by aikaterna** [comment]
Tested and works.

**Comment by tekulvw** [comment]
I'd trust @aikaterna on this one, giving my OK for what it's worth

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/08496d0793f2720fe5befd122ac2832592aebc73

**Pull request closed without merging**
