### PR TITLE
Add `header`, `hyperlink` and `subtext` utilities

### PR DESCRIPTION
**Pull request by Kreusada**
### Description of the changes

Adds new `header` and `hyperlink` utilities, showcased [here](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-).

Their implementation could be up for discussion if anyone has alternative ideas. I could also add a bullet point util to this PR, but I held back due to not knowing how to best implement embedded bullets.

### Have the changes in this PR been tested?

Yes

### CODE REVIEW

**Comment by Kowlin** [comment]
The chance is big that Discord.py will add these to their library, however I'm not opposed to merging this.

**Comment by Jackenmen** [comment]
> The chance is big that Discord.py will add these to their library

That's unlikely, discord.py doesn't have utilities for *constructing* Markdown since most of the time it's trivial to just do it yourself, often shorter. Our whole chat_formatting module is proof of d.py not having such utilities.

**Comment by Kowlin** [comment]
Probably should be updated to also include Subtext 😅

**Comment by Kreusada** [comment]
> Probably should be updated to also include Subtext 😅

Good idea. I've just updated the PR to include this 👍

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
