### PR TITLE
[Launcher and Red.py] Red-DiscordBot-Sharded v1.0

### PR DESCRIPTION
**Pull request by Pierce01**
intro
### PR closed. (I made a mistake with disabling shards, go to the repo for the update. "will you finish v2.0?" eh.

# To-do
* Change file system to a database (or change file system that is shard friendly)
## Description
This is just Red-DiscordBot that can be sharded for the users that have big bots using the base.

## Why did you make this?
Since it seemed that others didn't take sharding as a priority, i whipped up something that allows you to shard with a red base.

## Setting up

If you modified your `red.py` you'll need to copy and paste the code i added.

Same with the launcher. Note, when using `Update Red` in the launcher, the new update may overwrite my code, so you'll need to repaste what i added.

### Setting up your first instance

make sure your shards.json file looks something like
```
{
    "SHARD0": "0",
    "SHARD1": "1",
    "SHARDC": "2",
    "SHARDS": "False"
}
```
SHARDC is for the shard count, so thats the amount of shards you have. 

the shard counting system starts from 0, so if SHARDC (shard count) is set to 2, the two shards would be `0,1`

defaultly, `red.py` is set up to run with shards disabled. You can turn them on in the launcher. When enabling, it'll ask you for a shard ID, you need to type 0, this is `SHARD0`.

example

Both `SHARD0` and `SHARD1` have been defined, but enabling will make you set `SHARD0` to a value, which I'll change, my main goal was to make the the user get a hang of the `Add Value` button which I'll be going over.

next you can run the first instance.

### Setting up your second instance

Setting up the second instance is easy. Go to line 65, and change `SHARD0` to `SHARD1`.

Example2

now run the second instance. that was easy right??

### Now here's the fun stuff.

you might be asking, "how do i add a third one??".

you'll need to add a new value to `shard.json`. open the launcher, and open the shards menu.
select `Add new shard Value` and go through the steps of making a value. Since we started at 0, the third shard will be `2`

Example3

Now redo what i did for the second instance, but instead of `SHARD1` it would be `SHARD2`

## FAQ

1. Why don't all my servers show up??
A. Sharding makes your bot login to only a certain amount of servers, so the other shards fill in the rest.

2. Why didnt my prefix update?
~~A. You need to reload/restart your other shards, its like turning off one stove but leaving the other on, you need to turn the other off also.~~ Data corruption

3. What happened to my custom commands?
A. As for v1.0 of this, there is data corruption. My idea for fixing it is either to wait for a different type of database or to make separate shard files. Idea would be the bot would read both files, but only write to the specific shard file, thus loading cc's from another shard, but not over writing it. "is this possible?" I'll have to look into it more, this is all based off of ideas at the moment.

### CODE REVIEW

**Comment by palmtree5** [comment]
Should fix #713 if merged

**Comment by palmtree5** [comment]
Is there a reason for not using dataIO?

**Comment by Pierce01** [comment]
no reason. didn't even think about it woops. 😅

**Comment by tekulvw** [comment]
Have you come up with a solution that avoids cog data corruption? This has been a priority, but that is the biggest problem we've yet to completely solve.

**Comment by Pierce01** [comment]
## Solution of not changing
I do think in my own opinion, if shards do change servers, most if not all have saved the certain configs for said server. an example would be the custom commands.

## Solution of changing
to prevent data corruption either a temp backup for the day or a temp file could be made for said server/ over all config. Open to ideas though

**Comment by tekulvw** [comment]
I'm not entirely sure what you're trying to communicate so here's why sharding simply won't work with Red as it is today:

1. Each cog loads a complete copy of it's own data, which means that each cog in each shard will load it's own copy.
2. As cogs start accumulating data, that data will ONLY be stored on the shard that made the change. This means that all other shards fall out of sync.
3. As cogs start *saving* data only the LATEST version will be saved to a file and it will completely overwrite any changes made by other shards, leading to blatant data corruption (that will ONLY be visible once you restart the bot).
4. This PR forces a user to modify source code to start secondary shards??? In all honesty, that's not an acceptable way of doing this, not to mention the data corruption that is going to occur.
5. In order to fix the data corruption issue, a new data storage backend will need to be implemented that allows cogs to save only the data that changed to a global data source (e.g. a database). And then each and EVERY cog writer will need to update their cogs to make use of this system, any cogs that don't get updated WILL have data corruption issues.

**Comment by Pierce01** [comment]
I understand, Thank you for explaining. 

I've only started working with the base as of today, due to being asked to make a way for sharding to work for the base. I wasn't aware of each file resetting or being over written by the bot itself (thus causing the big issue), thought it was added on to. I'll look into solving that using different saving method or ~~opening the file in said command, so it would be updated globally when the command is used, and maybe change the overwrite to just add on~~ (I'll experiment)  As for `4`, that was a "draft" idea, so its going to be changed for the future.

Thank you for your time 👍

**Comment by Kowlin** [comment]
@tekulvw But we don't if we just adapt DataIO to use "Drivers"... I *really* don't see the need for cog creators to rewrite their cogs just to support sharding.

**Comment by palmtree5** [comment]
I agree. If there's a way to do this in which we reduce the workload to support sharding, that would be ideal

**Comment by Pierce01** [comment]
I'm messing around with a new file system to include sharding support for the current redbot version.
Since the d.py rewrite will support auto sharding, I'm going to continue this as a project when i have free time.

## What i did so far. 
I made the cogs save and right to normal file paths, only with shard ID included into their file names, so they will be only writing to those shard files, so the other shards wont break. File system is being converted something like this.
```
        c = "data/downloader/repos{}.json".format(self.bot.shard_id)
        f = c.replace("None", "")
```
So json files would be named `filename0.json` or `filename.json` if there are no shards
should it be different?

## Planned
After i finish this, i plan on making it so the bot reads from different shard folders. Depending on the way i plan on doing it, my current idea is ghetto. So I'll look into it when i get to that point

**Comment by Ryonez** [comment]
Sorry if this is a dumb question, but why is this a pull request? The code is still being worked on, and if it's implemented now, it would break to current working code that is in active use.

Note, I'm still new to git really, so I don't know if there's "method behind the madness", as it were.

**Comment by Pierce01** [comment]
I tried PRing v1.0, however people stated the above mistakes, so I'm going back and fixing them 👌

**Comment by Stylite** [comment]
@ryonez it's to show and for progress reports

**Comment by Ryonez** [comment]
I see, thank you for explaining it >.<

**Comment by Twentysix26** [comment]
Sharding will most likely be implemented in the incoming rewrite, as the new discord.py [seems to allow it effortlessly](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.AutoShardedClient).  
@Maxie01 As it stands this PR doesn't solve the main problem, which is the (massive) data loss that such a thing would introduce. Even the last method you described is very hacky, assuming it would work.  
I'm not looking to implement big changes considering that this release is nearing its end and I'm pretty sure that major ones would be required to make sharding work properly here.

**Comment by Pierce01** [comment]
Seems sensible to wait till the rewrite. Thanks for taking your time to read all those comments. 

tip

**Pull request closed without merging**
