### PR TITLE
[Mod] Improved Slowmode

### PR DESCRIPTION
**Pull request by Kowlin**
Updated slowmode with an optional channel argument.

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### CODE REVIEW

**Review by mikeshardmind — CHANGES_REQUESTED** [review]
This isn't safe for the check used. If this is to be added, we need something similar to the voice perm check allowing voice mutes since perms are granular by channel.

**Comment by Kowlin** [comment]
Hmmm, right, the fact that we don't have those at the moment is becoming a real pain in the ass :eyes:

**Comment by mikeshardmind** [comment]
Probably worth implementing the more general thing in #2721 prior to this to allow it to be done in a better way with less duplicated code everywhere we want to use such a pattern.

**Comment by Kowlin** [comment]
Ye I do agree, I'm gonna go ahead and close this until later then.

**Pull request closed without merging**
