### PR TITLE
[V3 Alias] Allow wider range of aliases

### PR DESCRIPTION
**Pull request by Aioxas**
Possible fix for #1118

Makes it so that the only non-valid names are the ones that can't be printed by something.

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Possible fix for #1118

### CODE REVIEW

**Comment by Aioxas** [comment]
Since there is no name that results in false, Tests break. Unless we don't want spaced aliases, then we can change it to "return not str.isspace()"

**Comment by Tobotimus** [comment]
I don't think we want spaced aliases, in fact I don't think they'd work anyway, since the alias parser only checks the first word in the command.

I think a check for containing whitespace would be sufficient. In my opinion this should be done with regex, since it covers additional whitespace chars which don't fall under ascii.

**Comment by Aioxas** [comment]
Just read about it and using isspace() was wrong since it only applies to strings consisting only of whitespace. 

Would `return not bool(re.search(r'/s', str)) ` since it checks for what you asked?

 Got to cast it to bool since it would return a non-boolean object otherwise. As well as invert it due to the nature of the regex.

**Comment by Tobotimus** [comment]
@Aioxas Sounds good to me.

Although I'd keep the `isprintable` check in there too.

**Comment by Aioxas** [comment]
Weirdly enough, attempting to create an alias that has " anywhere in the alias name results in non-execution of the command due to lack of or incorrect args.

**Comment by Tobotimus** [comment]
Nice.

The `"` issue probably comes from the way quoted arguments are passed into commands. I'd be content if we simply didn't allow them to be in an alias name.

**Comment by Aioxas** [comment]
The alias subcommand won't execute at all if there's a `"` on the name, so there's no worry right there

However, it will work if you have it on both sides of the alias name string, but it won't be part of the alias execution command. so `"meow"` will be saved as `meow` and show as `meow`

**Comment by Tobotimus** [comment]
I see what you mean now. That's not a worry then. From a bit of testing with V2's alias, I've found that you can actually have a `"` in your alias by escaping it with a backslash, but that doesn't really matter, since it works as an alias after that.

**Review by Tobotimus — APPROVED** [review]

**Comment by Aioxas** [comment]
Aight cool. Thanks for the help with the PR. Hopefully no further changes for this PR is required.

**Review by palmtree5 — APPROVED** [review]

**Pull request merged**
