### PR TITLE
[Trivia] addition of Chemistry trivia

### PR DESCRIPTION
**Pull request by owocado**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Addition of Chemistry trivia category. Credits to FunTrivia.
133 questions added for now, will add more later.

### CODE REVIEW

**Comment by ellwhy** [comment]
Hi there! 

I recently made another PR (https://github.com/Cog-Creators/Red-DiscordBot/pull/4157) that is also chemistry based. Would you be interested in combining both our chemistry trivias into one cohesive yaml file, with all authors credited? Please let me know!

I've also went ahead and removed any overlapping/repeating questions that my PR's yaml had, in case we decide to keep the chemistry trivias separate.

**Comment by owocado** [comment]
Sounds good to me.

**Comment by ellwhy** [comment]
Neat! Would you like me to create a PR to push my chem trivia yaml to your public repo of Red-DiscordBot, or did you have something else in mind?

Normally I'd do a PR to your branch but it looks like its hidden/private.

**Comment by ellwhy** [comment]
Hi there,

Due to inactivity, we are going to have our chem quiz (#4157) a standalone from this quiz. We've removed any overlap so that combining the two quizzes via bb8 commands won't produce dupe questions.

**Comment by owocado** [comment]
@ellwhy as I already said in my previous reply,  you're free to add/combine the contents of this trivia to #4157 as long as you give credits to me and FunTrivia.

**Comment by ellwhy** [comment]
Perfect! I'll go ahead and do that then.

**Comment by ellwhy** [comment]
yaml for #4157 has been updated to reflect the addition of this PR's chemistry quiz contents. Authors from this PR's yaml have been added to author line.

**Comment by owocado** [comment]
Closing this in favor of #4157

**Pull request closed without merging**
