### PR TITLE
TooManyArguments Error Handling

### PR DESCRIPTION
**Pull request by Redjumpman**
Added handling of TooManyArguments error, when passing `ignore_extra=False` in commands.command()

### CODE REVIEW

**Comment by tekulvw** [comment]
Needs a rebase

**Comment by Twentysix26** [comment]
That and a more user friendly message

**Review by Twentysix26 — CHANGES_REQUESTED** [review]
Rebase and more user friendly message

**Comment by Twentysix26** [comment]
Closing for inactivity

**Pull request closed without merging**
