### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Flame442**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fix typo of "teh" instead of "the".

### CODE REVIEW

**Comment by mikeshardmind** [comment]
I'm not 100% sure this is a typo and not intentional.

See: https://en.wikipedia.org/wiki/Teh 

And [this article](https://live.engadget.com/2006/03/30/world-of-warcraft-pwning-teh-pc-games-market/) (and too many others) where some publisher went a little too far to show they understood it.

**Comment by Flame442** [comment]
It is the only time that spelling is used, and Aika said there was no joke of that kind specific to that character. I don't know my warcraft lore, but this appears to be a typo.

**Comment by mikeshardmind** [comment]
> 
> 
> It is the only time that spelling is used, and Aika said there was no joke of that kind specific to that character. I don't know my warcraft lore, but this appears to be a typo.

I'm also not a Warcraft lore person, was just cautioning against an instant merge off of "typo", when this particular case seemed possible to not be one and wanted confirmation.

**Comment by Tobotimus** [comment]
Gonna say that this is a genuine typo, though I appreciate the heads up :)

**Review by Tobotimus — APPROVED** [review]

**Pull request merged**
