### PR TITLE
Blackjack!

### PR DESCRIPTION
**Pull request by ajm1996**
Integrated a blackjack mini-game in Red's economy system!
55c161be3567a0ca1ac3222f64602d71

### CODE REVIEW

**Comment by Kowlin** [comment]
Please merge this into Cog-changes

**Comment by irdumbs** [comment]
any way to toggle the images to something... less huge?
maybe have the images side-by-side?

**Comment by ajm1996** [comment]
@Kowlin will do
@irdumbs the bot is simply sending an image, which I thought was the cleanest way of going about it. I did shrink them from their original size, but in retrospect I was using them in a text channel dedicated for bot games and it would be obnoxious in most other scenarios. I'll shrink them a bit more and I'm open to ideas.

**Comment by irdumbs** [comment]
I believe @canule was able to draw the cards side-by-side.
perhaps you can ask him.

Some people do prefer the bot not send files/images though, so a toggle between text/image versions would be nice 👍 
If this was a separate cog instead of a PR to a core cog, I wouldn't care about the text/image toggle.

Also, please be more verbose with the command name. 
`q` isn't used in the audio cog, `queue` is.
users can make an alias if they'd like a shorter command

**Comment by ajm1996** [comment]
@irdumbs All I could find was @canule's 4 in a row game in which he used ASCII characters and emjois. By more verbose do you mean you would prefer "blackjack" to "bj"? I started with blackjack but it became obnoxious to fully type it for every action. Forgot there were aliases.
Also would you guys prefer it as a separate cog? Wasn't aware there was a repo for them. I'm open for whatever works best.

@Kowlin should I do a new PR to cog-changes?

**Comment by irdumbs** [comment]
I'd prefer a separate cog. If you put it in a separate cog, I won't bug you about that image/text toggle. In fact, if it's in a separate cog, you can pretty much do whatever you like.
I'd still prefer the cards side-by-side though :3

I said ask @canule, not just poke around his stuff :P He's on the Red server every so often.

Yes, that is what I mean by verbose.

**Comment by ajm1996** [comment]
@irdumbs Already put in the toggle and shrunk the images a bit. Looked for him on the server a few times but haven't seen him online. If everyone likes it I figure I might as well leave it in economy cog because it pairs well with the slots, I don't mind changing some small things.

**Comment by franc-ist** [comment]
@ajm1996 Canule keeps changing names... He's currently known as Mash

**Comment by Twentysix26** [comment]
Well, closing it for now. This is good stuff that it would probably be better as a separate cog that interfaces with economy (currently rewriting economy to make it server based and have better bindings)

**Pull request closed without merging**
