### PR TITLE
allow mentioning the bot as an alternative to using the bot prefix

### PR DESCRIPTION
**Pull request by mikeshardmind**
### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
Modify the prefix manager to allow mentioning the bot as an alternative to using a prefix.

### CODE REVIEW

**Comment by Tobotimus** [comment]
I think this should at least be toggleable by the owner, and disabled by default

**Comment by mikeshardmind** [comment]
Added an argument to argparser as well, there might be more places this would need to be stored if this should be a persistent setting, but it's a start

**Comment by tekulvw** [comment]
Do we want to add a command to make this a persistent, toggleable setting?

**Comment by Kowlin** [comment]
Toggle sounds good.

**Comment by mikeshardmind** [comment]
`when_mentioned_or(*prefixes)` must be passed both the bot and the message.

See the note in [discord.py](https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/bot.py#L48) )

**Review by Tobotimus — APPROVED** [review]
I'm happy with this for now. Can be made persistent and toggleable in another PR.

**Review by Kowlin — APPROVED** [review]

**Comment by mikeshardmind** [comment]
Will re-PR, merging is failing due to the branch being removed.

**Pull request closed without merging**
