### PR TITLE
Issue #171 Add support for m4a audio files 

### PR DESCRIPTION
**Pull request by Pazu-dev**
Issue #171 add and test more supported Audio Extensions
Tested on Windows and Ubuntu

### CODE REVIEW

**Comment by irdumbs** [comment]
can you describe your testing process n such?

**Comment by Pazu-dev** [comment]
Certainly, 
Had a local playlist setup with purchased (unprotected) m4a, "normal" m4a and standard mp3 files. Tested the files in vlc player to make sure no errors in the files existed and that they played all the way through. 
Then tried playing the playlist through the unedited audio.cog and it played the mp3 file only as expected.
They after adding the m4a detection support made sure it would detect and list local playlists with just mp3 files, just m4a files and a mix of m4a and mp3 files. All listed correctly and no duplication of the mixed local playlist.

Then played through the test playlist entirely making sure the songs would play at the correct length and without errors, which was successful.
Also tested skipping songs and pausing and resuming the songs. All completed successfully.

**Comment by Kowlin** [comment]
In theory files such as .m4a's and .vcc's will work. Since there supported by Ffmpeg

**Comment by irdumbs** [comment]
awesome. I approve of allowing m4a's
I'll put vcc on the list to test

**Comment by tekulvw** [comment]
Has anyone tested this?

**Comment by franc-ist** [comment]
@tekulvw m4a's work. tested the whole of Maduk's 12 track LP with only one hiccup, and that was a connection problem from my end.

**Comment by tekulvw** [comment]
@Pazu-dev please resubmit the PR to cog-changes

**Pull request closed without merging**
