### PR TITLE
[Warnings]Make it possible to add reason with unwarn

### LINKED ISSUE #3093: `[p]unwarn` has no arg for reason, and modlog says one is addable
# Command bugs

#### Command name

`[p]unwarn`

#### What cog is this command from?

`warnings`

#### What were you expecting to happen?

There to be a third argument where you can put an optional reason for unwarning the user.

#### What actually happened?

There is no argument that allows you to set the reason. The modlog channel says "**Reason:** Use the `reason` command to add it", implying that you should be able to set a reason without needing to do it in two commands.

#### How can we reproduce this issue?

1. `[p]load warnings`
2. Set up a modlog channel, `[p]modlogset modlog <channel>`
3. `[p]warn` someone
4. `[p]unwarn` them, and note how you cannot add a reason
5. Notice how the modlog says that there is no reason added to the case
6. Use `[p]reason` and notice how you can add a warning to the case

#### Others
I may (attempt!) to PR a fix myself - though I'm a little busy so feel free to do this yourself.
I would like to thank [Skyrider#1337 for reporting this bug](https://discordapp.com/channels/133049272517001216/387398816317440000/639794017596473355). And yes, I waited a whole 11.5 hours for them to open an issue themselves.

### PR DESCRIPTION
**Pull request by Dav-Git**
Might need to be put in Optional[reason: str]

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
This closes #3093 .
PR opened since Vexed is kinda on a break iirc.

### CODE REVIEW

**Comment by Dav-Git** [comment]
The check's didn't fail when I tested with `tox` , not sure what Lint is trying to tell me.

**Comment by Jackenmen** [comment]
It's trying to tell you that you used `points` variable that is not defined in that scope.

**Comment by Jackenmen** [comment]
It might be better to not require to use registered reason in `[p]unwarn` command as reasons registered for warnings will most likely not be really useful as reasons for removing a warning.
This is just an opinion though, not a change request so don't change this unless reviewer assigned to this PR tells you to.

**Comment by Dav-Git** [comment]
I was thinking about that but didn't want to rule out the option of having registered "unwarn reasons"

**Comment by Dav-Git** [comment]
This is continued in #3490

**Pull request closed without merging**
