### PR TITLE
[Mod] Delete commands after X seconds

### PR DESCRIPTION
**Pull request by tekulvw**
Configurable timed deleter, won't throw errors when forbidden either

### CODE REVIEW

**Comment by xdtrammell** [comment]
How is this used,I updated the mod.py file with your commit just not sure what the command is? Thank you so much.

Edit: Thank you for your help on discord.

On top of this issue is there anyway this could be set up to be cleaned up as well. 
http://i.imgur.com/6YWbN9I.png

**Comment by GostOmega** [comment]
@xdtrammell For the request of audio, I recommend to make a text channel for audio commands only, call it music_requests or music_room for example. In the topic of the channel I'd mention a daily wipe of the chat, so at the end of the day you simply do `[p]cleanup messages 9999` (anyone with permissions to manage messages can use the [p]cleanup command).

I use this method to keep certain commands out of general chat, like a slot_machine room for the economy cog, and music_requests for the audio. The mods and I clear chat at the end of the day in those two room, so it's not much of an hassle.

I also recommend utilizing an alias for the cleanup command, `[p]alias add clear cleanup messages` for example, so the results would be `[p]clear #`

**Comment by Kowlin** [comment]
Works like a charm for me.

**Review by Twentysix26 — CHANGES_REQUESTED** [review]
Docstring needs a fix, shows up weird in the help. The setting also needs to show up when you do [p]modset

**Review by Twentysix26 — APPROVED** [review]

**Pull request merged**
