### PR TITLE
Added worldflags trivia

### PR DESCRIPTION
**Pull request by franc-ist**

### CODE REVIEW

**Comment by Twentysix26** [comment]
Using pictures is a pretty cool idea

**Comment by Kowlin** [comment]
Note that discord has support for emoji flags

**Comment by irdumbs** [comment]
guam better be on that list :3
!riot

nice job man, that's cool

**Comment by franc-ist** [comment]
@Kowlin yeah, but not every flag is in discord. @irdumbs pretty much all the flags are there, apart from a few smaller pacific islands

**Comment by irdumbs** [comment]
:cry:

**Pull request merged**
