### PR TITLE
Various improvements in usage of Rich in Red

### LINKED ISSUE #4702: Address various feedback about Rich
Making this issue to make this trackable, here's some actual discussion:
https://discord.com/channels/133049272517001216/718148684629540905/793565318940721272

And an example screenshot showing the issue with visibility of blue color on Windows 10 (this is already using the new cmd color scheme, so it is important that we don't neglect this) that is currently used for numbers and INFO log level (and possibly other things):
image

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [x] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes
Will fix #4702 once this PR gets finished.

Done:
- [x] Add some flags to improve configurability
    - [x] `--rich-traceback-extra-lines` which allows setting the number of additional lines of code before and after the executed line that should be shown in traceback generated by Rich (defaults to 0 which means showing only one line per stack level, similarly to regular Python tracebacks
    - [x] `--rich-traceback-show-locals` which allows to enable showing local variables in tracebacks generated by Rich which can be useful when developing for Red
    - [ ] ???
- [x] Decide on the right colors for everything
    - [/] Make a syntax theme that doesn't look horrible while still being visible in most common terminals
        - this is debatable, but I think I mostly reached that goal
        - when we can, we just use the Monokai theme however, that's not possible for old Command Prompt and Mac OS's Terminal
    - [x] Ensure all used colors are visible in most common terminals
        - [x] Windows
            - [x] CMD
            - [/] (not as important) PowerShell
        - [x] Linux
            - [x] tty console (the one you see on Linux installations without any graphical interface)
            - [x] LXTerminal with Raspberry Pi OS's color scheme
            - [x] (not as important) KDE Konsole
            - [x] (not as important) Gnome Terminal with Ubuntu's color scheme
        - [/] Mac
    	    - [/] Terminal
- [x] Use Rich's default global console object instead of making one for the bot object
- [x] Bump Rich to the latest version
    - [x] Fixed line pointer in tracebacks not rendering on the old Command Prompt (https://github.com/willmcgugan/rich/pull/911)
    - [x] Colors in the output from Rich can now be completely disabled with `NO_COLOR` environment variable
- [x] Disable indent guides in traceback (flare's suggestion)
- [x] Skip empty lines between stack levels in traceback rendering (makes the traceback take fewer rows in the terminal)
- [x] Use full width of the terminal when printing traceback (I think pretty much everyone has a problem with that, which is not surprising lol)
- [x] Disable syntax highlighting on the log messages (let's be honest, it's just too colorful and the highlighting isn't particularly great either...); tracebacks still have syntax highlighting
- [x] Make logger level bold, adjust various stuff about text formatting in loggers
- [x] Show only one line per stack level in tracebacks by default (made configurable with a `--rich-traceback-extra-lines` flag)
- [x] Prevent Rich's console output from being redirected in Dev cog
- [x] Remove usage of Colorama from our code base completely
- [x] Stop highlighting (bolding) `(_)` in Red-DiscordBot splash
- [x] Fix the first row being bolded in tables under the splash

Notes:
Bold on Windows isn't actually bold, Windows instead uses a different shade of the color when text is bolded.

### CODE REVIEW

**Comment by Jackenmen** [comment]
Figuring out the *right* colors for everything in Rich so that it is all readable on the most common terminals (see the list in the issue description) is the only thing left to do here but it's also the most troublesome one. I'll be trying to look into it in the coming days, but I would appreciate all the help with figuring out something that looks acceptable and is not hard to see on different applications. Hopefully, we'll figure something out :/

**Comment by Jackenmen** [comment]
I can't really test colors on Mac OS X so I would appreciate it if someone could run the bash script below.

**Little code pieces for testing the standard 8 colors and their bright and bolded variants:**
Unix:
```bash
#!/bin/bash

TEXT='gYw';

for i in {0..7}
do
    for option in '3' '9' '1;3'
    do
        echo -en "\033[$option${i}m$TEXT\033[0m    ";
    done
    echo;
done
```
Windows (should work on both CMD and PowerShell):
```bat
@echo off
set TEXT=gYw
for /F "delims=#" %%a in ('prompt #$E# ^& for %%a in ^(1^) do rem') do set "ESC=%%a"

for /L %%i in (0,1,7) do (
    for %%o IN ("3" "9" "1;3") do (
        cmd /C exit /b 27
        <nul (set /p z="%ESC%[%%~o%%im%TEXT%%ESC%[0m    ")
    )
    echo:
)
```

**Comment by Jackenmen** [comment]
Default color scheme screenshots

<details>
<summary>Most important terminals</summary>

**Default color scheme screenshots**
Windows - CMD:
image
Linux - tty console
image
Linux - LXTerminal with Raspberry Pi OS's color scheme
image
Mac - Terminal (Catalina)
image
Mac - Terminal (supposedly, Big Sur on dark mode)
image
</details>

<details>
<summary>Less important terminals</summary>

Windows - PowerShell:
image
Linux - LXTerminal with its default color scheme
image
Linux - KDE Konsole
image
Linux - Gnome Terminal with Ubuntu's color scheme
image
Linux - Gnome Terminal with its default color scheme
image
Linux - xterm
image
</details>

And last but not least...
Cool Retro Term! :D
image

**Comment by Jackenmen** [comment]
Here's a first take on the syntax theme colors...
Would love to hear some feedback, as I made those from scratch and I honestly don't know if these are any good, nor what should possibly be changed.

<details>
<summary>Most important terminals</summary>

Windows - CMD:
image
Linux - tty console:
image
Linux - LXTerminal with Raspberry Pi OS's color scheme:
image
Mac - Terminal:
image
</details>

<details>
<summary>Less important terminals</summary>

Windows - PowerShell:
image
Linux - LXTerminal with its default color scheme:
image
Linux - KDE Konsole:
image
Linux - Gnome Terminal with Ubuntu's color scheme:
image
Linux - Gnome Terminal with its default color scheme
image
</details>

**Comment by Drapersniper** [comment]
The bright cyan on mac default (white) is difficult to read and hard on the eye. Other than that everything else is looking good

**Comment by Jackenmen** [comment]
I made the proposed changes and here are screenshots of the updated color scheme on different terminals.

<details>
<summary>Most important terminals</summary>

Windows - CMD:
image
Linux - tty console:
image
Linux - LXTerminal with Raspberry Pi OS's color scheme:
image
Mac - Terminal:
image
</details>

<details>
<summary>Less important terminals</summary>

Windows - PowerShell:
image
Linux - LXTerminal with its default color scheme:
image
Linux - KDE Konsole:
image
Linux - Gnome Terminal with Ubuntu's color scheme:
image
Linux - Gnome Terminal with its default color scheme:
image
Linux - Cool Retro Term :D
image
</details>

If this looks alright, I'll proceed with getting screenshots of the whole Rich output on different terminals, including truecolor monokai color scheme on terminals that support it.

**Comment by Jackenmen** [comment]
I prepared a script that produces output using our styles and Red-like messages which can be used to produce repeatable output without having to install Red in whole. I'll be checking this on all the different terminals which I've already been presenting above. If the used terminal supports true colors, the screenshots will be generated for both the true color variant and the standard 16 colors variant.

https://gist.github.com/jack1142/302f2f4650eab57776b528aae98219fb

I'll be coming with another update soon™

**Comment by Jackenmen** [comment]
Alright, here it is... Red output with Rich tables, logging, colors on all terminals that I've been posting screenshots for before.

<details>
<summary>Most important terminals</summary>

- Windows - CMD
image
- Linux - tty console
image
- Linux - LXTerminal with Raspberry Pi OS's color scheme
    - True color support enabled
    image
    - True color support disabled
    image
- Mac - Terminal
image
</details>

<details>
<summary>Less important terminals</summary>

- Windows - PowerShell:
image
- Linux - LXTerminal with its default color scheme:
    - True color support enabled
    image
    - True color support disabled
    image
- Linux - KDE Konsole:
    - True color support enabled
    image
    - True color support disabled
    image
- Linux - Gnome Terminal with Ubuntu's color scheme:
    - True color support enabled
    image
    - True color support disabled
    image
- Linux - Gnome Terminal with its default color scheme:
    - True color support enabled
    image
    - True color support disabled
    image
- Linux - Cool Retro Term :D
Screenshot from 2021-01-19 22-28-49
</details>

**Comment by Jackenmen** [comment]
This should now be ready for review. PR description has been updated appropriately.

**Comment by Flame442** [comment]
Soft approve, I did not do a full review but this seems to work from my basic testing, and I like the changes.

**Review by TrustyJAID — APPROVED** [review]
Looks good to me!

**Pull request merged**
