### PR TITLE
Add explicit type checking for *_from_id(s) methods (#5459)

### LINKED ISSUE #5459: Config *_from_id(s) methods not typechecking.
### What Red version are you using?

3.4.14

### What were you trying to do?

Trying to access a guild's data from config using the `Config.guild_from_id()` method but accidentally passed in a guild object instead of its id.

### What did you expect to happen?

An error or exception to raise that indicated that my passed value wasn't of type int.

### What actually happened?

The `Config.guild_from_id()` method took the guild object and casted it to a string which turned into the guild's name and upon bot restart, errors were raised about it not being of base 10 for int casting when using the `Config.all_guilds()` method in a cog's initialization

### How can we reproduce this error?

1. Use the `Config.guild_from_id()` method but instead of an integer id, pass a proper guild object.
2. Restart the bot and call the `Config.all_guilds()` method in a cog.

### Anything else?

I'll be happy to push a pr fix for this if needed

### PR DESCRIPTION
**Pull request by i-am-zaidali**
### Description of the changes

This PR adds type checking for the parameters of *_from_id(s) methods in config in order to ensure config files do not break incase parameters are not of type `int`.

If I've made any sort of mistakes, please correct me as this is my first PR and i would be happy to recieve constructive criticism

Fixes #5459

### CODE REVIEW

**Comment by Flame442** [comment]
Your PR has failed the style check, make sure you run [the black code formatter](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md#43-style) on your code.

**Review by Flame442 — CHANGES_REQUESTED** [review]
Since you have deleted the branch/repo for this PR, the changes I am requesting cannot be fulfilled in this PR. Please either make a new PR with these changes, or let us know if you are no longer interested in maintaining this PR so we can recreate it ourselves.

The trailing newline added in the docstrings should be removed (ex L963).
The actual type of the object should be formatted as `obj.__class__.__name__`, not `type(obj)` (ex L966).

**Comment by i-am-zaidali** [comment]
> Since you have deleted the branch/repo for this PR, the changes I am requesting cannot be fulfilled in this PR. Please either make a new PR with these changes, or let us know if you are no longer interested in maintaining this PR so we can recreate it ourselves.
> 
> The trailing newline added in the docstrings should be removed (ex L963).
> The actual type of the object should be formatted as `obj.__class__.__name__`, not `type(obj)` (ex L966).

Ummm sorry i might have accidentally deleted the repo unknowingly. I'll get around to doing it again later and make the necessary changes. Thanks for reviewing this :D

**Comment by Flame442** [comment]
Superseded by #5564.

**Pull request closed without merging**
