### PR TITLE
[Core] Universal config: MongoDB and JSON backend

### PR DESCRIPTION
**Pull request by tekulvw**
Lot's o shit changed, we know have:
 * Defined global/server/channel/role/member/user specific CONFIG variables accessed through a config interface
 * Adds `MONGO_URL` and `MONGO_PORT` keys to red.json WHICH MUST BE SET BEFORE USE
 * Use `bot.get_conf(cogname, some_random_unique_number_or_string_that_SHOULD_NEVER_CHANGE)` to get your global conf object

Quick Example:
```py
conf = bot.get_conf("Test", 12980234578923458902345)

conf.register_global("keyname")
conf.register_server("keyname")
conf.register_channel("keyname")
conf.register_role("keyname")
conf.register_member("keyname")
conf.register_user("keyname")

conf.keyname
conf.set("keyname", value)
conf.set_misc({"test1": "hello"})

conf.server(server_obj).keyname
conf.server(server_obj).set("keyname", value)

conf.channel(channel_obj).keyname

conf.role(role_obj).keyname

conf.member(member_obj).keyname

conf.user(user_obj).keyname

conf.misc()
```

[Example cog](https://github.com/tekulvw/Squid-Plugins/blob/master/example518/example518.py)

### CODE REVIEW

**Comment by palmtree5** [comment]
`pymongo` should probably be added to requirements.txt for this

**Comment by tekulvw** [comment]
should I add something like `misc` in here so people can just dump their current configs/settings in? (that way no one has to waste time writing converters)

**Comment by tekulvw** [comment]
Misc usage has been enabled. This allows you to take any current json and dump it into misc in it's entirety for easy conversion.

**Comment by tekulvw** [comment]
- [ ] remove prints
- [ ] check global set

**Comment by tekulvw** [comment]
[DBMS backend solution](https://trello.com/c/ogw0fsxF/13-dbms-backend-solution)

**Comment by Twentysix26** [comment]
Implemented in the rewrite #770

**Pull request closed without merging**
