### PR TITLE
Shorten the audit log reason appropriately, remove unused vars

### LINKED ISSUE #4187: [Mod] Receiving "wrong" error when banning with more than 512 characters.
# Other bugs

#### What were you trying to do?

Trying to ban a member with over 512 characters.

#### What were you expecting to happen?

Receiving a well-made error.

#### What actually happened?

Bot say `An unexpected error occurred.`

#### How can we reproduce this issue?

Ban someone with more than 512 characters.

### PR DESCRIPTION
**Pull request by madebylydia**
### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

This close #4187.

### CODE REVIEW

**Review by Kowlin — DISMISSED** [review]
Not really happy with the solution here, I'd rather truncate the messages when its being written to modlog and keep the full message within the configs.

**Comment by Jackenmen** [comment]
I think it would be better, if `get_audit_reason()` were updated with a new keyword-only argument called `shorten` (defaulting to `False`) that would automatically shorten the audit reason to 512 characters, if needed. This would allow us to avoid repeating the same code as the current state of the PR does.

If someone from org gives `+1` to this, I can update the PR appropriately myself, otherwise I don't want to because it's a bit more than a minor change.

**Comment by Flame442** [comment]
+1 assuming `shorten` says in the docs that it will shorten to fit the spec of discord audit logs

**Review by Jackenmen — APPROVED** [review]
This should be ready to go now, thanks.

**Pull request merged**
