### PR TITLE
[CI Docs] Allow linkcheck to retry before declaring link broken

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
We all know linkcheck annoyances, this might mitigate our issues with it.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
I'm actually a little concerned about this one. Most of the time where we've seen a link check fail was when multiple PRs were being updated at once and we were getting timed out by remote hosts.

**Comment by Tobotimus** [comment]
So are you saying that this PR would likely make the problem worse..?

**Comment by mikeshardmind** [comment]
Probably not worse for us, as it still requires it to fail at least once for anything to be different, but I don't like the idea of this potentially spamming out more requests when the main failure mode we've seen are being timed out by the remote host.

It might be more valuable to not treat the link check as an error, at least if we can get a GH action or other clear notification that allows us to check if a link really does need replacing.

Otherwise, we can still just restart builds which are erroring in known good cases, without losing the current benefits.

I definitely think it's worth addressing, I'm just not sure if this is how we should.

**Comment by Jackenmen** [comment]
I'm not sure if you can set up recurring link check, but that might be better than doing link check on each PR. It would however be good to also check if any newly added links in PR work (though I don't really know if this can be done sanely)
I don't think it is that bad to do one or two retries for that one link that sometimes *may* fail if there's high chance that's gonna mitigate the issue but it is true that there are alternatives.

**Review by Kowlin — APPROVED** [review]
Looks good.

**Pull request merged**
