### PR TITLE
[Trivia] Fixed typo

### PR DESCRIPTION
**Pull request by Mamalus**
everytime isn't a compound word.

### CODE REVIEW

**Comment by tekulvw** [comment]
This must *really* annoy you

**Comment by hunter30022** [comment]
Lmfao. Leave it for the grammar nazis.

**Comment by Mamalus** [comment]
Nah, it's just something small. I mean trying to help make it better at least.

**Review by tekulvw — APPROVED** [review]

**Comment by Electromaster232** [comment]
Alright, this will go down in the books as one of the odder PRs of Red

**Comment by tekulvw** [comment]
Leave the unnecessary, antagonistic comments out of GH please. This is not a chat forum.

**Comment by hunter30022** [comment]
Yes sir!

**Review by Tobotimus — APPROVED** [review]

**Review by Kowlin — APPROVED** [review]

**Pull request merged**
