### PR TITLE
Ignore fuzzywuzzy slow sequence matcher warning

### PR DESCRIPTION
**Pull request by Tobotimus**
Many users who see this warning seem to panic and think it is worth reporting. I'd rather this just be hidden.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
hmmm. I don't really like hiding this one. It gives users who actually understand the message enough info to get a performance boost if they handle it. If we can intercept the warning and make it more clear that this is not a breakage, I'd find such a solution to be better.

**Comment by Tobotimus** [comment]
I'd rather just have it as a logging.info call then. warnings outputs a code snippet and it looks ugly and causes users to panic

**Comment by mikeshardmind** [comment]
We can detect that we have the slow version from inside red right? If so, keeping the warning suppression, and adding the logging.info call for it would be sufficient

**Comment by Tobotimus** [comment]
Yeah that's exactly what I'm doing :smile:

**Review by mikeshardmind — APPROVED** [review]

**Pull request merged**
