### PR TITLE
added async support for io thru aiofiles

### PR DESCRIPTION
**Pull request by srhinos**
also added backwards compatibility so if this is updated and deps aren't nothing will break. I could add in a forceful update of deps but I dont want to control the local environment of the end user. This is very hastily written though so highly advise it to be reviewed and tested

### CODE REVIEW

**Review by srhinos — COMMENTED** [review]
why did I forget a "

**Review by srhinos — COMMENTED** [review]
whats up with namespaces, anyway

**Review by srhinos — COMMENTED** [review]
""s

**Review by palmtree5 — CHANGES_REQUESTED** [review]
"dependancies" -> "dependencies"
"dependancy" -> "dependency"

**Pull request closed without merging**
