### PR TITLE
Bump black to 20.8b1 (and reformat)

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Dependency update

### Description of the changes
Bumps black version and reformats with it. The biggest fix (but also style/behavior change) in Black 20.8b is proper handling of "magic trailing comma", which you can notice in the diffs.

So Black will now explode collections and any bracket pair **if** a trailing comma is present in it.
Since previous version had some issues with how it handled this, you can see in the diffs that there are places where Black now explodes the collection/bracket pair. There were few places where exploding didn't make sense so I removed the wrongly placed commas there.

As for other changes, Black now formats docstrings and handles some multiline things a bit differently which is what rest of the things in the diff are about.

// It might be worth to wait few days with this as it's very much possible that Black will need some hotfix releases.
There's not that much of reformatting and I don't see anything that could make existing PRs conflict so there's probably no need to postpone this more than aforementioned few days.

### CODE REVIEW

**Review by Drapersniper — APPROVED** [review]
LGTM, the mypy-extension dep is for future plans?

**Comment by Jackenmen** [comment]
> LGTM, the mypy-extension dep is for future plans?

No, it's part of Black's dependencies and we currently include both primary dependencies as well as dependencies that come from primary dependencies.

**Comment by Dav-Git** [comment]
I'm guessing this will update itself with ``make syncenv`` (for dev) and ``pip install`` on my machine (or any one else deving with red)on next release?

**Comment by Jackenmen** [comment]
@Dav-Git yep, [commit `0ff83dd`](https://github.com/Cog-Creators/Red-DiscordBot/pull/4371/commits/0ff83dd905e921b2577c9bd4cd3d4c443efa00b8) handles that

**Pull request merged**
