### PR TITLE
[V3 Mod] QoL change for Userinfo

### PR DESCRIPTION
**Pull request by Kowlin**
### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

QoL change to userinfo. Hides the roles tab if none are found

### CODE REVIEW

**Comment by mikeshardmind** [comment]
I like the changes, but I'd like to see one possible tweak to the docstring with this adding a note that some fields may not be shown if not applicable now that we have both this and the voice channel optional one.

**Comment by Tobotimus** [comment]
Hmm, I think we will need to come to an agreement here. I personally prefer being explicit about the roles, i.e. how it was before.

**Comment by Kowlin** [comment]
I do agree with Sinbad here, my PR should have included help text that explains that roles and names are hidden unless there's actually to show something.

**Comment by Redjumpman** [comment]
I'm bumping this since, there hasn't been any activity or discussion about it since Jun 9th. Have we come to an agreement on what this should look like?

**Review by Tobotimus — APPROVED** [review]
I'm gonna merge this after adding clarification about omitted fields in the help docstring.

**Pull request merged**
