### PR TITLE
Change predefined prefix to use the bot command prefix

### PR DESCRIPTION
**Pull request by phantium**
Changed predefined ! prefix to use the bot command prefix and removed the prefix from the docstrings.

### CODE REVIEW

**Comment by Twentysix26** [comment]
Would be better to use `ctx.prefix`, as it shows the prefix used

**Comment by phantium** [comment]
I only used `self.bot.command_prefix[0]`, because it was used already in the _play function and I wanted to keep it consistent throughout the code.
Do you want me to change that one as well or just this one?

**Comment by tekulvw** [comment]
You don't have ctx in _play iirc so no, you won't be able to make that change, however the first two you removed ! and didn't add the context specific prefix back?

**Comment by phantium** [comment]
Those are docstrings, mind you.

**Comment by phantium** [comment]
I modified the prefix to ctx.prefix and added [p] to the command examples so it's clear they need to specify a prefix.

**Pull request merged**
