### PR TITLE
[Launcher] add function for generating systemd autostart

### PR DESCRIPTION
**Pull request by palmtree5**
Pretty self explanatory. Ideally it would've just put the file in the place it needed to be in but I was getting permissions errors trying to write directly to that location. This also will only work if the OS uses systemd and doesn't have checks in place for that yet

### CODE REVIEW

**Comment by palmtree5** [comment]
Ok, it'll now move it to the right location. Now for systemd checks...

**Comment by palmtree5** [comment]
and systemd checks in. Fails if the return code from `which systemd` is nonzero and exits back to the menu in that case

**Comment by palmtree5** [comment]
Gonna work on extending this to include Upstart, OpenRC, and launchd. Maybe I'll look into trying to autogenerate something that will autostart the bot on Windows too

**Comment by palmtree5** [comment]
Upstart checks in. OpenRC in progress

**Comment by Twentysix26** [comment]
As discussed on Discord I don't think this belongs in the launcher

**Comment by palmtree5** [comment]
not to mention this PR was stale anyway :P

**Pull request closed without merging**
