### PR TITLE
!song shows local file name

### PR DESCRIPTION
**Pull request by franc-ist**
will show the folder and track name e.g. `Playing from local file: 'testing/Crazy in Love (Feat. Leah Kelly)'`

### CODE REVIEW

**Comment by tekulvw** [comment]
First, you should PR to `cog-changes` not `develop`. Second, with the impending audio changes why not just tack this on to the wanted features?

**Comment by franc-ist** [comment]
@tekulvw it is on the wanted features, but that isn't a PR, just an issue. I'll move the PR tho

**Comment by tekulvw** [comment]
I realize it's just an issue, but the audio cog is gonna get wiped out (soon TM) in favor of some rewrite.

**Comment by franc-ist** [comment]
hmm. so where should i stick it?

**Pull request closed without merging**
