### PR TITLE
Spelling correction of method name in Tunnel

### PR DESCRIPTION
**Pull request by Jackenmen**
### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fix for wrong spelling in method name `files_from_attatch`, I changed it to `files_from_attach` in all its appearances.

This is actually breaking change, because of change of method's name, lol.

### CODE REVIEW

**Review by mikeshardmind — COMMENTED** [review]
I'd prefer if this was done in a non-breaking fashion for now given how much QA has recommended people use this method when they need files in a quick and easy way.

```py

    @property
    def files_from_attatch(self):
        return self.files_from_attach

```

Adding this to the Tunnel class with your changes would be sufficient for that, the property could then be removed later on.

**Comment by Jackenmen** [comment]
Because it is static method this would still be breaking change, because now you would have to create instance before using the method. I think it should be enough to just do a simple assignment to old name after defining the method.
```py
files_from_attatch = files_from_attach
```

**Comment by mikeshardmind** [comment]
Right, forgot that was made a static method for a moment.

**Comment by Jackenmen** [comment]
I added it then.

**Comment by Jackenmen** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/blob/e3cb29fbda6cb5d5f7ca30bec209cec96edd9848/redbot/core/utils/tunnel.py#L73-L76
also, I wanted to add PR for this, because it looks like bad logic to me, this will always send the message to the side that started the tunnel, either original channel, or the sender that the bot reacts to on this channel - I think it should be:
```py
send_to = self.recipient if uid == self.sender.id else self.origin
```
I just thought that maybe I could do it in this PR (assuming this isn't some strange logic that I just don't understand)

**Comment by mikeshardmind** [comment]
your logic is solid there and properly fixes the intent (of sending a message of the tunnel being closed to the other end)

**Comment by Jackenmen** [comment]
Can I do it here or should I just do another PR?

**Comment by Tobotimus** [comment]
@jack1142 Another PR would be great for that change.

As for this PR, could you just add this comment above line 161?
```py
# Backwards-compatible typo fix (GH-2496)
```

**Comment by Jackenmen** [comment]
Ayy, I wanted to do that from the beginning (I wouldn't have thought of adding PR number though), I'll commit it in a second

**Comment by Jackenmen** [comment]
@Tobotimus updated, I'll add the other PR later today.

**Review by Tobotimus — APPROVED** [review]
Thanks @jack1142!

**Pull request merged**
