### PR TITLE
[Cleanup] Add `clearchannel` command.

### PR DESCRIPTION
**Pull request by AAA3A-AAA3A**
### Description of the changes

Since deleting messages is limited to 14 days, here is the "[p]cleanup clearchannel" command to dupe a channel and delete the old one in order to remove all messages from it. The request must be approved by a "y" message like the other one and the "manage_channel" permission.
Thanks in advance.

### CODE REVIEW

**Review by i-am-zaidali — COMMENTED** [review]
**From line 87-97**: Message predicate has a [yes_or_no method](https://docs.discord.red/en/stable/framework_utils.html?highlight=yes_or_no#redbot.core.utils.predicates.MessagePredicate.yes_or_no) that you could use to achieve this in a better, more compact way. 

**From line 772-778**: You have 5 percentage signs (%) for formatting, yet you only provide 4 values for it.

**Comment by Twentysix26** [comment]
-1
This introduces a particularly destructive command (can potentially delete years worth of message history) for very little benefit (doing it through the UI from desktop and mobile is trivial) to users that maybe *shouldn't* be able to delete channels that easily (how each server defines "admin" varies greatly and misconfigurations can and do happen).
Finally, in my opinion servers that have this bizarre requirement to wipe entire channels on a regular basis should be using threads to begin with.

**Comment by AAA3A-AAA3A** [comment]
> -1 This introduces a particularly destructive command (can potentially delete years worth of message history) for very little benefit (doing it through the UI from desktop and mobile is trivial) to users that maybe _shouldn't_ be able to delete channels that easily (how each server defines "admin" varies greatly and misconfigurations can and do happen). Finally, in my opinion servers that have this bizarre requirement to wipe entire channels on a regular basis should be using threads to begin with.

I coded it because a server owner needed it. Many bots have this feature. The redbot does not have access to the threads and therefore cannot handle moderation. There may also be spam channels that need to be cleared quickly. I understand what you mean. You are right.
Thanks for your answer!

**Comment by Jackenmen** [comment]
Sorry, this is not functionality we are interested in adding to Core Red. I don't think it's really related to the Cleanup cog and it is way too niche of a use case to be suitable for Core.

If someone wants such a command, it would be better to make a 3rd-party cog for it.

**Pull request closed without merging**
